### ISSUE TITLE
Bump Docker version

### ISSUE THREAD

**Issue by RustyBower** [pglombardo/PasswordPusher#100]
Looks like the current version in Docker Hub is still 1.0. Any chance to bump this to latest with the latest greatest code base?

**Comment by pglombardo** [comment]
Hey @RustyBower - thanks for the reminder.  Will do soon.

**Comment by pglombardo** [comment]
Late but done.  :-)

https://hub.docker.com/u/pglombardo

Let me know if you have any issues with these.

**Comment by RustyBower** [comment]
Just pulled down latest. Thanks!
