### ISSUE TITLE
MySQL doesn't like a default value for TEXT fields (release 1.28.0)

### ISSUE THREAD

**Issue by clmcavaney** [pglombardo/PasswordPusher#1002]
G'day,
Just tried deploying [release 1.28.0](https://github.com/pglombardo/PasswordPusher/releases/tag/v1.28.0)

When the additional database field was being added, this error occured:
`Mysql2::Error: BLOB, TEXT, GEOMETRY or JSON column 'passphrase_ciphertext' can't have a default value`

Can this be changed to have no default value?

references:

- https://github.com/pglombardo/PasswordPusher/blob/bfbb547f765aefe3c079ff38775c304009a7214e/db/migrate/20230406094931_add_passphrase_to_models.rb#L1
- https://dev.mysql.com/doc/refman/8.0/en/blob.html#:~:text=BLOB%20and%20TEXT%20columns%20cannot%20have%20DEFAULT%20values.

**Comment by pglombardo** [comment]
Hi @clmcavaney - thanks for pointing that out.  I'll remove the default value and update the field logic likely sometime over the weekend.

**Comment by pglombardo** [comment]
Just an update:  this affects MySQL servers and oddly not MariaDB.  I believe I have a solution (to also not break non-MySQL users).  

I didn't get to this over this holiday but hopefully soon.

**Comment by MatthewBieda** [comment]
Our new release is also blocked by this.

**Comment by pglombardo** [comment]
Just a quick update.  I thought I coded myself into a corner with this release which would force users to manually revert a migration - but luckily that's not the case.  I'm [making progress](https://stackoverflow.com/questions/76027312/from-a-mysql-client-connection-how-can-i-determine-which-mysql-server-is-in-use/76028229#76028229) and should be able to put a PR together soon.

**Comment by MatthewBieda** [comment]
Great thanks for all the work you do on this project.

**Comment by clmcavaney** [comment]
Agree with Matthew

**Comment by pglombardo** [comment]
Draft PR created in #1002.  Could either (or both) of you run this query to confirm my theory/fix?

`show variables like "version_comment%";`

Looking for what the returned value is.

**Comment by clmcavaney** [comment]
hmm... 
```
show variables like "version_comment%";
+-----------------+----------+
| Variable_name   | Value    |
+-----------------+----------+
| version_comment | (Ubuntu) |
+-----------------+----------+
1 row in set (0.00 sec)
```

**Comment by clmcavaney** [comment]
Also
```
mysql> show variables like "version%";
+-------------------------+-------------------------+
| Variable_name           | Value                   |
+-------------------------+-------------------------+
| version                 | 8.0.32-0ubuntu0.20.04.2 |
| version_comment         | (Ubuntu)                |
| version_compile_machine | x86_64                  |
| version_compile_os      | Linux                   |
| version_compile_zlib    | 1.2.13                  |
+-------------------------+-------------------------+
5 rows in set (0.00 sec)
```

Doesn't show MySQL or MariaDB - frustrating.

**Comment by MatthewBieda** [comment]
This is Azure Database for MySQL

![mysql](https://user-images.githubusercontent.com/63665300/233666827-0715f694-bcf1-4aec-9499-0b4709ffde77.jpg)

**Comment by pglombardo** [comment]
Thanks for the patience on this one.

The fix is in [1.28.2.rc2](https://github.com/pglombardo/PasswordPusher/releases/tag/v1.28.2.rc2) which is building now.  Docker containers with tag `1.28.2.rc2` should be posted soon.

The fix uses [exception handling](https://github.com/pglombardo/PasswordPusher/blob/master/db/migrate/20230406094931_add_passphrase_to_models.rb#L9-L10) to get around the column defaults and then in the [next migration](https://github.com/pglombardo/PasswordPusher/blob/master/db/migrate/20230420175410_fix_passphrase_default.rb) synchronizes all of the database types to be without column defaults.

I set this release as pre-release until either or both of you could kindly confirm the fix.

**Comment by clmcavaney** [comment]
G'day Peter,
Testing this now:
```
Password Pusher: migrating database to latest...
== 20230406094931 AddPassphraseToModels: migrating ============================
-- add_column(:passwords, :passphrase_ciphertext, :text, {:null=>false, :default=>"", :limit=>2048})
-- add_column(:passwords, :passphrase_ciphertext, :text, {:limit=>2048})
   -> 3.0674s
-- add_column(:file_pushes, :passphrase_ciphertext, :text, {:limit=>2048})
   -> 1.0550s
-- add_column(:urls, :passphrase_ciphertext, :text, {:limit=>2048})
   -> 0.7994s
== 20230406094931 AddPassphraseToModels: migrated (5.0028s) ===================

== 20230420175410 FixPassphraseDefault: migrating =============================
-- change_column_null(:passwords, :passphrase_ciphertext, true)
   -> 0.2500s
-- change_column_null(:file_pushes, :passphrase_ciphertext, true)
   -> 0.3514s
-- change_column_null(:urls, :passphrase_ciphertext, true)
   -> 0.3005s
-- change_column_default(:passwords, :passphrase_ciphertext, nil)
   -> 0.3000s
-- change_column_default(:file_pushes, :passphrase_ciphertext, nil)
   -> 0.3338s
-- change_column_default(:urls, :passphrase_ciphertext, nil)
   -> 0.2785s
== 20230420175410 FixPassphraseDefault: migrated (1.8149s) ====================

Password Pusher: precompiling assets...
I, [2023-04-24T01:12:09.991050 #9]  INFO -- : Writing /opt/PasswordPusher/public/assets/application-a992b70d45e06bc5be23ad7206f79fcb6cf6c24c79735d4984241f0b6bbe376b.css
I, [2023-04-24T01:12:09.991371 #9]  INFO -- : Writing /opt/PasswordPusher/public/assets/application-a992b70d45e06bc5be23ad7206f79fcb6cf6c24c79735d4984241f0b6bbe376b.css.gz
Password Pusher: starting puma webserver...
[191] Puma starting in cluster mode...
[191] * Puma version: 6.2.2 (ruby 3.2.2-p53) ("Speaking of Now")
[191] *  Min threads: 5
[191] *  Max threads: 5
[191] *  Environment: production
[191] * Listening on http://0.0.0.0:5100
[191] Use Ctrl-C to stop
[191] - Worker 0 (PID: 193) booted in 0.0s, phase: 0
[191] - Worker 1 (PID: 195) booted in 0.0s, phase: 0
...
```

Looks good!

I can see the new passphrase lockdown feature now:
![image](https://user-images.githubusercontent.com/5875512/233878381-a68213b9-3b92-452b-96a2-9a0a3839bdcf.png)

**Comment by pglombardo** [comment]
Excellent - thanks for confirming!

**Comment by MatthewBieda** [comment]
Works for me!

**Comment by pglombardo** [comment]
Ok [1.28.2](https://github.com/pglombardo/PasswordPusher/releases/tag/v1.28.2) is released.  There are no changes between `1.28.2.rc2` and `1.28.2`.  Containers are building now.

Thanks again for all the help!
