### ISSUE TITLE
copy buttons not working anymore

### ISSUE THREAD

**Issue by tibo59** [pglombardo/PasswordPusher#1020]
## 🐛 Bug Report
Hi, since at least two releases copy buttons not working anymore :
- secret url copy button 
- password copy button ("copy to clipboard")

No messages, no url or password in buffer

## 🔬 How To Reproduce

Create a secret, push it.
Try to copy it with the button, try to copy password with the button

### Environment

Where are you running/using Password Pusher?

- [ ] pwpush.com
- [ X] Docker
  - [X ] pwpush-ephemeral
  - [ ] pwpush-mysql
  - [X ] pwpush-postgres
  - [ ] custom image
- [ ] Heroku
- [ ] Digital Ocean
- [ ] Microsoft Azure
- [ ] Google Cloud
- [ ] AWS
- [ ] Source Code
- [ ] Other (please specify)

If applicable, what version of Password Pusher?

### Screenshots

![image](https://user-images.githubusercontent.com/92431904/232036073-8e2de470-15bf-4c34-a6f4-d123c1049573.png)
![image](https://user-images.githubusercontent.com/92431904/232036138-564031d8-aece-42c9-afc5-70a14daefd68.png)

## 📈 Expected behavior

Copy from action buttons (both url and secret)

**Comment by tibo59** [comment]
Seem need https to work.

**Comment by pglombardo** [comment]
Yeah that's a hassle and a known issue.  The bug is filed in https://github.com/pglombardo/PasswordPusher/issues/734 - it hasn't gotten priority to be fixed with all the other things happening.

**Comment by ddrx1984** [comment]
> ## 🐛 Bug Report
> 
> Hi, since at least two releases copy buttons not working anymore :
> 
>     * secret url copy button
> 
>     * password copy button ("copy to clipboard")
> 
> 
> No messages, no url or password in buffer
> ## 🔬 How To Reproduce
> 
> Create a secret, push it. Try to copy it with the button, try to copy password with the button
> ### Environment
> 
> Where are you running/using Password Pusher?
> 
>     * [ ]  pwpush.com
> 
>     * [ X] Docker
>       
>       * [X ] pwpush-ephemeral
>       * [ ]  pwpush-mysql
>       * [X ] pwpush-postgres
>       * [ ]  custom image
> 
>     * [ ]  Heroku
> 
>     * [ ]  Digital Ocean
> 
>     * [ ]  Microsoft Azure
> 
>     * [ ]  Google Cloud
> 
>     * [ ]  AWS
> 
>     * [ ]  Source Code
> 
>     * [ ]  Other (please specify)
> 
> 
> If applicable, what version of Password Pusher?
> ### Screenshots
> 
> ![image](https://user-images.githubusercontent.com/92431904/232036073-8e2de470-15bf-4c34-a6f4-d123c1049573.png) ![image](https://user-images.githubusercontent.com/92431904/232036138-564031d8-aece-42c9-afc5-70a14daefd68.png)
> ## 📈 Expected behavior
> 
> Copy from action buttons (both url and secret)

hi @tibo59 ,
were you able to solve the problem with the “clipboard”?

**Comment by tibo59** [comment]
> > ## 🐛 Bug Report
> > Hi, since at least two releases copy buttons not working anymore :
> > ```
> > * secret url copy button
> > 
> > * password copy button ("copy to clipboard")
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > No messages, no url or password in buffer
> > ## 🔬 How To Reproduce
> > Create a secret, push it. Try to copy it with the button, try to copy password with the button
> > ### Environment
> > Where are you running/using Password Pusher?
> > ```
> > * [ ]  pwpush.com
> > 
> > * [ X] Docker
> >   
> >   * [X ] pwpush-ephemeral
> >   * [ ]  pwpush-mysql
> >   * [X ] pwpush-postgres
> >   * [ ]  custom image
> > 
> > * [ ]  Heroku
> > 
> > * [ ]  Digital Ocean
> > 
> > * [ ]  Microsoft Azure
> > 
> > * [ ]  Google Cloud
> > 
> > * [ ]  AWS
> > 
> > * [ ]  Source Code
> > 
> > * [ ]  Other (please specify)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > If applicable, what version of Password Pusher?
> > ### Screenshots
> > ![image](https://user-images.githubusercontent.com/92431904/232036073-8e2de470-15bf-4c34-a6f4-d123c1049573.png) ![image](https://user-images.githubusercontent.com/92431904/232036138-564031d8-aece-42c9-afc5-70a14daefd68.png)
> > ## 📈 Expected behavior
> > Copy from action buttons (both url and secret)
> 
> hi @tibo59 , were you able to solve the problem with the “clipboard”?

Good morning,
You had to set up https for it to work.
But I haven't tested the new versions.

**Comment by ddrx1984** [comment]
> > > ## 🐛 Bug Report
> > > Hi, since at least two releases copy buttons not working anymore :
> > > ```
> > > * secret url copy button
> > > 
> > > * password copy button ("copy to clipboard")
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > No messages, no url or password in buffer
> > > ## 🔬 How To Reproduce
> > > Create a secret, push it. Try to copy it with the button, try to copy password with the button
> > > ### Environment
> > > Where are you running/using Password Pusher?
> > > ```
> > > * [ ]  pwpush.com
> > > 
> > > * [ X] Docker
> > >   
> > >   * [X ] pwpush-ephemeral
> > >   * [ ]  pwpush-mysql
> > >   * [X ] pwpush-postgres
> > >   * [ ]  custom image
> > > 
> > > * [ ]  Heroku
> > > 
> > > * [ ]  Digital Ocean
> > > 
> > > * [ ]  Microsoft Azure
> > > 
> > > * [ ]  Google Cloud
> > > 
> > > * [ ]  AWS
> > > 
> > > * [ ]  Source Code
> > > 
> > > * [ ]  Other (please specify)
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > If applicable, what version of Password Pusher?
> > > ### Screenshots
> > > ![image](https://user-images.githubusercontent.com/92431904/232036073-8e2de470-15bf-4c34-a6f4-d123c1049573.png) ![image](https://user-images.githubusercontent.com/92431904/232036138-564031d8-aece-42c9-afc5-70a14daefd68.png)
> > > ## 📈 Expected behavior
> > > Copy from action buttons (both url and secret)
> > 
> > 
> > hi @tibo59 , were you able to solve the problem with the “clipboard”?
> 
> Good morning, You had to set up https for it to work. But I haven't tested the new versions.

Good morning @tibo59 ,
Thank you for your message.
I set up my Docker like this:

docker run --name pwpush1 -d -p "5100:5100"
-e PWP__BRAND__LIGHT_LOGO=/logos/mylogo.png
-e PWP__DEFAULT_LOCALE=de
-v /var/lib/pwpush/logos:/opt/PasswordPusher/public/logos
pglombardo/pwpush:latest



I'm currently sending it locally without https / I have the current version v1.34.5.
Can you show me how to set up the whole thing on https?

Thanks
