### ISSUE TITLE
no translations for Passphrase Lockdown feature

### ISSUE THREAD

**Issue by tibo59** [pglombardo/PasswordPusher#1021]
## 🐛 Bug Report

Hello,
i notice that the Passphrase Lockdown feature appears only in english.
There is no segments to translate in https://translation.io/

## 🔬 How To Reproduce

Choose a language other than English

### Environment

Where are you running/using Password Pusher?

- [X ] pwpush.com
- [X ] Docker
  - [ ] pwpush-ephemeral
  - [ ] pwpush-mysql
  - [X ] pwpush-postgres
  - [ ] custom image
- [ ] Heroku
- [ ] Digital Ocean
- [ ] Microsoft Azure
- [ ] Google Cloud
- [ ] AWS
- [ ] Source Code
- [ ] Other (please specify)

If applicable, what version of Password Pusher?

![image](https://user-images.githubusercontent.com/92431904/232038306-345f25f1-edd3-4373-93a8-84a0c28fc630.png)

**Comment by pglombardo** [comment]
HI @tibo59 - they're coming.  New features usually take another release to get translated.  Thanks for pointing it out - I'll pull the latest string and release again soon.

**Comment by pglombardo** [comment]
https://github.com/pglombardo/PasswordPusher/releases/tag/v1.28.1 is building now.  This adds the missing translations and fixes some others.

Closing but let me know if you see any issues.  We can reopen if so.
