### ISSUE TITLE
Show hide Header and Footer completely

### ISSUE THREAD

**Issue by sonphnt** [pglombardo/PasswordPusher#1024]
## 🚀 Feature Request

A new setting that allows controlling Header and Footer to be hidden/shown
## 🔈 Motivation

I would like to hide the full footer or header completely, 
There is already a setting in the footer that allows showing/hiding the footer menu but not for the logo and also the copyright

Thanks

**Comment by pglombardo** [comment]
Hi @sonphnt - unfortunately I have no plans to do this.  You're always welcome to fork and modify your copy of the repository though.  That would be the best path for this functionality.

I hope this helps.  Let me know if you have any questions.
