### ISSUE TITLE
API returns null values

### ISSUE THREAD

**Issue by fabian-we** [pglombardo/PasswordPusher#106]
Hi!
I'm trying to test the API and I'm getting a broken response only filled with null values:
```
{
  "id": null,
  "payload": null,
  "expire_after_days": null,
  "expire_after_views": null,
  "expired": false,
  "url_token": null,
  "created_at": null,
  "updated_at": null,
  "user_id": null,
  "deleted": false,
  "first_view": false,
  "deletable_by_viewer": true
}
```

The response code is 200, not 201 as I'm getting with the curl example.

I'm testing with Insomnia REST client with the following parameters:
POST: `{ "password[payload]": "mypassword", "password[expire_after_days]": "2", "password[expire_after_views]": "10" }`
Headers:
_Content-Type: application/json
Accept: application/json_

Any idea what I'm doing wrong?

**Comment by pglombardo** [comment]
Hi @fabian-we - I'm not sure honestly but I suspect it has something to do with the Insomnia client as curl, JS and the 3rd party tools all seem to be working still.

Another possibility:  where are you sending the requests?  To pwpush.com or a private instance?  If private and you save a password via the UI form, does it work?

**Comment by fabian-we** [comment]
Hi @pglombardo,
I'm planning to use a private instance, but currently I'm testing with pwpush.com/p.json.

I digged a little deeper, and now I got it!

URL encoding (like the curl example) works:
```
POST https://pwpush.com/p.json HTTP/1.1
Host: pwpush.com
User-Agent: insomnia/6.6.2
Content-Type: application/x-www-form-urlencoded
Accept: application/json
Content-Length: 102

password%5Bpayload%5D=mypassword&password%5Bexpire_after_days%5D=2&password%5Bexpire_after_views%5D=10
```
JSON payload doesn't seem to work:
```
POST https://pwpush.com/p.json HTTP/1.1
Host: pwpush.com
User-Agent: insomnia/6.6.2
Content-Type: application/json
Accept: application/json
Content-Length: 116

{ 
 "password[payload]": "mypassword",
 "password[expire_after_days]": "2",
 "password[expire_after_views]": "10" 
}
```

I never programmed Ruby, but after reading this [Stackoverflow question](https://stackoverflow.com/questions/12221634/get-a-json-as-post-parameter), I had the idea to change the JSON to this:
```
{
 "password": 
  {
    "payload": "mypassword",
    "expire_after_days": "2",
    "expire_after_views": "10" 
   }
}
```
And this works just fine.

Perhaps you should add this info to the API example page, for the case of using `Content-Type: application/json`.

**Comment by pglombardo** [comment]
Updated - thanks @fabian-we!

https://github.com/pglombardo/PasswordPusher/wiki/Password-API

**Comment by pglombardo** [comment]
Hi @fabian-we - just a note that I just added authentication to the JSON API so you can track pushes, view audit logs etc. etc.  I put a short twitter thread here: https://twitter.com/pwpush/status/1563889107536941057

Hope all is well!

**Comment by sergeevabc** [comment]
How do I send a message in a language other than English?
For example, `"payload": "привет"` is then rendered as ?????? on the web.

**Comment by pglombardo** [comment]
> How do I send a message via JSON API in a language other than English?
> For example, "payload": "привет" is then rendered as ?????? on the web.
> Solution. Add charset to Add -ContentType "application/json; charset=utf-8"

😎 

> And this one returns nothing at all:
> curl -X POST --data "password[payload]=привет" https://pwpush.com/p.json

This one works for me:

<img width="1466" alt="Screenshot 2024-02-06 at 09 39 23" src="https://github.com/pglombardo/PasswordPusher/assets/395132/b5ee524d-632f-4776-b7f2-f3363fcafc10">
<img width="834" alt="Screenshot 2024-02-06 at 09 35 39" src="https://github.com/pglombardo/PasswordPusher/assets/395132/154c0a05-1f91-4727-8b81-2427a8d6cbec">


This one doesn't work (good find):

> This one returns an error:
> $.post('https://pwpush.com/p.json',{ 'password[payload]': 'привет', 'password[expire_after_days]': '1', 'password[expire_after_views]': '1' }, function(data) { alert(data.url_token) } )
> Uncaught TypeError: $.post is not a function

`$` is part of JQuery which pwpush doesn't use anymore.  That is old documentation that needs to be updated.

**Comment by pglombardo** [comment]
Hi all - just an update that the API has some changes coming soon that shouldn't break anything but just in case, see #3068.
