### ISSUE TITLE
Disable some languages.

### ISSUE THREAD

**Issue by technofab** [pglombardo/PasswordPusher#1078]
Hi Peter and all.. I've edited settings.yml and dashed some language. But wich is the right way do disable languages? 

![image](https://user-images.githubusercontent.com/14272723/235664409-4fa4e0dc-cb10-41de-824b-be98caafa94a.png)

**Comment by pglombardo** [comment]
Hi @technofab - this hasn't been requested before so it's not possible currently with `settings.yml`.  To remove languages, you have to remove the language codes from [this line](https://github.com/pglombardo/PasswordPusher/blob/master/config/initializers/translation.rb#L2) in `config/initializers/translation.rb`.

I can move that language list to `settings.yml` to make this easier which is probably the right move.  Let me see if I can add this soon.

**Comment by technofab** [comment]
Ok for now i can mount a modified version removing languages where we are not interested. Thanks for now.

**Comment by pglombardo** [comment]
Added the [ability to disable individual languages](https://github.com/pglombardo/PasswordPusher/blob/master/config/settings.yml#L707-L708).  [v1.28.6](https://github.com/pglombardo/PasswordPusher/releases/tag/v1.28.6) is building now.

Thanks for pointing this out @technofab!
