### ISSUE TITLE
When using REST API call password[first_view] is ignored

### ISSUE THREAD

**Issue by pgarm** [pglombardo/PasswordPusher#110]
Been writing a [PoSh module](https://github.com/pgarm/pwposh) with Invoke-RestMethod to work against pwpush, so that it can be used in PoSh Core.
Hit a hurdle - when adding `password[first_view] = "False"` expected result is to have the first "sender" view already consumed. Instead the API response is True and actual result is the first view experience (with "Copy link" etc.) still presented when opening the hyperlink.

Not a major problem, worked around it by emulating first view with generic web request. Still might be cleaner to actually process it on the service side.

**Comment by pglombardo** [comment]
I wonder if this could be related to how the form data is processed.  Could you try `password[first_view] = "false"`?  (lower case "f")

If Ruby processes that value as a string (and isn't converted to a boolean), then it would result in `true` since its non nil.

**Comment by pglombardo** [comment]
Nice project BTW!

**Comment by pgarm** [comment]
Thanks :)
Seems to be some other quirk - constructed the body with lowercase, still get True for first_view in reply (and opening the link I get the "This is your password. Use this secret link to share it:" piece
```powershell
PS C:\Users\pavel.garmashov\GitHub\pwposh> $body

password
--------
@{payload=0xDk^?(C; expire_after_days=7; expire_after_views=5; deletable_by_viewer=true; first_view=false}

PS C:\Users\pgarm\GitHub\pwposh> Invoke-RestMethod -Method 'Post' -Uri $url -ContentType "application/json" -Body ($body | ConvertTo-Json)

id                  : 504654
payload             : zV8WRryV1EM7XN3T8ieM2w==

expire_after_days   : 7
expire_after_views  : 5
expired             : False
url_token           : l0gwx81xd9aathp7
created_at          : 30/09/2019 11:40:39
updated_at          : 30/09/2019 11:40:39
user_id             :
deleted             : False
first_view          : True
deletable_by_viewer : True
```

BTW, any other methods accessible via API? Like pulling the password based on link, which could be pretty useful in cross-company scripting.

**Comment by pglombardo** [comment]
Ok you're right.  New password records are created by default with a `first_view` of true:
https://github.com/pglombardo/PasswordPusher/blob/ff35d37f4e37f8b83364785c5b0a163a331bdae9/app/controllers/passwords_controller.rb#L78-L80

So it's not even checking for that in the POST body.

> BTW, any other methods accessible via API? Like pulling the password based on link, which could be pretty useful in cross-company scripting.

You can append `.json` to any URL and you will get a JSON response instead of HTML.

To retrieve a password:
`curl -X GET https://pwpush.com/p/<ID>.json`

Or to destroy a password (regardless of views/expiration) use method DELETE
`curl -X DELETE https://pwpush.com/p/<ID>.json`

Note that destroy is only possible if the option was set (`password[deletable_by_viewer]` was set to true) when the password record was created.

![Screen Shot 2019-09-30 at 2 12 31 PM](https://user-images.githubusercontent.com/395132/65877692-8fdc0b00-e38c-11e9-98d7-d7f24f8d8772.png)

...and that JSON requests retrieve a password eats up a view just like a browser view.

I updated the Wiki Page with these examples too:
https://github.com/pglombardo/PasswordPusher/wiki/Password-API#other-endpoints

**Comment by pgarm** [comment]
Grand, thanks a mil!
I'll get some time to build the retrieve and delete in the PoSh module for completeness.

If you get a chance to do the check on the service side, would be perfect. As in the OP, not a big deal as it's just an extra request - but might become a problem for large-scale operations.

**Comment by pgarm** [comment]
Ran a few more tests with other endpoints - might be a PoSh glitch, but seems the Get and Delete throw some weird responeses:
```powershell
PS C:\Users\pgarm\GitHub\pwposh> Invoke-RestMethod -Method 'Get' -Uri "https://$Server/p/$($Reply.url_token).json"

id                  : 504654
payload             : zV8WRryV1EM7XN3T8ieM2w==

expire_after_days   : 7
expire_after_views  : 5
expired             : False
url_token           : l0gwx81xd9aathp7
created_at          : 30/09/2019 11:40:39
updated_at          : 30/09/2019 11:45:05
user_id             :
deleted             : False
first_view          : False
deletable_by_viewer : True
```
even though the counter properly decreases, the password returned is in Base64-encoded hash (not really useful for the retriever), and the view counter in JSON, as well as last modification timestamp, remain as at the time of first view.
Maybe it's just me being dumb ;)

```powershell
PS C:\Users\pgarm\GitHub\pwposh> Invoke-RestMethod -Method 'Delete' -Uri "https://$Server/p/$($Reply.url_token).json"
Invoke-RestMethod : {"id":504654,"payload":null,"expire_after_days":7,"expire_after_views":5,"expired":true,"url_token":"l0gwx81xd9aathp7","created_at":"2019-09-30T11:40:39.475Z","updated_at":"2019-09-30T18:43:02.580Z","user_id":null,"deleted":true,"first_view":false,"deletable_by_viewer":true}
At line:1 char:1
+ Invoke-RestMethod -Method 'Delete' -Uri "https://$Server/p/$($Reply.u ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (Method: DELETE, Req…ontent-Length: 0
}:HttpRequestMessage) [Invoke-RestMethod], HttpResponseException
+ FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
```
The method call throws an error, but actually deletes the record (and that's returned in JSON response. Could be a PoSh problem, as the curl request completes without any issue, silently.
I'll play around with that...

**Comment by pglombardo** [comment]
Doh - on the `GET`, the JSON response code is returning the raw database model with the password encrypted as it is in the database.  :-(  I'll need to fix that in the application.

The `DELETE` error is odd.  Not sure about that one at first glance...

Let me see if I can get some time in the next couple days to fix that JSON Get.  As for the Delete - hrm need to think about that one for a bit.  :-)

**Comment by pglombardo** [comment]
So two tasks:

1. Honor `first_view` in Post body
2. Decrypt password in Get JSON response.

I'll do this in the next release hopefully soon.

**Comment by pgarm** [comment]
I'm trying to get my head around the `DELETE` as well, might need to play around with Wireshark to see the actual response. Probably the result code returned as anything but 200/OK is treated by PoSh as a error.

On the `GET` side, maybe nice to get the number of remaining views as well (in addition to total max views as of now). Not too relevant for automation in admin work, but might be useful if people build that into workflows.

I'll build the Pull function assuming it returns the decrypted value for now, should be ready for people to use against next release. I'll probably add a check in to cover for private instances that are not updated - fail gracefully with a message that the password returned was encrypted.

**Comment by pgarm** [comment]
> I'm trying to get my head around the `DELETE` as well, might need to play around with Wireshark to see the actual response. Probably the result code returned as anything but 200/OK is treated by PoSh as a error.

The code returned is indeed HTTP/500
`$Error[0].Exception   
Response status code does not indicate success: 500 (Internal Server Error).`

**Comment by pgarm** [comment]
Ok, the current version of PwPoSh has delete and retrieve (in two varieties, over REST and WEB) functions done. Sort of ready for public use, I'll wait for more live testing done by others and then mark as release.
Will amend later after your next release.

**Comment by pglombardo** [comment]
Also fixed the 500 on Delete in https://github.com/pglombardo/PasswordPusher/pull/115.

All deployed and live.

**Comment by pgarm** [comment]
Thanks a mil Peter for the effort put into the tool!
Finally got some time to test extensively - these three are indeed behaving now :)
I'll leave the catches in the PoSh module for some time as deprecated ones to cater for people using older builds of PasswordPusher for private instances.

Found two new ones - #117, #118, and created a separate #119 for the remaining views / modify timestamp

**Comment by pglombardo** [comment]
Thanks @pgarm - I'll get on those other issues hopefully soon.  It's the end of year crunch right now so I'm juggling a bit currently.

**Comment by pgarm** [comment]
Feel ya. Same thing here :)

**Comment by pglombardo** [comment]
Hi @pgarm - It's been a long while on this issue but just an update that the API has some changes coming soon that shouldn't break anything but just in case, see #3068.

Hope all is well!
