### ISSUE TITLE
QR Code, for Created URL, in Preview Page

### ISSUE THREAD

**Issue by Viajaz** [pglombardo/PasswordPusher#1100]
## 🚀 Feature Request
It would be useful of the generated URL (on the preview page) was available as a QR code.
This could perhaps be shown by clicking a QR code button next to the current "copy" button on the right of the field.

## 🔈 Motivation

1. Some interface users need the password URL on their mobile device but the available information, to generate the URL (eg: the password, secret etc.), is on their workstation, and the two are air-gapped/not-connected. Scanning a QR code has a reduced attack surface than other forms of communication between two devices in this scenario.
2. Useful if it needs to be printed (eg: poster) and consumed by end-users, in meatspace, using their mobile devices.

## 🛰 Alternatives
Using a browser extension or separate application.

**Comment by pglombardo** [comment]
Hey @Viajaz - I'll be releasing this soon (#2037)

![Screenshot 2024-04-09 at 13 40 17](https://github.com/pglombardo/PasswordPusher/assets/395132/05bd55ca-8417-4192-8370-6365b0c30e56)

**Comment by pglombardo** [comment]
I'm still considering making a "printable" page with only the QR code and expiration message...

**Comment by pglombardo** [comment]
Released in [v1.40.0](https://github.com/pglombardo/PasswordPusher/releases/tag/v1.40.0).  Thanks for the suggestion!
