### ISSUE TITLE
Forgot password

### ISSUE THREAD

**Issue by orangetigger813** [pglombardo/PasswordPusher#1171]
## Checklist

- [ ] I've searched the project's [`issues`](https://github.com/pglombardo/pwpush/issues?q=is%3Aissue).
- [ ] I've searched the project's [`discussions`](https://github.com/pglombardo/PasswordPusher/discussions).

## ❓ Question

How can I [...]?

Is it possible to [...]?

**Comment by pglombardo** [comment]
If you forgot your password on pwpush.com, please use [this link](https://pwpush.com/en/users/password/new) to reset your password.

I'll close out this issue but if anything remains, please let me know.
