### ISSUE TITLE
Returned password in initial response for new password push is in encrypted format

### ISSUE THREAD

**Issue by pgarm** [pglombardo/PasswordPusher#118]
Found this when doing tests for closure of #110 
JSON response to initial push has the password in encrypted form. Could be used to try executing an attack to determine algorithm/salt/key used to encrypt passwords in the database.

```
{                                             
    "id":  544432,
    "payload":  "BjbUVut76ToMpxDBNXgUlw==\n", 
    "expire_after_days":  7,                  
    "expire_after_views":  5,
    "expired":  false,
    "url_token":  "i0y8opzc6oo7uvdz",
    "created_at":  "2019-11-19T15:05:58.023Z",
    "updated_at":  "2019-11-19T15:05:58.023Z",
    "user_id":  null,
    "deleted":  false,
    "first_view":  false,
    "deletable_by_viewer":  true
}
```

**Comment by pglombardo** [comment]
This was fixed in the (recent?) past:

![Screen Shot 2020-09-05 at 1 12 06 PM](https://user-images.githubusercontent.com/395132/92303889-90f0c180-ef79-11ea-9464-2c26f31349ff.png)

Thanks for all the help @pgarm
