### ISSUE TITLE
German translation error

### ISSUE THREAD

**Issue by markusglaetzner** [pglombardo/PasswordPusher#1198]
There is a little translation error in the german version, when you open the generated link:
actual: "Der geheime Link uns sämtlicher Inhalt..."
correct: "Der geheime Link und sämtlicher Inhalt..."

**Comment by pglombardo** [comment]
Thanks @markusglaetzner!  Im traveling for the next few weeks so I'll make this change once I'm back.

**Comment by pglombardo** [comment]
Hi @markusglaetzner - I've made the fix even though I don't speak German so fingers crossed that it is correct.  :-)

<img width="328" alt="Screenshot 2023-07-25 at 18 20 26" src="https://github.com/pglombardo/PasswordPusher/assets/395132/03deac68-6bc8-450d-b0e3-f0ad2fe69b38">

Thanks for pointing this out.  The updated string will go out in a release soon.

**Comment by pglombardo** [comment]
This fix has been released in the latest versions.  Thanks for the help @markusglaetzner!
