### ISSUE TITLE
SSL deployment

### ISSUE THREAD

**Issue by itcentrenz** [pglombardo/PasswordPusher#120]
Any chance you could add some high-level instructions on a SSL deployment?

**Comment by pglombardo** [comment]
Hi @itcentrenz that's a very broad topic that is covered already by a bunch of blogs and guides.  It really depends on what you're using (HAProxy, Nginx, Apache, Heroku, GCE etc. etc.)

What might be helpful is some past discussions in issues you can find here:
https://github.com/pglombardo/PasswordPusher/issues?q=is%3Aissue+ssl+is%3Aclosed

If those don't help, let me know a bit about your environment and how you want to set it up and maybe I can provide some guidance.

Hope this helps - let me know on the above!

**Comment by pglombardo** [comment]
One more thing, by far the easiest setup is to deploy to Heroku and configure their SSL option:
https://github.com/pglombardo/PasswordPusher#deploy-to-heroku

**Comment by itcentrenz** [comment]
Hi Peter,
Thanks for getting back to me. I got it working after logging the issue. We’re using Apache as the reverse proxy.

I had the proxy working, and figured out I need to turn on force_ssl for the production environment, but that then caused a redirection loop for the pwpush front page.

Turns out the simple fox was to add this line to the Apache config:
RequestHeader set "X-Forwarded-Proto" expr=%{REQUEST_SCHEME}

Thanks again for getting back to me.

Kind regards,
Sam Thomas

**Comment by pglombardo** [comment]
Ok that's great  to hear.  I hit that redirect loop issue before and it took a while for me to resolve it so good that you found that fix so quick.

I'll close this issue then.  For any other issues/questions, feel free to file another issue.

Best,
Peter
