### ISSUE TITLE
Login page footer not rendering properly

### ISSUE THREAD

**Issue by ekadin-mtc** [pglombardo/PasswordPusher#1219]
## 🔬 How To Reproduce

1. Navigate to Login page (signups are disabled)

### Environment

Where are you running/using Password Pusher?

- [ ] pwpush.com
- [x ] Docker
  - [ ] pwpush-ephemeral
  - [x ] pwpush-mysql
  - [ ] pwpush-postgres
  - [ ] custom image
- [ ] Heroku
- [ ] Digital Ocean
- [ ] Microsoft Azure
- [ ] Google Cloud
- [ ] AWS
- [ ] Source Code
- [ ] Other (please specify)

If applicable, what version of Password Pusher?

### Screenshots

![pwpush_loginpage](https://github.com/pglombardo/PasswordPusher/assets/105028623/28a5b3ed-9aef-4690-a5ab-bd6492de5ce3)
## 📈 Expected behavior

![pwpush_loginpage-correct](https://github.com/pglombardo/PasswordPusher/assets/105028623/c89e80cd-5bd5-4b56-9954-d289bbd68241)

**Comment by pglombardo** [comment]
Hi @ekadin-mtc -  what container tag are you using?


That is a language string issue. I'm traveling for the next couple weeks but once I get back I'll take a closer look. 

Peter

**Comment by ekadin-mtc** [comment]
Hi @pglombardo - I was using pwpush-mysql:release when I experienced the issue. I just tried pwpush-mysql:latest and it is fixed there.

Thanks for all your work!

**Comment by pglombardo** [comment]
Excellent.  Once I get back I'll update the tags and push out the new release.
