### ISSUE TITLE
What makes a good CRYPT_KEY or CRYPT_SALT?

### ISSUE THREAD

**Issue by kleinfelter** [pglombardo/PasswordPusher#122]
environment.rb says "# If deploying PasswordPusher yourself, you should change these CRYPT values."

Maybe you could add a few words to the FAQ about how to pick a new value for these?  Will I break something if I change the length of either of these fields?  Should I just copy data from /dev/urandom for the right number of bytes?

**Comment by pglombardo** [comment]
Hi @kleinfelter - Good points.  I'll add something to the FAQ and potentially a code comment.  Thanks.

**Comment by huiguang-liang** [comment]
Not sure if this helps, but with the Docker build, I mapped `/opt/PasswordPusher/config/` to a persistent `docker/PasswordPusher/config/`, and made the following changes to `docker/PasswordPusher/config/environment.rb`:

```
+                require 'securerandom'

-                CRYPT_KEY = ENV.fetch('CRYPT_KEY', '}s-#2R0^/+2wEXc47\$9Eb')
-                CRYPT_SALT = ENV.fetch('CRYPT_SALT', ',2_%4?[+:3774>f')
+                CRYPT_KEY = SecureRandom.base64(24)
+                CRYPT_SALT = SecureRandom.base64(24)
```

My knowledge of Ruby and Docker is very sketchy at best. Use at your own peril.

**Comment by pglombardo** [comment]
This seems like a nice solution!

On the ephemeral, something like this should potentially be the default - regenerate each reboot since the DB doesn't persist...

**Comment by pglombardo** [comment]
The encryption in Password Pusher has been updated along with much better documentation:

https://pwpush.com/en/pages/generate_key

Cycling the encryption key on each ephemeral restart is still a valid (and nice) feature request.  I filed #272 to track and eventually implement.

I'm closing out this issue for now.  If anything remains, please let me know.
