### ISSUE TITLE
How to Reload App After Config Change

### ISSUE THREAD

**Issue by dbuehler77** [pglombardo/PasswordPusher#124]
I'd like to change the two default password expiration settings below, which are found in app.json

```
EXPIRE_AFTER_VIEWS_DEFAULT
EXPIRE_AFTER_DAYS_DEFAULT
```
After changing the values for these settings in the app.json file, what do I need to do to reload the application and apply those settings?

**Comment by pglombardo** [comment]
Hi @dbuehler77 - If you're running the app on Heroku (which is what that app.json is used for), those values are just for setting up the initial Heroku config.  If you go to your application dashboard --> Settings, you can change those settings under "Config Vars"

![Screen Shot 2020-03-02 at 10 46 48 AM](https://user-images.githubusercontent.com/395132/75664678-2762c400-5c73-11ea-9cb7-e63ed4447358.png)


![Screen Shot 2020-03-02 at 10 45 06 AM](https://user-images.githubusercontent.com/395132/75664570-f2ef0800-5c72-11ea-955f-7c4ae9d30e59.png)

If you're not running in Heroku, then you can instead just edit [this file](https://github.com/pglombardo/PasswordPusher/blob/master/config/environment.rb#L10-L18) and restart the application.

**Comment by dbuehler77** [comment]
Hey @pglombardo - I'm not running in Heroku, so I'll follow the bottom instructions. Thanks!

**Comment by pglombardo** [comment]
Closing this issue.  Feel free to file another if any issues remain.  Thanks!
