### ISSUE TITLE
United Theme missing text

### ISSUE THREAD

**Issue by mmustafa160** [pglombardo/PasswordPusher#1320]
## 🔬 How To Reproduce

1. ... 

### Environment

Where are you running/using Password Pusher?

- [ ] pwpush.com
- [ *] Docker
  - [ ] pwpush-ephemeral
  - [ ] pwpush-mysql
  - [*] pwpush-postgres
  - [ ] custom image
- [ ] Heroku
- [ ] Digital Ocean
- [ ] Microsoft Azure
- [ ] Google Cloud
- [ *] AWS
- [ ] Source Code
- [ ] Other (please specify)

If applicable, what version of Password Pusher?

### Screenshots

United Theme

![Screenshot 2023-08-04 at 9 46 05 AM](https://github.com/pglombardo/PasswordPusher/assets/134008245/cd856b29-60b3-43ec-b2cd-b7148bb6ea3d)
![Screenshot 2023-08-04 at 9 46 15 AM](https://github.com/pglombardo/PasswordPusher/assets/134008245/9b7f3a18-0e34-412c-99ed-f9a91e86cb5d)

## 📈 Expected behavior

Theme on pwpush.com

![Screenshot 2023-08-04 at 9 51 40 AM](https://github.com/pglombardo/PasswordPusher/assets/134008245/4121bc8d-5724-47c5-9304-73c3adf3ab92)

![Screenshot 2023-08-04 at 9 51 51 AM](https://github.com/pglombardo/PasswordPusher/assets/134008245/62a8a081-eaa0-4375-98e2-94c88f09dfb8)

**Comment by pglombardo** [comment]
Hi @mmustafa160 - update to the latest container tag and that should fix it.  There was an issue in an older release that caused this.

I just tried with the `release` tag and it looks ok:

<img width="631" alt="Screenshot 2023-08-04 at 17 14 55" src="https://github.com/pglombardo/PasswordPusher/assets/395132/64b3cbbf-2615-48f4-a0f5-7fd8fcb302ce">

**Comment by mmustafa160** [comment]
I just pulled the docker image again with the release tag. It's fixed. Thank you.
