### ISSUE TITLE
Kubernetes: puma parent process being killed

### ISSUE THREAD

**Issue by amirnazarizadeh** [pglombardo/PasswordPusher#1326]
Hi
I tried to deploy pwpusher to kubernetes. everything is OK:
`[9] * Listening on http://0.0.0.0:5100
[9] Use Ctrl-C to stop
[9] - Worker 0 (PID: 11) booted in 0.19s, phase: 0
[9] - Worker 1 (PID: 13) booted in 0.2s, phase: 0`
 but when I request to it, it gives me following error:
`[11] ! Detected parent died, dying
[13] ! Detected parent died, dying
containers/docker/pwpush-ephemeral/entrypoint.sh: line 16: 9 Killed bundle exec puma -C config/puma.rb -e private`

**Comment by pglombardo** [comment]
Hi @amirnazarizadeh,

When the application boots, `puma` launches a master process and then child processes to handle the HTTP requests.

Something is killing that parent process but it's not clear what...  Could you check the container for any other logs?  Inside the container there is also a `logs` directory that may have some evidence.

<img width="542" alt="Screenshot 2023-08-08 at 14 26 02" src="https://github.com/pglombardo/PasswordPusher/assets/395132/021bff2c-0f1b-4dfc-8b7a-61a46bc9de1a">

Could you also set these environment variables?  We can lower that other one to `debug` if needed too.

**Comment by amirnazarizadeh** [comment]
thank you for fast response.
I enabeld debug logs and got:
`D, [2023-08-08T12:43:00.738297 #14] DEBUG -- : source=rack-timeout id=70786ecc-087b-491c-8509-02c863dddf56 timeout=15000ms state=ready
D, [2023-08-08T12:43:00.743355 #14] DEBUG -- : source=rack-timeout id=70786ecc-087b-491c-8509-02c863dddf56 timeout=15000ms service=5ms state=active
containers/docker/pwpush-ephemeral/entrypoint.sh: line 16: 9 Killed bundle exec puma -C config/puma.rb -e private`

**Comment by amirnazarizadeh** [comment]
unfortunately problem still exists and it's not OOM kill :(

**Comment by amirnazarizadeh** [comment]
Hero of the day. that was memory issue. Thank you sir.

**Comment by amirnazarizadeh** [comment]
No idea? :(
