### ISSUE TITLE
Azure: cannot start docker container

### ISSUE THREAD

**Issue by gregoryca** [pglombardo/PasswordPusher#1338]
## 🐛 Bug Report

After creating an azure container server instance with docker compose, i cannot start pwpush

## 🔬 How To Reproduce

1. Configure linux ubuntu with docker-compose installed on it
2. run the compose file attached

### Code sample
https://cloud.apex-migrations.net/s/o9qwTBseKoE9Hm5

### Environment
Operating system - Linux (ubuntu 20.04)
Image publisher - cloud-infrastructure-services
Image offer - docker-compose-ubuntu20
VM generation - V1
VM architecture - x64

Where are you running/using Password Pusher?

- [ ] pwpush.com
- [ ] Docker
  - [ ] pwpush-ephemeral
  - [ ] pwpush-mysql
  - [ ] pwpush-postgres
  - [ ] custom image
- [ ] Heroku
- [ ] Digital Ocean
- [x] Microsoft Azure
- [ ] Google Cloud
- [ ] AWS
- [ ] Source Code
- [ ] Other (please specify)

If applicable, what version of Passwo
![pwpush - issue](https://github.com/pglombardo/PasswordPusher/assets/10562868/a2b6c30a-8b5a-49ee-8b86-0ce18969c574)
rd Pusher?

Latest version

### Screenshots

screenshot added on the end of the bug report

## 📈 Expected behavior

PWPush should start like it did when i run this at home

## 📎 Additional context
this docker compose file works on a bare metal linux ubuntu 22.04 server

**Comment by pglombardo** [comment]
This docker-compose.yml file works for me locally as well.

What is Azure doing to create that output `bundler: command not found: rake`?  That isn't part of the container boot process...

These items are already built into the container.  Any ideas?  I don't have access to Azure currently.

**Comment by gregoryca** [comment]
is there an option for me to enable more debugging ? i will try to update the docker engine to see if that helps.

**Comment by pglombardo** [comment]
[This is the container boot script](https://github.com/pglombardo/PasswordPusher/blob/master/containers/docker/pwpush-mysql/entrypoint.sh#L7) that runs `rake`.  `rake` is built and installed into the container during the build process.

Works locally - I can't imagine why it wouldn't on Azure.  I do know we have other users on Azure working ok...

> is there an option for me to enable more debugging ?

Not for that part of the container boot process...

**Comment by gregoryca** [comment]
I have found out that it had to do with the image used. I can now deploy, the only fault i'm getting on Azure Container Instance, is that PWPush cannot find the MSYQL db. Any pointers ? i was able to launch a docker-compose.yml file that works, but now it won't work when i push the same infra from terraform. One difference i saw is that via the docker-compose file, azure creates a dns container which does not happen when i launch it form terraform.

**Comment by gregoryca** [comment]
Thank you very much ! i suspected it was a DNS issue, as the NGINX container i deployed via terraform could also not find the container based on the name i gave it in terraform. I will test it, and report how it went

**Comment by gregoryca** [comment]
As suspected it was a DNS issue. When using docker-compose.yml against the Azure CLI, it will automatically deploy a DNS sidecar to manage the traffic within the ACI.

When i switched over from the CLI to Terraform. The config of the docker-compose.yml was not valid anymore due to how the inter-container communication is handled on Azure. I had to change the DB_URL to the following:
DATABASE_URL=mysql2://passwordpusher_user:passwordpusher_passwd@127.0.0.1:3306/passwordpusher_db

and it started working immediately. Thank you very much for your help and quick answers !
