### ISSUE TITLE
Not all settings applied?

### ISSUE THREAD

**Issue by OlafCIT** [pglombardo/PasswordPusher#1349]
Hi,

I have the pwpush Docker image with PostgreSQL and notice that not all environment settings are included. A few are working after I changed the variables from the quotes (from double to single).

When registering I immediately get a 500 error with the standard logo and not the custom one, as soon as I extract the confirmation link from the log file and paste it in the browser, I receive the message that the token is not correct.

Also the passphrase isn't working.

Is it also possible to use the password generator only for registered users and the retreival link for public?
(Only the /p for public).

Attached the configuration files and errors that I receive (removed sensitive info).
I'm probably doing something wrong in the configuration, but I can't find the cause.

version: '2.1'

services:
  postgres:
    image: docker.io/postgres:10
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: passwordpusher_user
      POSTGRES_PASSWORD: passwordpusher_passwd
      POSTGRES_DB: passwordpusher_db

  passwordpusher:
    image: docker.io/pglombardo/pwpush-postgres:release
    ports:
      - "5100:5100"
    depends_on:
      - postgres
    links:
      - postgres:postgres
    environment:
      TZ: "Europe/Amsterdam"
      PWP__PW__EXPIRE_AFTER_DAYS_DEFAULT: "1"
      PWP__PW__EXPIRE_AFTER_VIEWS_MIN: "1"
      PWP__PW__RETRIEVAL_STEP_DEFAULT: "true"
      PWP__ENABLE_LOGINS: "true"
      PWP__ALLOW_ANONYMOUS: "true"
      PWP__MAIL__RAISE_DELIVERY_ERRORS: "true"
      PWP__MAIL__SMTP_ADDRESS: ""
      PWP__MAIL__SMTP_PORT: "587"
      PWP__MAIL__SMTP_USER_NAME: ""
      PWP__MAIL__SMTP_PASSWORD: ""
      PWP__MAIL__SMTP_AUTHENTICATION: "plain"
      PWP__MAIL__SMTP_STARTTLS: "true"
      PWP__MAIL__SMTP_OPENSSL_VERIFY_MODE: 'none'
      PWP__MAIL__OPEN_TIMEOUT: "10"
      PWP__MAIL__READ_TIMEOUT: "10"
      PWP__HOST_DOMAIN: ""
      PWP__HOST_PROTOCOL: "https"
      PWP__MAIL__MAILER_SENDER: ''
      PWP__ENABLE_FILE_PUSHES: "false"
      PWP__ENABLE_URL_PUSHES: "false"
      PWP__BRAND__TITLE: ""
      PWP__BRAND__TAGLINE: ""
      PWP__BRAND__SHOW_FOOTER_MENU: "false"
      PWP__BRAND__LIGHT_LOGO: ""
      PWP__BRAND__DARK_LOGO: ""
      PWP__LOG_TO_STDOUT: "false"
      PWP__LOG_LEVEL: "debug"
      PWP__DEFAULT_LOCALE: 'nl'
      PWP__THEME: 'lumen'
      PWP_PRECOMPILE: 'true'
      PWPUSH_MASTER_KEY: ""
      PWP__PW__EXPIRE_AFTER_DAYS_MIN: "1"
      PWP__PW__EXPIRE_AFTER_DAYS_MAX: "7"
      PWP__PW__EXPIRE_AFTER_VIEWS_DEFAULT: "1"
      PWP__PW__EXPIRE_AFTER_VIEWS_MAX: "5"
      PWP__PW__ENABLE_DELETABLE_PUSHES: "true"
      PWP__PW__DELETABLE_PUSHES_DEFAULT: "true"
      PWP__PW__ENABLE_RETRIEVAL_STEP: "false"
      PWP__PW__ENABLE_BLUR: "true"
![image](https://github.com/pglombardo/PasswordPusher/assets/140914963/12256b4b-e1d5-4780-b524-edbaa2b8abb9)
![image](https://github.com/pglombardo/PasswordPusher/assets/140914963/05f1a982-1346-4c74-a3ed-0d8f761e6e1b)

I, [2023-08-13T00:43:37.764797 #176]  INFO -- : [ab514799-a777-4319-aaf6-6260be65b10a] method=POST path=/nl/users/confirmation format=turbo_stream controller=Users::ConfirmationsController action=create status=500 allocations=7476 duration=323.77 view=0.00 db=1.53 ip=95.xx.xxx.xx forwarded_for=95.xx.xxx.xx
F, [2023-08-13T00:43:37.770686 #176] FATAL -- : [ab514799-a777-4319-aaf6-6260be65b10a]
[ab514799-a777-4319-aaf6-6260be65b10a] TypeError (no implicit conversion of Symbol into Integer):
[ab514799-a777-4319-aaf6-6260be65b10a]
[ab514799-a777-4319-aaf6-6260be65b10a] app/controllers/application_controller.rb:14:in `custom_set_locale_from_url'
D, [2023-08-13T00:43:37.773201 #176] DEBUG -- : source=rack-timeout id=ab514799-a777-4319-aaf6-6260be65b10a timeout=15000ms service=343ms state=completed

**Comment by pglombardo** [comment]
Hi @OlafCIT some thoughts inline below

> I have the pwpush Docker image with PostgreSQL and notice that not all environment settings are included. A few are working after I changed the variables from the quotes (from double to single).

With that many environment variables, you might want to consider using a custom `settings.yml` instead.  It's easier to manage.  Documentation on this [is available here](https://github.com/pglombardo/PasswordPusher/blob/master/Configuration.md#configuring-via-a-custom-settingsyml-file).

> When registering I immediately get a 500 error with the standard logo and not the custom one, as soon as I extract the confirmation link from the log file and paste it in the browser, I receive the message that the token is not correct.

The error page has the standard logo.  This may be fixed in the future.  Feel free to file a separate feature request as a reminder but I'm aware of it in any case.

> Also the passphrase isn't working.

I need more details to diagnose this one.  Could you file a separate issue?

> Is it also possible to use the password generator only for registered users and the retreival link for public?
> (Only the /p for public).

If I understand this correctly - there is no way to make the password generator for registered users.  In a larger scope, you have `PWP__ALLOW_ANONYMOUS: "true"` which allows "not logged in" users access the front page.


Lastly, you have many environment variables set without values such as `PWP__MAIL__SMTP_ADDRESS: ""` and `PWP__MAIL__MAILER_SENDER: ''`.  This will definitely cause errors specifically with the `ConfirmationsController` that you had a screenshot of.

My advice would be to remove all of the environment variables that you don't need.  But of course, you need a valid email server configured for logins, file and URL pushes to work.

I hope this puts you in the right direction.  Let me know how it goes.

**Comment by OlafCIT** [comment]
Hi,

I removed the info from the variables, thats why it's empty.
The problems with the passphrase is solved. This was because a fault in the vhost config.

I will check the rest tomorrow.

Thanks!

**Comment by pglombardo** [comment]
Ok sounds good.  I found a problem in the passphrase redirect with URL pushes.  I'll be fixing this soon too.

**Comment by pglombardo** [comment]
Hi @OlafCIT - This issue fell through the cracks.  Do you have any updates or remaining issues?  Hope all is well!

**Comment by pglombardo** [comment]
Hi @OlafCIT - just an update:

> When registering I immediately get a 500 error with the standard logo and not the custom one, as soon as I extract the confirmation link from the log file and paste it in the browser, I receive the message that the token is not correct.

All branding on the error pages will be removed in the next release via #1920

**Comment by pglombardo** [comment]
Since I haven't heard back, I'll close out this issue but if anything remains, feel free to comment or open a new issue.  I'd be more than happy to help.
