### ISSUE TITLE
Cannot create anything in kubernetes

### ISSUE THREAD

**Issue by amirnazarizadeh** [pglombardo/PasswordPusher#1350]
I deployed the ephemeral version of pwpush. everything is OK till I want to push a password. It gives me following error:
`ActiveRecord::StatementInvalid: SQLite3::ReadOnlyException: attempt to write a readonly database`
the permissions are:
`drwxr-xr-x    3 pwpusher pwpusher        72 Aug  4 17:31 .`
`drwxr-xr-x    1 pwpusher pwpusher      4096 Aug  4 17:31 ..`
`-rw-r--r--    1 pwpusher pwpusher    126976 Aug  4 17:31 db.sqlite3`
`drwxr-xr-x    2 pwpusher pwpusher      4096 Aug  4 17:26 migrate`
`-rw-r--r--    1 pwpusher pwpusher      6136 Aug  4 17:26 schema.rb`
`-rw-r--r--    1 pwpusher pwpusher       355 Aug  4 17:26 seeds.rb`

**Comment by pglombardo** [comment]
Did you resolve this @amirnazarizadeh?  If you did, could you share what you found?  It'll help anyone else that comes across this issue.
