### ISSUE TITLE
FR: Increase Max Files Per Push Limit (currently a max of 10 files can be attached)

### ISSUE THREAD

**Issue by kayvanaarssen** [pglombardo/PasswordPusher#1357]
Saw this commit; https://github.com/pglombardo/PasswordPusher/pull/1340/commits/d1883f50fbf9147fbb3efb0c7df632207f2ef934

Does this mean that we can do more than 10 file pushes at once? Or is this based on the file size?
Updated to the latest version, and can still only do 10 files at a time. Is there a setting we need to set in the `.env`

**Comment by pglombardo** [comment]
Hi @kayvanaarssen - The limit in that commit is for pwpush.com only to avoid abuse (and limit costs).  It's a limit on the total number of "file based pushes" for a single user.

So to summarise for self-hosted:

* Max number of "file pushes" per user account: _unlimited_
* Max number of files that can be attached to a single push: _10_

Slightly confusing but hopefully I explained it well enough.

**Comment by kayvanaarssen** [comment]
Thanks! Will it be possible to increase the max files in a push via the `.env` file in a future release.
Can you change this to a Feature Request than? 
Thanks again!

**Comment by pglombardo** [comment]
Sure thing/done.  I can likely make the maximum number configurable.

**Comment by kayvanaarssen** [comment]
https://github.com/pglombardo/PasswordPusher/issues/1767
Sorry, did not know that this one was open still.
Can you make this an option to set Max. upload items in single upload.

**Comment by kayvanaarssen** [comment]
@pglombardo Any update on this? Would be very helpfull!

**Comment by pglombardo** [comment]
The reminder is good :-)

The file upload limit per push is in the javascript so I need to a bit of tricker to make it configurable via environment variable in the Docker image.  I'll try this week.

**Comment by kayvanaarssen** [comment]
@pglombardo That would be really really awesome.
We now catch us sharing files like documentation, config files, images etc. Not even that big but like 30-100 files it adds up. 
Should be not an issue for the application. But indeed if its a hard limit I get that its a bit harder to get around it.

Now we zip the things first etc. But that’s not user friendly and time consuming.

**Comment by pglombardo** [comment]
Just an update that this has been implemented in #1828.  Just a bit more testing & documentation and it'll be out in the next release.

**Comment by kayvanaarssen** [comment]
You are awesome! Please refer to the docs on what we need to put in the .env to get this to work! Thanks!!

**Comment by pglombardo** [comment]
Ok released in [v1.37.0](https://github.com/pglombardo/PasswordPusher/releases/tag/v1.37.0).  I just tested and all looks good.  The new env var is `PWP__FILES__MAX_FILE_UPLOADS`.

I'll close this out but if you have any problems let me know!  Thanks for pointing this out.

**Comment by kayvanaarssen** [comment]
I've done some testing and it has a hard time when uploading lets say just 85 small image files ranging from 100-500KB in size, server load is really low. Using a 2core/4GB RAM machine.
Enough resources available;

When you come from a fresh browser session it will be able to handle it. But if you do for example 2 back to back. It will stall at +/- 40 uploads for some reason.
Did you experience this in your testing? Maybe i'm pushing the limits of some component here :-D 

![image](https://github.com/pglombardo/PasswordPusher/assets/672841/dd278a84-32a9-4d6e-ad93-bc42f6898eab)

**Comment by pglombardo** [comment]
[This](https://edgeguides.rubyonrails.org/active_storage_overview.html#direct-uploads) is the JS library in use to handle the uploads.  We may be hitting a limit there or in the backend server with concurrent connections.  Uploads are direct and each open a new TCP socket to push the data.

I'll have to test more.  Which storage backend do you have setup?  e.g. local, S3?

**Comment by kayvanaarssen** [comment]
> [This](https://edgeguides.rubyonrails.org/active_storage_overview.html#direct-uploads) is the JS library in use to handle the uploads. We may be hitting a limit there or in the backend server with concurrent connections. Uploads are direct and each open a new TCP socket to push the data.
> 
> I'll have to test more. Which storage backend do you have setup? e.g. local, S3?

Still using Digital Ocean Spaces due to the CORS settings not working on https://www.dadup.eu/ that we normally use. 
Don't know of any limits on the Digital Ocean Side...
