### ISSUE TITLE
Bootstrap 5.3.1 breaks theme:  updated requires theme update

### ISSUE THREAD

**Issue by pglombardo** [pglombardo/PasswordPusher#1377]
## 🐛 Bug Report

The default theme breaks in dark mode when Bootstrap is updated to 5.3.1.  Last good version was 5.2.3

## 🔬 How To Reproduce

1. ...

### Environment

Where are you running/using Password Pusher?

- [ ] pwpush.com
- [ ] Docker
  - [ ] pwpush-ephemeral
  - [ ] pwpush-mysql
  - [ ] pwpush-postgres
  - [ ] custom image
- [ ] Heroku
- [ ] Digital Ocean
- [ ] Microsoft Azure
- [ ] Google Cloud
- [ ] AWS
- [ ] Source Code
- [ ] Other (please specify)

If applicable, what version of Password Pusher?

**Comment by DominikZublasing** [comment]
Hello,
I've noticed this issue too.
Is there an estimate of when this problem will be fixed?

**Comment by pglombardo** [comment]
Hi @DominikZublasing - There is no ETA unfortunately.  It's when the clouds open up between other issues, my day job and everything else :-)  But with that said, this should be a hopefully easy fix sooner than later.

For now, this shouldn't be an issue as I've locked the version down to `5.2.3` until this is fixed.

When I do have the fix out, I'll make sure to update here.

**Comment by pglombardo** [comment]
As of [v1.50.2](https://github.com/pglombardo/PasswordPusher/releases/tag/v1.50.2) I believe all the issues mentioned here are fixed.  Also the bootstrap gem (for UI styling) is fully updated now.

You can also test dark mode on the OSS version at https://oss.pwpush.com

I'll close this out but if anything remains, please let me know.  Thanks for reporting!
