### ISSUE TITLE
Files and URLs option not available

### ISSUE THREAD

**Issue by hegedussz** [pglombardo/PasswordPusher#1400]
## Checklist

- [ ] I've searched the project's [`issues`](https://github.com/pglombardo/pwpush/issues?q=is%3Aissue).
- [ ] I've searched the project's [`discussions`](https://github.com/pglombardo/PasswordPusher/discussions).

## ❓ Question

I set the `PWP__ENABLE_FILE_PUSHES: true` and `PWP__ENABLE_URL_PUSHES: true` variables, but I can't see these optinon. 

Image version: docker.io/pglombardo/pwpush-mysql:1.31.3

**Comment by pglombardo** [comment]
Hi @hegedussz - do you also have logins enabled?  Those two features depend on logins being enabled.

**Comment by hegedussz** [comment]
I forgot to set the `PWP__ENABLE_LOGINS` variable.
It works now. 

Thank you!
