### ISSUE TITLE
Slack app failing with "dispatch_failed" error

### ISSUE THREAD

**Issue by jjlu2** [pglombardo/PasswordPusher#142]
Noob here. We set up a forked pwpush instance with a docker container hosted in our kubernetes and were making POST calls successfully to it with a Slack bot to https://pwpush.[domain].com/c. This was working until a few days ago.

I tested the Slack integration with the public pwpush address (https://pwpush.com/c). This also fails. 

Has the request URL changed? Anything new to add to the PWPush-Slack docs?

**Comment by pglombardo** [comment]
Thanks for reporting @jjlu2.  Fix for this is merged.  Will test and release before Monday.

**Comment by pglombardo** [comment]
The fix by @justin-rhoades has been merged and released:  This has been deployed to [pwpush.com](https://pwpush.com/) and the [docker container images](https://hub.docker.com/u/pglombardo/) have been updated.   Thanks for pointing out this issue.
