### ISSUE TITLE
Azure WebApp - Change localization files?

### ISSUE THREAD

**Issue by Manu-H** [pglombardo/PasswordPusher#1439]
## Checklist

- [X] I've searched the project's [`issues`](https://github.com/pglombardo/pwpush/issues?q=is%3Aissue).
- [X] I've searched the project's [`discussions`](https://github.com/pglombardo/PasswordPusher/discussions).

## ❓ Question

Hello! :)
I deployed PasswordPusher to an Azure WebApp Service (issue #277).
Everything works fine. Branding, Config with environment variables and so on.
I can change the default language with the environment variables with an issue.  There is one thing i'd like to change left - some text from the localization files. I can not find the files within the Azure App Services.
Does anyone have an similar setup and achieved this?

Thanks for your input! :)

**Comment by pglombardo** [comment]
Hi @Manu-H - it's not currently possible to change many of the strings (easily).  The English strings are in the source code and their language translations are in [config/locales](https://github.com/pglombardo/PasswordPusher/tree/master/config/locales).

You could rewrite those files and overlay new versions but that wouldn't affect English language strings.

The problem is that I could make some of the strings configurable, but then they would have no other language translations.

Which strings did you want to change?

**Comment by chesterbeckett** [comment]
> ## Checklist
> * [x]  I've searched the project's [`issues`](https://github.com/pglombardo/pwpush/issues?q=is%3Aissue).
> * [x]  I've searched the project's [`discussions`](https://github.com/pglombardo/PasswordPusher/discussions).
> 
> ## ❓ Question
> Hello! :) I deployed PasswordPusher to an Azure WebApp Service (issue #277). Everything works fine. Branding, Config with environment variables and so on. I can change the default language with the environment variables with an issue. There is one thing i'd like to change left - some text from the localization files. I can not find the files within the Azure App Services. Does anyone have an similar setup and achieved this?
> 
> Thanks for your input! :)
> 
> ## 📎 Additional context

Hi Manu-H, 

I have deployed to Azure Web App too, via the screenshot methods noted in #277. Just wondered if you did anything differently as I cannot get the config changes to apply, using the environment variables (Application settings?). 

Currently trying simple stuff like PWP_DEFAULT_LOCALE and PWP__BRAND__TAGLINE variables, but they are not taking even after a web app restart.

**Comment by pglombardo** [comment]
> EDIT 2: Working now, no other reason than, just wait longer! Seems to take longer to create the containers with the precompile, but its still very hit n miss!

That's good to hear that it's working now.  Setting `PWP_PRECOMPILE` does cause all of the assets to be re-compiled for the new theme on container boot which can take 30-90 seconds (depending on the system).  I should probably add that to the documentation.

Is everything else working for you now @chesterbeckett?

**Comment by pglombardo** [comment]
Hi @Manu-H - I'll close out this issue soon if nothing remains.

I will get to moving all the strings out to independent yaml files eventually but no ETA yet.

Let me know if you need anything else.
