### ISSUE TITLE
"Copy to Clipboard" copies password and not temp link

### ISSUE THREAD

**Issue by jjlu2** [pglombardo/PasswordPusher#145]
When a user generates a link to share a password, the "copy to clipboard" buttons copy the password itself and not the temporary link.

**Comment by brunobcestari** [comment]
Actually, the copy button next to the URL is not working at all (maybe your password was already in your clipboard when you clicked)
I fixed it adding a Javascript function for this button here app/assets/javascripts/passwords.js

**Comment by pglombardo** [comment]
Fix is in progress here: https://github.com/pglombardo/PasswordPusher/pull/149

**Comment by pglombardo** [comment]
The fix for this has been deployed to [pwpush.com](https://pwpush.com/) and the [docker container images](https://hub.docker.com/u/pglombardo/) have been updated.   Thanks for reporting!
