### ISSUE TITLE
Darkmode - CSS Text Color not correct

### ISSUE THREAD

**Issue by kayvanaarssen** [pglombardo/PasswordPusher#1454]
When using darkmode in the browser Password Pusher will change its interface to Dark nice :-D 
But check;

Dark Mode: 

![image](https://github.com/pglombardo/PasswordPusher/assets/672841/b68f5976-0dc8-4176-bf9c-2a1787a9c99e)

Dark Mode all Text Selected;

![image](https://github.com/pglombardo/PasswordPusher/assets/672841/aee197fa-785f-41b6-8309-8c7cb32be8d0)

As you can see some text is not visible.
Can you please fix this in the next release?

**Comment by pglombardo** [comment]
Hi @kayvanaarssen - If I remember correctly, this was a bug in a past version.  What version are you using and did you configure any custom CSS or a custom theme?

**Comment by kayvanaarssen** [comment]
Just default, latest version. Its being updated every update by Watchtower.

Any suggestions?

**Comment by kayvanaarssen** [comment]
Hope you get better soon😉
Its okay for now. Hope it will be fixed asap.

**Comment by pglombardo** [comment]
Thanks/I'm getting better now.  I reverted the gem update in #1461 - it's a temporary bandaid until #1377 is fixed.

**Comment by kayvanaarssen** [comment]
Watchtower just updated, and now it looks like it should again. Thanks!!

**Comment by pglombardo** [comment]
Cool - I disabled dependabot updates to that gem until the bug is fixed.

**Comment by ArxWachtMa** [comment]
Hello,

Experiencing this also from pwpush:1.48 & onward. Browser theme seems to override PWP_THEME, more specificaly text colour.

**Comment by ArxWachtMa** [comment]
Hello @pglombardo ,

Thank you for the swift response. I'll open a new issue throughout the day.

Have a great monday!

**Comment by pglombardo** [comment]
As of v1.50.2 I believe all the issues mentioned here are fixed.  Also the bootstrap gem (for UI styling) is fully updated now.

You can also test dark mode on the OSS version at https://oss.pwpush.com

I'll close this out but if anything remains, please let me know.  Thanks for reporting!
