### ISSUE TITLE
DOCKER: Build Docker images via github action is broken

### ISSUE THREAD

**Issue by sirux88** [pglombardo/PasswordPusher#1487]
## 🐛 Bug Report
The alpine based docker images require `gem 'sqlite3', force_ruby_platform: true` within gemfile to get built.
This was changed to `gem 'sqlite3'` in #1483 
I'm investigating how to solve this.

### Environment

Where are you running/using Password Pusher?

- [ ] pwpush.com
- [x] Docker
  - [x] pwpush-ephemeral
  - [ ] pwpush-mysql
  - [ ] pwpush-postgres
  - [ ] custom image
- [ ] Heroku
- [ ] Digital Ocean
- [ ] Microsoft Azure
- [ ] Google Cloud
- [ ] AWS
- [ ] Source Code
- [ ] Other (please specify)

If applicable, what version of Password Pusher?

**Comment by pglombardo** [comment]
Hi @sirux88 - yeah I just removed to get the github build to pass.  I was investigating on the failure but it was a rabbit hole.  Let me know if you have any ideas.

BTW I'm planning to loop back to your other PRs this weekend.  I've been a bit overloaded lately.

**Comment by sirux88** [comment]
You removed it because testing failed? (I think you meant testing with "github build to pass")
This is no offense I just want to make it sure

And for the other PRs:
Take your time. There's no pressure on it

**Comment by sirux88** [comment]
Having `gem 'sqlite3', force_ruby_platform: true ` is a requirement to have docker images with alpine base images(see #815) .
So the removal of ` force_ruby_platform: true ` in #1483 needs to be reverted.

My testings with `gem 'sqlite3', force_ruby_platform: true ` in `Gemfile` resulted in:
- **Ruby 3.1.x**: All fine until sqlite3 gem version 1.6.5. Above this version native building building fails
- **Ruby 3.2.x**: Building sqlite native gem version 1.6.6 is fine. Below aswell

So it seems this problem is tied to ruby 3.1.4 and sqlite version beginning with 1.6.6

I see two possible options:
1) Pin sqlite version to 1.6.5 for the moment, throw an issue on [sqlite3-ruby](https://github.com/sparklemotion/sqlite3-ruby) and hope it gets fixed for ruby 3.1.x
2) Update min. ruby version to 3.2.x. Since testing against ruby 3.2 is already done and the docker base image is of this version it shouldn't be this big problem

**Comment by pglombardo** [comment]
Great analysis @sirux88.  I'm fine with either option but dropping Ruby 3.1 support sounds easier.  Shall I create a PR to restore `force_ruby_platform` and remove Ruby 3.1 from the test suite?

**Comment by sirux88** [comment]
I would go for dropping ruby 3.1 support aswell.
Since you're the ruby pro feel free do so. 
If you mention me I'll throw an eye on it when it's available

**Comment by sirux88** [comment]
I throw an issue on the sqlite3 devs https://github.com/sparklemotion/sqlite3-ruby/issues/411

@pglombardo:
We could pin psych version to something <5.0 if you prefer to fix this issue.
But still I would go for dropping ruby v3.1 support

**Comment by pglombardo** [comment]
Ok #1489 built successfully & tests passed/merged.  That should do it - Let's see on the next nightly container builds...

**Comment by sirux88** [comment]
Seems fine to me aswell

**Comment by pglombardo** [comment]
Closing
