### ISSUE TITLE
Cannot install pwpusher with docker-compose from version 1.30.0 to latest version

### ISSUE THREAD

**Issue by nicoden81** [pglombardo/PasswordPusher#1498]
## 🐛 Bug Report

Hi,
I can't upgrade pwpush from version 1.29.3 to 1.30.0 (and to the latest version).
Pwpusher throws errors when starting the pwpush-mysql container (see attached file):
```
Password Pusher: migrating database to latest...
rake aborted!
TypeError: no implicit conversion of nil into String
```
I have attached docker-compose file and .env file.
I have tried with other version of mariadb (11.0) but same problem.
I have tried to perform a new  install with new volumes and new names, but same errors.
(
## 🔬 How To Reproduce

1. stop pwpusher: docker-compose down
2. In docker-compose directory, set pwpusher version in .env files
3. Start docker-compose: docker-compose up -d

### Environment

Where are you running/using Password Pusher?

- [ ] pwpush.com
- [x] Docker
  - [ ] pwpush-ephemeral
  - [x] pwpush-mysql
  - [ ] pwpush-postgres
  - [ ] custom image
- [ ] Heroku
- [ ] Digital Ocean
- [ ] Microsoft Azure
- [ ] Google Cloud
- [ ] AWS
- [ ] Source Code
- [ ] Other (please specify)

If applicable, what version of Password Pusher?

## 📎 Additional context

[pwpush_error.txt](https://github.com/pglombardo/PasswordPusher/files/12804787/pwpush_error.txt)
[docker-compose.zip](https://github.com/pglombardo/PasswordPusher/files/12804964/docker-compose.zip)

**Comment by pglombardo** [comment]
Hi @nicoden81 - The stack trace you posted suggest there is likely a problem in the settings.yml file you configured [specifically with this settings](https://github.com/pglombardo/PasswordPusher/blob/master/config/settings.yml#L91).

Could you try adding that line to your settings.yaml to see what affect it has?

**Comment by nicoden81** [comment]
Hi,

Thanks you very much. That was the issue. It's now working. I apologize for
my mistake.

Regards.

**Comment by pglombardo** [comment]
That's great to hear that it's resolved.  Let me know if you have any other issues!
