### ISSUE TITLE
Avoid Chrome translating pwpush page

### ISSUE THREAD

**Issue by alexandre-zia-ifood** [pglombardo/PasswordPusher#154]
When Google Chrome Browser automatically translates pwpush page to whatever the user language is, if the secret being pushed has special characters, chrome translation adds spaces around these characters and user get a wrong secret.

So it would be great if pwpush could disable Chrome browser auto translation.

This can be achieved by adding a < head > < meta > tag, that would prevent translation of the entire page:
`<meta content="notranslate" name="google">`

or perhaps a notranslate class only in the secret element:
`<span class="user notranslate">His Name Here</span>`

We are testing here adding the meta and solved the problem, 
added :
`%meta{ :name => "google", :content => "notranslate" }`
into application.html.haml

**Comment by pglombardo** [comment]
Thanks for reporting this (and including the fix).  I'll add this in and post back here soon once it's out.

**Comment by pglombardo** [comment]
I've added the tags and it seems to be working in my local tests.  Once I deploy the fix to pwpush.com during a low traffic period I'll update here.

**Comment by pglombardo** [comment]
The fix is live on pwpush.com.  New docker container images are pending.

**Comment by pglombardo** [comment]
New containers published  https://hub.docker.com/u/pglombardo
