### ISSUE TITLE
firewall problem with docker pwpush and nginx reverse proxy

### ISSUE THREAD

**Issue by Threepwood77** [pglombardo/PasswordPusher#1540]
Hello,
thanks for the pwpush tool, it's really great!
I was able to deploy the docker without any problems, it works perfectly.
I've set up a reverse proxy with Nginx, which also works well.
However, as soon as I want to set up IPTABLE rules to prohibit all traffic except for Nginx and Docker, it doesn't work.
do i have to launch the docker container with special settings ?
or do I need specific IPTABLE rules ?
I use the default port for docker container access (5100)
and I use the standard ports for Nginx access (80 and 443).
thanks for your help.

**Comment by pglombardo** [comment]
Hi @Threepwood77 - sincere apologies that I can't be much help on setting up rules for iptables...

You might have better luck asking in a Linux forum - the specifics of Password Password don't really matter.  You have a front end proxy with ports 80/443 and a backend application serving from port 5100.  This should be a common question in the iptables communities I would think.


As a last resort, this is what Chat GPT says:

To restrict traffic to only allow access to your Docker container and Nginx while using iptables, you need to create appropriate rules to permit incoming traffic to these specific services. Here are the steps you can follow:

1. Allow Nginx traffic:

   If Nginx is listening on ports 80 and 443 for HTTP and HTTPS, respectively, you can add rules to allow traffic on those ports.

   ```bash
   iptables -A INPUT -p tcp --dport 80 -j ACCEPT
   iptables -A INPUT -p tcp --dport 443 -j ACCEPT
   ```

   These rules will allow incoming HTTP and HTTPS traffic to your Nginx server.

2. Allow Docker traffic:

   You mentioned that your Docker container is using port 5100. To allow traffic to the Docker container, you can add a rule like this:

   ```bash
   iptables -A INPUT -p tcp --dport 5100 -j ACCEPT
   ```

   This rule allows incoming traffic on port 5100, which is the default port for your Docker container.

3. Drop all other incoming traffic:

   After allowing traffic for Nginx and Docker, you should drop all other incoming traffic to restrict access to only these services.

   ```bash
   iptables -A INPUT -j DROP
   ```

   This rule will drop all incoming traffic that doesn't match the previous rules.

Make sure to save your iptables rules so they persist across reboots. The method for saving rules may vary depending on your Linux distribution. On many systems, you can use the `iptables-save` command or save the rules in a file and load them on boot.

Remember to test these rules carefully to avoid accidentally locking yourself out of the server. You might want to test them on a non-production server or a testing environment first.

Also, if your Docker container is running multiple services, you may need to specify more rules to allow traffic to specific ports for those services. Adjust the rules accordingly to match your specific setup.

**Comment by pglombardo** [comment]
Hi @Threepwood77 - did you ever make any progress on this?

**Comment by Threepwood77** [comment]
Hello, 
I couldn't find a solution with just one instance, so I decided on two.
one which acts as a nginx frontend and which refers (via a private network) to the instance with docker.
It works well like that :)
