### ISSUE TITLE
Support for IAM and Workload Identity on GCS

### ISSUE THREAD

**Issue by petskratt** [pglombardo/PasswordPusher#1567]
## 🚀 Feature Request

Implement 2 additional [configuration parameters supported by ActiveStorage](https://edgeguides.rubyonrails.org/active_storage_overview.html#google-cloud-storage-service) for using IAM and workload identity. Apparently just `iam` and (optionally for testing) `gsa_email` are needed:

```
google:
  service: GCS
  ...
  iam: true
  gsa_email: "foobar@baz.iam.gserviceaccount.com"
```

## 🔈 Motivation

Workload identity is recommended way for GKE applications to authenticate to and consume other Google Cloud services: "[Introducing Workload Identity: Better authentication for your GKE applications](https://cloud.google.com/blog/products/containers-kubernetes/introducing-workload-identity-better-authentication-for-your-gke-applications)"

## 🛰 Alternatives

Current GCS configuration is based on supplying credentials, that are prone to committing to GIT in plaintext and make credential rotation a notable pain. Considering the files are stored without encryption bucket credentials have notable value.

**Comment by pglombardo** [comment]
Good point!  I'll try to add this soon.  Thanks @petskratt

**Comment by petskratt** [comment]
Tested and works as intended, tx @pglombardo!

For future implementers:
- be aware, that files are stored without encryption & ensure access to bucket in GCP is properly limited
- permissions required are not documented on ActiveStorage, so including relevant parts of my Terraform manifest:

```
resource "google_service_account" "passwordpusher-sa" {
  project      = var.project
  account_id   = "passwordpusher-storage-sa"
  display_name = "Passwordpusher bucket Service Account"
  description  = "Ephemeral file storage for Passwordpusher"
}

resource "google_service_account_iam_binding" "passwordpusher-sa-iam-binding" {
  service_account_id = google_service_account.passwordpusher-sa.name
  role               = "roles/iam.workloadIdentityUser"
  members            = [ "serviceAccount:${var.project}.svc.id.goog[passwordpusher-namespace/passwordpusher-sa]" ]
}

resource "google_storage_bucket" "passwordpusher-bucket" {
  name                        = "passwordpusher-storage"
  project                     = var.project
  location                    = var.data_bucket_location
  storage_class               = "STANDARD"
  uniform_bucket_level_access = true
  force_destroy               = true
 
  cors {
    origin          = ["https://example.com"]
    method          = ["PUT"]
    response_header = ["Content-Type", "Content-MD5", "Content-Disposition"]
    max_age_seconds = 3600
  }
}

resource "google_storage_bucket_iam_member" "passwordpusher-bucket-role" {
  bucket = google_storage_bucket.passwordpusher-bucket.name
  role   = "roles/storage.objectAdmin"
  member = "serviceAccount:${google_service_account.passwordpusher-sa.email}"
}

resource "google_project_iam_member" "passwordpusher-iam-role" {
  project = var.project
  role    = "roles/iam.serviceAccountTokenCreator"
  member  = "serviceAccount:${google_service_account.passwordpusher-sa.email}"
}
```
