### ISSUE TITLE
sing up error 500

### ISSUE THREAD

**Issue by DJKenzoDE** [pglombardo/PasswordPusher#1576]
i have the singup process endet everytime in error 500
i use it with docker and docker compose
i have the latest version and have downbloaded the compose file i think couple of hours

here is the log with log-level: debug

password-pwpush-1  | D, [2023-10-26T16:46:48.477328 #10] DEBUG -- :    (0.2ms)  SELECT GET_LOCK('1111536674037510630', 0)
password-pwpush-1  | D, [2023-10-26T16:46:48.485284 #10] DEBUG -- :   ActiveRecord::SchemaMigration Pluck (0.7ms)  SELECT `schema_migrations`.`version` FROM `schema_migrations` ORDER BY `schema_migrations`.`version` ASC
password-pwpush-1  | D, [2023-10-26T16:46:48.489872 #10] DEBUG -- :   ActiveRecord::InternalMetadata Load (0.7ms)  SELECT `ar_internal_metadata`.* FROM `ar_internal_metadata` WHERE `ar_internal_metadata`.`key` = 'environment' LIMIT 1
password-pwpush-1  | D, [2023-10-26T16:46:48.510861 #10] DEBUG -- :    (0.8ms)  SELECT RELEASE_LOCK('1111536674037510630')
password-pwpush-1  | Password Pusher: starting puma webserver...
password-pwpush-1  | [12] Puma starting in cluster mode...
password-pwpush-1  | [12] * Puma version: 6.4.0 (ruby 3.2.2-p53) ("The Eagle of Durango")
password-pwpush-1  | [12] *  Min threads: 5
password-pwpush-1  | [12] *  Max threads: 5
password-pwpush-1  | [12] *  Environment: production
password-pwpush-1  | [12] *   Master PID: 12
password-pwpush-1  | [12] *      Workers: 2
password-pwpush-1  | [12] *     Restarts: (✔) hot (✖) phased
password-pwpush-1  | [12] * Preloading application
password-pwpush-1  | Password Pusher Version: 1.32.2
password-pwpush-1  | [12] * Listening on http://0.0.0.0:5100
password-pwpush-1  | [12] Use Ctrl-C to stop
password-pwpush-1  | [12] - Worker 0 (PID: 14) booted in 0.02s, phase: 0
password-pwpush-1  | [12] - Worker 1 (PID: 16) booted in 0.0s, phase: 0
password-pwpush-1  | D, [2023-10-26T16:46:53.411760 #16] DEBUG -- : source=rack-timeout id=d4e8ddf2-d191-4a8b-a8e4-043bec9c47f2 timeout=15000ms state=ready
password-pwpush-1  | D, [2023-10-26T16:46:53.453713 #16] DEBUG -- : source=rack-timeout id=d4e8ddf2-d191-4a8b-a8e4-043bec9c47f2 timeout=15000ms service=42ms state=active
password-pwpush-1  | I, [2023-10-26T16:46:53.567899 #16]  INFO -- : [d4e8ddf2-d191-4a8b-a8e4-043bec9c47f2] method=GET path=/en/users/sign_up format=html controller=Users::RegistrationsController action=new status=200 allocations=40799 duration=112.08 view=47.26 db=3.47 ip=2.205.1.98
password-pwpush-1  | D, [2023-10-26T16:46:53.569242 #16] DEBUG -- : source=rack-timeout id=d4e8ddf2-d191-4a8b-a8e4-043bec9c47f2 timeout=15000ms service=158ms state=completed
password-pwpush-1  | D, [2023-10-26T16:47:10.335487 #16] DEBUG -- : source=rack-timeout id=37771a69-0696-4986-a816-69ea86a1ba31 timeout=15000ms state=ready
password-pwpush-1  | D, [2023-10-26T16:47:10.349578 #16] DEBUG -- : source=rack-timeout id=37771a69-0696-4986-a816-69ea86a1ba31 timeout=15000ms service=14ms state=active
password-pwpush-1  | D, [2023-10-26T16:47:10.814263 #16] DEBUG -- : [37771a69-0696-4986-a816-69ea86a1ba31]   TRANSACTION (0.2ms)  BEGIN
password-pwpush-1  | D, [2023-10-26T16:47:10.815628 #16] DEBUG -- : [37771a69-0696-4986-a816-69ea86a1ba31]   User Exists? (1.2ms)  SELECT 1 AS one FROM `users` WHERE `users`.`email` = BINARY 'admin+test6@djkenzo.eu' LIMIT 1
password-pwpush-1  | D, [2023-10-26T16:47:10.828340 #16] DEBUG -- : [37771a69-0696-4986-a816-69ea86a1ba31]   User Count (11.5ms)  SELECT COUNT(*) FROM `users` WHERE `users`.`authentication_token` = 'xvyAv8KsawjoKKtzWzP2'
password-pwpush-1  | D, [2023-10-26T16:47:10.838753 #16] DEBUG -- : [37771a69-0696-4986-a816-69ea86a1ba31]   User Create (3.2ms)  INSERT INTO `users` (`email`, `encrypted_password`, `reset_password_token`, `reset_password_sent_at`, `remember_created_at`, `sign_in_count`, `current_sign_in_at`, `last_sign_in_at`, `current_sign_in_ip`, `last_sign_in_ip`, `created_at`, `updated_at`, `admin`, `failed_attempts`, `unlock_token`, `locked_at`, `confirmation_token`, `confirmed_at`, `confirmation_sent_at`, `unconfirmed_email`, `authentication_token`) VALUES ('admin+test6@djkenzo.eu', '$2a$12$Z8.zyDPuDtq4Dhmee3a6Je.TubF5D0rmSAwYGgcjsH0gmHIe7DASe', NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, '2023-10-26 16:47:10', '2023-10-26 16:47:10', FALSE, 0, NULL, NULL, 'WNA2BnsA7u6x81J7L2F8', NULL, '2023-10-26 16:47:10', NULL, 'xvyAv8KsawjoKKtzWzP2')
password-pwpush-1  | D, [2023-10-26T16:47:10.844924 #16] DEBUG -- : [37771a69-0696-4986-a816-69ea86a1ba31]   TRANSACTION (5.6ms)  COMMIT
password-pwpush-1  | D, [2023-10-26T16:47:10.853558 #16] DEBUG -- : [37771a69-0696-4986-a816-69ea86a1ba31] Devise::Mailer#confirmation_instructions: processed outbound mail in 7.4ms
password-pwpush-1  | D, [2023-10-26T16:47:11.335926 #16] DEBUG -- : source=rack-timeout id=37771a69-0696-4986-a816-69ea86a1ba31 timeout=15000ms service=1000ms state=active
password-pwpush-1  | I, [2023-10-26T16:47:12.257926 #16]  INFO -- : [37771a69-0696-4986-a816-69ea86a1ba31] Delivered mail 653a980ed09d6_103fe80125f1@054e136b7f48.mail (1404.2ms)
password-pwpush-1  | D, [2023-10-26T16:47:12.258003 #16] DEBUG -- : [37771a69-0696-4986-a816-69ea86a1ba31] Date: Thu, 26 Oct 2023 16:47:10 +0000
password-pwpush-1  | To: admin+test6@djkenzo.eu
password-pwpush-1  | Message-ID: <653a980ed09d6_103fe80125f1@054e136b7f48.mail>
password-pwpush-1  | Subject: Confirmation instructions
password-pwpush-1  | Mime-Version: 1.0
password-pwpush-1  | Content-Type: text/html;
password-pwpush-1  |  charset=UTF-8
password-pwpush-1  | Content-Transfer-Encoding: 7bit
password-pwpush-1  |
password-pwpush-1  | <!DOCTYPE html>
password-pwpush-1  | <html lang="en">
password-pwpush-1  | <head>
password-pwpush-1  |   <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
password-pwpush-1  |
password-pwpush-1  |   <title>Password Pusher</title>
password-pwpush-1  |
password-pwpush-1  |   <meta content="Password Pusher is an application to securely send passwords over the web. Links to passwords expire after a certain number of views and/or time has passed." name='description'>
password-pwpush-1  |   <meta content='width=device-width, initial-scale=1' name='viewport'>
password-pwpush-1  |
password-pwpush-1  |   <link rel="stylesheet" href="/assets/application-3a8156f988f0d24564b141455443c520f8d76261b22b9070b234f21dfda1f65f.css" data-turbo-track="reload" />
password-pwpush-1  |   <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css"/>
password-pwpush-1  |   <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/lipis/flag-icons@6.6.6/css/flag-icons.min.css"/>
password-pwpush-1  |   <script src="/assets/application-1dda1fb9c8c7deda1b211cbd1c3f23efd737772b315add0dfeee0b8e788842d3.js" data-turbo-track="reload" defer="defer"></script>
password-pwpush-1  | </head>
password-pwpush-1  |
password-pwpush-1  | <body class="d-flex flex-column min-vh-100">
password-pwpush-1  |
password-pwpush-1  | <div class="container">
password-pwpush-1  |
password-pwpush-1  |
password-pwpush-1  |
password-pwpush-1  | <h1>Confirm your new account</h1>
password-pwpush-1  | <p>Your account has been created but you must confirm that you own this email address.</p>
password-pwpush-1  |
password-pwpush-1  | <p>
password-pwpush-1  | You can confirm your account email by
password-pwpush-1  | <a href="https://npm.key-no.de/en/users/confirmation?confirmation_token=WNA2BnsA7u6x81J7L2F8">by clicking this link</a>
password-pwpush-1  | or by copying and pasting the following URL into your browser:
password-pwpush-1  | </p>
password-pwpush-1  |
password-pwpush-1  | <pre class="chroma">
password-pwpush-1  | https://npm.key-no.de/en/users/confirmation?confirmation_token=WNA2BnsA7u6x81J7L2F8
password-pwpush-1  | </pre>
password-pwpush-1  |
password-pwpush-1  | <p>If you didn&#39;t create an account, no action is required.</p>
password-pwpush-1  |
password-pwpush-1  |
password-pwpush-1  | <p>
password-pwpush-1  | --
password-pwpush-1  | <br/>
password-pwpush-1  | <a href="https://npm.key-no.de/en">Password Pusher</a>
password-pwpush-1  | <br/>
password-pwpush-1  | <span class="fs-6 text-muted">Go Ahead.  Email Another Password.</span>
password-pwpush-1  |
password-pwpush-1  |
password-pwpush-1  |
password-pwpush-1  |
password-pwpush-1  |
password-pwpush-1  |
password-pwpush-1  |
password-pwpush-1  | </div>
password-pwpush-1  |
password-pwpush-1  | </body>
password-pwpush-1  | </html>
password-pwpush-1  |
password-pwpush-1  | I, [2023-10-26T16:47:12.258852 #16]  INFO -- : [37771a69-0696-4986-a816-69ea86a1ba31] method=POST path=/en/users format=turbo_stream controller=Users::RegistrationsController action=create status=500 allocations=10626 duration=1917.18 view=0.00 db=21.78 ip=2.205.1.98
password-pwpush-1  | F, [2023-10-26T16:47:12.259866 #16] FATAL -- : [37771a69-0696-4986-a816-69ea86a1ba31]
password-pwpush-1  | [37771a69-0696-4986-a816-69ea86a1ba31] Net::SMTPAuthenticationError (530 5.7.0 Must issue a STARTTLS command first
password-pwpush-1  | ):
password-pwpush-1  | [37771a69-0696-4986-a816-69ea86a1ba31]
password-pwpush-1  | [37771a69-0696-4986-a816-69ea86a1ba31] app/controllers/application_controller.rb:14:in `custom_set_locale_from_url'
password-pwpush-1  | D, [2023-10-26T16:47:12.260875 #16] DEBUG -- : source=rack-timeout id=37771a69-0696-4986-a816-69ea86a1ba31 timeout=15000ms service=1925ms state=completed

**Comment by DJKenzoDE** [comment]
i have tried different solutions i thiunk and have aktivated starttls and have deactived but the error it always the same

password-pwpush-1  | F, [2023-10-26T17:00:02.988035 #14] FATAL -- : [964c283e-532f-430c-bac7-ffba679ec0f0]
password-pwpush-1  | [964c283e-532f-430c-bac7-ffba679ec0f0] Net::SMTPAuthenticationError (530 5.7.0 Must issue a STARTTLS command first
password-pwpush-1  | ):
password-pwpush-1  | [964c283e-532f-430c-bac7-ffba679ec0f0]
password-pwpush-1  | [964c283e-532f-430c-bac7-ffba679ec0f0] app/controllers/application_controller.rb:14:in `custom_set_locale_from_url'

**Comment by pglombardo** [comment]
HI @DJKenzoDE - I hope that the error is resolved.  If not, let me know - I'd be happy to help.
