### ISSUE TITLE
"Preview" From chat client count as a view

### ISSUE THREAD

**Issue by antoineVerlant** [pglombardo/PasswordPusher#159]
Hello,

We just setuped Password Pusher in Kubernetes at my company. (ephemeral)

It seems to work like a charm, but we just meet an issue : When sharing password link over what's app / slack / workplace/
The client of the chat fetch a preview of the page, which count as a view. We think our browser may "pre-fetch" the page too.
For example, my college created a link with 5 view, click the link, it say : 4 view left. Send it to me bye chat, and directly the view left drop to 0.

I understand this is due to chat bad practice but still we are looking for a solution to avoid those case.

Is there a way to easily add a step to reveal the password and decrement the number a view left.

Best Regards?

**Comment by pglombardo** [comment]
Hi @antoineVerlant - yes I've seen a few reports of this happening also with firewall and email scanners - intermediaries that eat up a view.

One proposed solution is to add a multi-step retrieval workflow but it is non-trivial to implement and I lack the time currently.  For now, the easiest fix is add an extra view or disable chat preview for certain URL patterns.

A request for such a workflow is filed at https://github.com/pglombardo/PasswordPusher/issues/123

**Comment by pglombardo** [comment]
Hi @antoineVerlant - I added a new preliminary click step this week:
https://twitter.com/pwpush/status/1427336252362313730

The docker images [have been updated](https://hub.docker.com/repositories).  The feature is on tags `latest` and `1.7.0`.

Thanks for making the request.  Let me know if you have any issues.

**Comment by antoineVerlant** [comment]
Fabulous work, thanks.
I will deploy the update asap.
So you know we officially start using Password Pusher for our internal process, so big thanks to you !

**Comment by pglombardo** [comment]
> So you know we officially start using Password Pusher for our internal process, so big thanks to you !

That's great to hear - my pleasure.
