### ISSUE TITLE
Toggle is reversed for "Delete password before expiration"

### ISSUE THREAD

**Issue by essdeeay** [pglombardo/PasswordPusher#160]
With the checkbox "Allow viewers to optionally delete password before expiration", the toggle is reversed, so if the box IS ticked, users cannot optionally delete before expiry, and if the box is NOT ticked, users CAN optionally delete.

**Comment by pglombardo** [comment]
Thanks for reporting.  I'll fix, add tests for this going forward and post back here once the fix is out and new containers are published.

**Comment by pglombardo** [comment]
Fix is merged; pending deploy

**Comment by pglombardo** [comment]
Github master branch, pwpush.com and Docker containers all updated with the fix.  Thanks again!

https://hub.docker.com/u/pglombardo
