### ISSUE TITLE
Database hostnames with underscores are not supported

### ISSUE THREAD

**Issue by David-COUDRAY** [pglombardo/PasswordPusher#1602]
## 🐛 Bug Report

DataBase server name (hostname) with underscore refused into DATABASE_URI.

Error message with Postgres : 
`URI::InvalidURIError: the scheme postgres does not accept registry part: user:pass@dbhost (or bad hostname?)`

Error message with MySQL/MariaDB : 
`URI::InvalidURIError: the scheme mysql2 does not accept registry part: user:pass@dbhost (or bad hostname?)`

I use Docker Swarm for HA and fail-over.
By default, docker swarm (like docker compose) assigns the hostname on docker container with the stack name and service name, like this: _stack-name_service-name_

On Ruby, hostname with underscore is rejected.
See this answer: https://stackoverflow.com/a/64344976/18188311 
RFC3986_Parser Ruby class: https://github.com/ruby/ruby/blob/master/lib/uri/rfc3986_parser.rb#L5 

### Environment

_Where are you running/using Password Pusher?_

- [ x ] Docker Image
  - [ x ] pwpush-mysql
  - [ x ] pwpush-postgres

_If applicable, what version of Password Pusher?_  Latest

## 📈 Expected behavior

I spent over 4 hours trying to figure out why it wasn't working.
I think it would be nice to **add a note on the Github redme**, as well as in the docker-compose file.

**Comment by pglombardo** [comment]
Wow that's an unfortunate bug.  Thanks for identifying this @David-COUDRAY.  I'll add a note to the README as suggested to hopefully save others from the headache.

**Comment by pglombardo** [comment]
I created the [Guide to DATABASE_URL](https://github.com/pglombardo/PasswordPusher/wiki/Guide-to-DATABASE_URL) with notes on this issue and underscores.  It's linked in the README and I'll start linking it around more as time goes on.

**Comment by David-COUDRAY** [comment]
Thank you for this @pglombardo ;-)

**Comment by pglombardo** [comment]
Hi @David-COUDRAY - this was a very helpful report.  Since this is now well documented in the project I'll close the issue out.  Thanks for reporting!
