### ISSUE TITLE
Is there rate limiting which can lead to DoS?

### ISSUE THREAD

**Issue by AmbitiousFrog** [pglombardo/PasswordPusher#1603]
## 🐛 Bug Report

Hi team!
I noticed that there is no rate limiting option for creating new secrets. If the character limit is big enough (default is enough) some malicious attacker can automate the creation of big secrets which can overwhelm the disk space on the server. 
I was able to generate 50GB of secrets in just 1 minute with 10RPS.

## 🔬 How To Reproduce

1. Create the request for pushing a secret with the maximum length
2. Intercept the request with some tool (I used Burp Suite) or you can use python requests.
3. Make a lot of requests to push a secret.
4. Notice the disk space exhaustion

### Environment

Where are you running/using Password Pusher?

- [ ] pwpush.com
- [ ] Docker Image
  - [x] pwpush
  - [ ] pwpush-ephemeral
  - [ ] pwpush-mysql
  - [ ] pwpush-postgres
  - [ ] custom image
- [ ] Heroku
- [ ] Digital Ocean
- [ ] Microsoft Azure
- [ ] Google Cloud
- [ ] AWS
- [ ] Source Code
- [ ] Other (please specify)

## 📈 Expected behavior

A rate limit policy should be implemented to prevent this behaviour. The best way to implement it is setuping a Captcha.

**Comment by pglombardo** [comment]
Hi @AmbitiousFrog - thanks for posting this.

Password Pusher [comes with throttling built in](https://github.com/pglombardo/PasswordPusher/blob/master/Configuration.md#throttling).  It's configurable but the defaults are listed in that documentation.

> I was able to generate 50GB of secrets in just 1 minute with 10RPS.

Two points on this:

1. The max push text size is 1MB.  10RPS X 60 (seconds) == 600MB.  Are you sure your numbers are right?
2. Even still, 1MB might be too large.  We should make that length configurable with a default of 512K possibly.

**Comment by pglombardo** [comment]
Hi @AmbitiousFrog - have you had a chance to look at this?

**Comment by pglombardo** [comment]
Hi @AmbitiousFrog - I'll close this out but if you have any further questions or issues let me know!

Best,
Peter
