### ISSUE TITLE
Lack of password[expire_after_days] parameter validation on the server side

### ISSUE THREAD

**Issue by AmbitiousFrog** [pglombardo/PasswordPusher#1604]
## 🐛 Bug Report

The following POST request body fields are not validated on the server side:

password[expire_after_days].
password[expire_after_views]

These parameters are validated only on the client-side. It can be manipulated in the request body itself to bypass the validation. 
This is not an issue by itself, but in combination with https://github.com/pglombardo/PasswordPusher/issues/1603 issue it can lead to DoS

### Environment

Where are you running/using Password Pusher?

- [ ] pwpush.com
- [x] Docker Image
  - [ ] pwpush
  - [ ] pwpush-ephemeral
  - [ ] pwpush-mysql
  - [ ] pwpush-postgres
  - [ ] custom image
- [ ] Heroku
- [ ] Digital Ocean
- [ ] Microsoft Azure
- [ ] Google Cloud
- [ ] AWS
- [ ] Source Code
- [ ] Other (please specify)

## 📈 Expected behavior

The password[expire_after_days].
password[expire_after_views] parameters are validated on the server side.

**Comment by pglombardo** [comment]
You may have missed it but these parameters are [validated by the framework](https://github.com/pglombardo/PasswordPusher/blob/master/app/controllers/passwords_controller.rb#L516-L517) and [then the model](https://github.com/pglombardo/PasswordPusher/blob/master/app/models/password.rb#L85-L94).

Thanks for keeping an eye out. This should be re-evaluated periodically but thus far, I haven't seen any issues in this area.

Additionally, we've had multiple penetration test runs against the code which also didn't reveal anything in this area.

I'll close out this issue but if you have any other insights/concerns, please let me know.
