### ISSUE TITLE
warning: Rack::File is deprecated and will be removed in Rack 3.1

### ISSUE THREAD

**Issue by jplitza** [pglombardo/PasswordPusher#1620]
## 🐛 Bug Report

Since updating to v1.33.0, calling `rake`  produces the following output on stderr:
```
vendor/bundle/ruby/3.2.0/gems/rack-3.0.8/lib/rack/file.rb:5: warning: Rack::File is deprecated and will be removed in Rack 3.1
```

## 🔬 How To Reproduce

1. Use v1.33.0
2. Run `rake daily_expiration` or `rake delete_expired_and_anonymous`

### Environment

Where are you running/using Password Pusher?

- [ ] pwpush.com
- [ ] Docker Image
  - [ ] pwpush
  - [ ] pwpush-ephemeral
  - [ ] pwpush-mysql
  - [ ] pwpush-postgres
  - [ ] custom image
- [ ] Heroku
- [ ] Digital Ocean
- [ ] Microsoft Azure
- [ ] Google Cloud
- [ ] AWS
- [x] Source Code
- [ ] Other (please specify)

If applicable, what version of Password Pusher?

v1.33.0

## 📈 Expected behavior

No output on stderr.

**Comment by pglombardo** [comment]
Hi @jplitza - thanks!  I'll dig into this soon.

**Comment by pglombardo** [comment]
Hi @jplitza - this seems to have been fixed with one of the updates.  I'll close this out but if I missed something, let me know and we'll re-open.

Thanks for reporting!
