### ISSUE TITLE
Postgres database version supported by passwordpusher?

### ISSUE THREAD

**Issue by mathsyx69** [pglombardo/PasswordPusher#1622]
## Checklist

- [x] I've searched the project's [`issues`](https://github.com/pglombardo/pwpush/issues?q=is%3Aissue).
- [x] I've searched the project's [`discussions`](https://github.com/pglombardo/PasswordPusher/discussions).

## ❓ Question

I host passwordpusher with podman using a podman-compose.yml file, it's work well. 
I used the docker-compose file provided in the source code as an example. 
But the postgres version tag is "10" and this version is no longer supported. 

Could I use the last version of postgres (16) instead of 10 with password pusher ?

**Comment by pglombardo** [comment]
I'll update that version in the docker compose file.

pwpush.com is running Postgres 15.  I've never tested 16 but I would bet 9 out of 10 it work just the same.  Backup and feel free to upgrade.  Let me know if you have any issues.
