### ISSUE TITLE
Colour customisation

### ISSUE THREAD

**Issue by PUPeter** [pglombardo/PasswordPusher#164]
Is it possible to add customisation for background and font colour? 
This could possibly be implemented using a config file.

Also less important, the ability to upload a logo?

**Comment by pglombardo** [comment]
It would be nice if we had a dashboard for this but unfortunately my time is limited these days so I'm currently doing maintenance work only for now.  I'll keep this issue open as a reminder for the feature potentially for the future.

If you want to do it yourself manually, you could modify the source yourself to change the theme.  If you check the [fork network](https://github.com/pglombardo/PasswordPusher/network), some child forks have done this:
https://github.com/teimas/PasswordPusher/commits/master
https://github.com/myitguycorp/PasswordPusher/commit/da89b3e679efbcbda4783f084477a149ef57b638

Hopefully this is helpful for you.

**Comment by pglombardo** [comment]
I found this one tonight:
https://twitter.com/pwpush/status/1361093887905984519

**Comment by PUPeter** [comment]
@pglombardo Appreciate the replies. For now I've customised it like so:

![image](https://user-images.githubusercontent.com/71748362/107892647-b2b79100-6f7a-11eb-9978-6d85c4f33034.png)

**Comment by pglombardo** [comment]
That looks great!  I should create a gallery with links somewhere to show these off.

I'll close this issue out then.  If anything other issues remain, let me know.

**Comment by pglombardo** [comment]
Hi @PUPeter - you might also be interested in these [custom theme instructions](https://github.com/pglombardo/PasswordPusher/issues/762#issuecomment-1416718368).

Hope all is well!

**Comment by pglombardo** [comment]
Another update: As of v1.26.10 Password Pusher now

* comes with [26 themes](https://github.com/pglombardo/PasswordPusher/blob/master/Themes.md#theme-gallery) bundled in selectable by environment variable
* also supports [custom CSS](https://github.com/pglombardo/PasswordPusher/blob/master/Configuration.md#how-to-add-custom-css)
* supports [entirely custom themes](https://github.com/pglombardo/PasswordPusher/blob/master/Configuration.md#adding-an-entirely-new-theme-from-scratch)

With this framework and foundation, we'll be able to make sure that future changes don't break user customisations.

Hope all is well.
