### ISSUE TITLE
Setting PAYLOAD_INITIAL_TEXT to non-default causes the password box not to clear on selection  

### ISSUE THREAD

**Issue by sumnerboy12** [pglombardo/PasswordPusher#168]
If I set `PAYLOAD_INITIAL_TEXT=Enter password here` when I click on the password text field and start typing, the initial text is not removed so my typing is added to the text.

Think this is due to `prepareTextField()` in app/assets/javascripts/application.js, where the message being compared is hardcoded to the default initial text value.

This looks like it needs to retrieve the initial text value from the env vars when comparing?

**Comment by pglombardo** [comment]
This has been fixed.  Updated docker container images are still pending release.
