### ISSUE TITLE
Gh

### ISSUE THREAD

**Issue by Patosb500** [pglombardo/PasswordPusher#1716]
## Checklist

- [ ] I've searched the project's [`issues`](https://github.com/pglombardo/PasswordPusher/issues?q=is%3Aissue).
- [x] I've searched the project's [`discussions`](https://github.com/pglombardo/PasswordPusher/discussions).

## ❓ Question

How can I [...]?

Is it possible to [...]?

## 📎 Additional context

```

```

**Comment by pglombardo** [comment]
Hi @Patosb500 - if you meant to post a question, please file a new issue and I'd be happy to help out!
