### ISSUE TITLE
icon and flagassets with localdelivery

### ISSUE THREAD

**Issue by svbroeker** [pglombardo/PasswordPusher#1735]
## 🚀 Feature Request

The flags and icon assets are currently integrated directly via cdn.jsdelivr.net. For security reasons, we would like to deliver this content via the application itself. In this case, it would be good if there was a switch to enable local delivery.

And the files are packaged into the app.
## 🔈 Motivation

Security Reasons

**Comment by pglombardo** [comment]
If I remember correctly, I hit a blocker when I first added this icon/style set via yarn.  I'll give it another shot over the holidays.  Thanks for pointing this out!

**Comment by svbroeker** [comment]
@pglombardo did you give it a try?

**Comment by pglombardo** [comment]
No luck unfortunately.  The `bootstrap-icons` & SCSS support are non-functional.  The SASSC support in Rails is [unmaintained](https://github.com/rails/sass-rails/issues/451) too.  So back to square 1.  

After many variations and attempts, SASSC just can't import the file from the npm package.  You're welcome to take a shot if you'd like.

<img width="908" alt="Screenshot 2024-01-02 at 10 02 22" src="https://github.com/pglombardo/PasswordPusher/assets/395132/741c7967-6980-4f62-85e7-97af59a252aa">

I need to give it some thought.  Maybe I'll get lucky.

Longer term, I may switch entirely to TailwindCSS FYI which would remove this package (and the remote import) entirely.

**Comment by svbroeker** [comment]
As lightweight idea: Is it possible to make that URL for the assets configurable. That we can provide them from a host at our side.

**Comment by pglombardo** [comment]
It's definitely possible but not the highest priority currently as it may be wasted effort if I migrate away from bootstrap.  

I'm curious though, what's the situation for you/why do you need local only asset delivery?

**Comment by svbroeker** [comment]
We would like to use your tool to replace our current password exchange solution. We are bound by the security guidelines of the BSI in Germany. One point is that access to third parties is best prevented due to the access data (like IP addresses) that are collected there.

**Comment by pglombardo** [comment]
Understood and makes sense.  Let me see what I can do...

**Comment by svbroeker** [comment]
Thanks! Hope to hear soon some postive news

**Comment by svbroeker** [comment]
Can you give me some news here? for me it would be enough that we can config a URL for the assets at first.

**Comment by pglombardo** [comment]
Unfortunately nothing yet @svbroeker but I haven't forgotten.  Just jugging a day job and now the flu.

**Comment by pglombardo** [comment]
Progress in #1827

**Comment by pglombardo** [comment]
Hi @svbroeker - All assets are now hosted locally to the application.  This change has been released in [v1.36.9](https://github.com/pglombardo/PasswordPusher/releases/tag/v1.36.9).

Thanks for pointing this out.  Let me know if you see any issues.  New Docker containers are building now.

**Comment by pglombardo** [comment]
Hey @svbroeker - just a heads up:  I realized that some left over jsdelivr links were still in the email templates #1898.  Fixed in #1900 - I'll push out the fix over the weekend.
