### ISSUE TITLE
v1.36.4: Containers failing to build because of Ruby 3.3.0 bug

### ISSUE THREAD

**Issue by svbroeker** [pglombardo/PasswordPusher#1766]
## 🐛 Bug Report

There is actually no image für 1.36.4 on dockerhub. I was wondering about it.

## 📈 Expected behavior

Docker Image for newest release is available

**Comment by pglombardo** [comment]
Hi @svbroeker - I updated the containers to `ruby:3.3-alpine` and it turns out there is a bug in Ruby that causes the container build to fail.  :-(

Either I'll revert the change soon or it'll get fixed upstream.

**Comment by pglombardo** [comment]
Fixed: https://github.com/pglombardo/PasswordPusher/releases/tag/v1.36.5

Thanks @svbroeker for pointing this out!
