### ISSUE TITLE
Overhaul URL path scheme / routes

### ISSUE THREAD

**Issue by jantari** [pglombardo/PasswordPusher#1791]
## 🚀 Feature Request

Currently, the paths/routes this project uses are a total mess:

1. The path fragments are translated, meaning instead of `/es/p/new` for the spanish page, it's `/es/p/nuevo`
  This makes access logs impossible to read (literally, because one can't speak all the supported languages)
  and makes URL-based access restrictions at a proxy level impossible to enforce.
2. Completely unrelated endpoints overlap, e.g. the path for viewing a password is 
  `GET /en/p/:id` but *at the same time* `GET /en/p/new` is the page for creating a new push!
  This is a very big problem because it makes restricting access to the new-push page completely impossible.
3. The [API endpoints](https://pwpush.com/api) are all over the place, they're behind `/p/`, `/f/` and `/r/` all at once
  and they all end in `.json` despite not being a file (to download) and accepting both url-encoded data and json and
  the differentiator for that being the `Content-Type` header and not the URL path.

## 🔈 Motivation

The unstructured, overlapping and impossible-to-predict routes make the user experience worse (for example, can't just edit a language shortcode in a URL and have it still work like with all other websites) and they make it impossible to secure and audit the access to PasswordPusher.

## 🛰 Alternatives

Release a new major version (breaking change) with all routes redone and cleaned up, most importantly:

1. No more translating of path fragments, all URLs are always english

but additional refactoring would be very nice, for example:

2. All UI endpoints behind `/ui/`, the root URL `/` redirects to `/ui/`
3. E.g. for viewing a push: `/ui/shared/:id`, for creating one `/ui/push/new`
  Note there is no need to differentiate between file, text and url pushes in the URL because the ID of a push is already unique
4. UI Localization could be done with a query parameter e.g. `/ui/shared/:id?l=en`
5. All API endpoints behind `/api/` and make them more "standard", e.g. some ideas:
  ```diff
  GET /api/push/:id
    Retrieve a push.
  DELETE /api/push/:id
    Expire a push.
  POST /api/push
    Create a new push.
  -GET /p/:url_token/preview.json # remove this, just include the public URL in the response from `GET /api/push/:id`?
  GET /api/push/:id/audit
    Retrieve the audit log for a push.
  -GET /api/push/active.json # remove this, replace with `POST /api/push/list`
  -GET /api/push/expired.json # remove this, replace with `POST /api/push/list`
  +POST /api/push/list
  +  Allow to post a custom filter criteria to query pushes, e.g. `{"filter":{"expired":true}}`
  ```

## 📎 Additional context

I noticed these problems when testing PasswordPusher. I was going to deploy it like this:

![pwpush_architecture](https://github.com/pglombardo/PasswordPusher/assets/25607767/05094e95-193c-4a45-8557-9d25b89db332)

and I would have restricted the routes/URL paths the reverse proxy allows to only those required for viewing/retrieving secrets.
But due to the translated path fragments and the overlaps, that turned out to not be possible. I can still just restrict/disallow POST and DELETE requests, but then the "Create a new push" WebUI is still publicly accessible which just doesn't sit right with me.
These difficulties deploying PasswordPusher were already mentioned in https://github.com/pglombardo/PasswordPusher/issues/1101.

I realize this is not a change that can be made immediately, but I hope you see the problems with the current routes and that this should be changed.

Thank you for the project and your time.

**Comment by pglombardo** [comment]
Hi @jantari - I can understand the frustration although I wouldn't call it a total mess - more like an organized chaos. :-)

Application routes are translated for SEO - this duplicates every URL for each language added.  Plus the overlaps and `/f`, `/p` & `/u` don't help I'm sure.

This historical reason for the current state is that this is a constantly maintained project for +10 years.  Constant updates and feature requests are done atomically.  Being an OSS project with 1 maintainer for all this time, big re-architects like the one you propose just isn't possible.

Your proposal is well thought out and logical but the reality is that the project doesn't have the man power to implement it.

With that said, the current URL scheme is more than functional and I can help you work though the URLs if needed.

As one example, `/<lang>/p/<id>` will first search for `/<lang>/p/[new|update|create|edit]` before failing back to an `:id`.

I hope I explained myself and the OSS situation well enough.  I appreciate the valid feedback but it won't be possible to implement a change as large as this.

**Comment by jantari** [comment]
I understand, I see it was easier to just implement what I need myself ( https://github.com/jantari/SecretLinks ).
