### ISSUE TITLE
Hide Passphrase Lockdown

### ISSUE THREAD

**Issue by IMIjrebassa** [pglombardo/PasswordPusher#1856]
## Checklist

- [x ] I've searched the project's [`issues`](https://github.com/pglombardo/PasswordPusher/issues?q=is%3Aissue).
- [x] I've searched the project's [`discussions`](https://github.com/pglombardo/PasswordPusher/discussions).

## ❓ Question

How can I hide the Passphrase Lockdown option from the web?
![image](https://github.com/pglombardo/PasswordPusher/assets/51189609/d777aa2e-a65e-4ba9-b16b-43c5db3c4463)
Thanks

**Comment by pglombardo** [comment]
Hi @IMIjrebassa - this isn't possible currently.  This will be added sometime later there year as a part of team policies.

**Comment by pglombardo** [comment]
Hi @IMIjrebassa - I'll close this out but if you have any other questions or issues let me know!
