### ISSUE TITLE
[Defaults Settings]:  wrong file path is used when loading the defaults setting to merge with settings.yaml

### ISSUE THREAD

**Issue by Bozz95** [pglombardo/PasswordPusher#1874]
## 🐛 Bug Report

In the `config/initilizers/settings.rb` file is used the wrong file path to prepend defaults settings.

I discovered this with the latest release which introduced the maximum file uploads, which bugged out to 0 because the program didn't find any default.

Currently the path used to get the defaults is `config/settings-defaults.yml`:

```ruby
# Prepend defaults to the Settings object in case users are missing some of the latest settings
Settings.prepend_source!(Rails.root.join('config/settings-defaults.yml').to_s)

```

Which is not correct because the dockerfile copies the whole repo config directory which has `config/defaults/settings.yml`.

## 🔬 How To Reproduce

Simply deploy the latest release with file upload enabled and the settings.yml from a previous release

### Environment

Where are you running/using Password Pusher?

- [ ] pwpush.com
- [ ] Docker Image
  - [ ] pwpush
  - [ ] custom image
- [ ] Heroku
- [ ] Digital Ocean
- [ ] Microsoft Azure
- [ ] Google Cloud
- [x] AWS (EKS)
- [ ] Source Code
- [ ] Other (please specify)

If applicable, what version of Password Pusher?
1.37.3

### Screenshots

![image](https://github.com/pglombardo/PasswordPusher/assets/39773886/42a0f1ac-3332-4ea4-8d7a-4e623884f7f7)

## 📈 Expected behavior

The correct file path should be used to load defaults.

**Comment by pglombardo** [comment]
Thanks for reporting this @Bozz95.  The fix has been released in [v1.37.5](https://github.com/pglombardo/PasswordPusher/releases/tag/v1.37.5)
