### ISSUE TITLE
RGPD cookie banner always in english

### ISSUE THREAD

**Issue by ewidance** [pglombardo/PasswordPusher#1876]
## 🚀 Feature Request

Translations for RGPD cookie management are note implemented. Text is always in english:
"Browser cookies help make this tool work. By using it, you agree the use of these cookies."

## 🔈 Motivation

Proper internationalisation

## 🛰 Alternatives

Add config items for managing text by ourself.

## 📎 Additional context

Tested in french.

**Comment by pglombardo** [comment]
Hi @ewidance - thanks for pointing this out.  That's an oversight.  I'll see if I can get this fixed soon.

**Comment by pglombardo** [comment]
Hi @ewidance - the fix is in progress and should go out over the weekend.
