### ISSUE TITLE
Mail config items in config file are not proprely handled

### ISSUE THREAD

**Issue by ewidance** [pglombardo/PasswordPusher#1877]
## 🐛 Bug Report

I've installed a local copy of github settings.yml file and bound it into docker. Most config items are working, but mail server settings don't seem to be properly handled when managed thru settings.yml file.

mail:
```
  raise_delivery_errors: true
  smtp_address: mail.mydomain.com
  smtp_user_name: 'passwdpush@mydomain.com'
  smtp_password: 'MyPassword'
  smtp_domain: 'mydomain.com'
  smtp_port: 587
  smtp_authentication: 'plain'
  smtp_starttls: true
  smtp_enable_starttls_auto: false
  smtp_open_timeout: 10
  smtp_read_timeout: 10
  smtp_openssl_verify_mode: 'none'
  mailer_sender: '"Password Pusher" <passwdpush@mydomain.com>'
```

Symptoms: fallback to localhost port 25 (already seen in feedbacks..) instead of using provided port / server address.

Same settings, injected thru environnement vars works fine:
  PWP__MAIL__RAISE_DELIVERY_ERRORS: true
  PWP__MAIL__SMTP_ADDRESS: mail.mydomain.com
  PWP__MAIL__SMTP_USER_NAME: 'passwdpush@mydomain.com'
  PWP__MAIL__SMTP_PASSWORD: 'MyPassword'
  PWP__MAIL__SMTP_PORT: 587
  PWP__MAIL__SMTP_AUTHENTICATION: 'plain'
  PWP__MAIL__SMTP_STARTTLS: true
  PWP__MAIL__SMTP_ENABLE_STARTTLS_AUTO: false
  PWP__MAIL__OPEN_TIMEOUT: 10
  PWP__MAIL__READ_TIMEOUT: 10
  PWP__MAIL__MAILER_SENDER: '"Password Pusher" <passwdpush@mydomain.com>'

## 🔬 How To Reproduce

Create a local config file, and bind it to settings.yml . Setup mail settings and allow user registration. Try to register and see if mails are sent.

Where are you running/using Password Pusher?

- [ ] pwpush.com
- [x] Docker Image
  - [ ] pwpush
  - [ ] custom image
- [ ] Heroku
- [ ] Digital Ocean
- [ ] Microsoft Azure
- [ ] Google Cloud
- [ ] AWS
- [ ] Source Code
- [ ] Other (please specify)

If applicable, what version of Password Pusher?
latest

## 📈 Expected behavior

A working config file, or at least identifing items needed to be configured thru env vars.

**Comment by pglombardo** [comment]
That's interesting.  Thanks for pointing it out.  I'll take a look at this soon.

**Comment by pglombardo** [comment]
Hi @ewidance - I've made a few updates: in v1.39.8, I added a tool to test email configurations.  This should handle all settings properly now.

Could you update to that version and try [this out](https://github.com/pglombardo/PasswordPusher/wiki/How-to-Validate-and-Test-Email-Settings)?

It should reveal where any email configuration issues are...

**Comment by pglombardo** [comment]
Hey @ewidance.  The latest is now [v1.40.7](https://github.com/pglombardo/PasswordPusher/releases/tag/v1.40.7) and this issue should be resolved.

Since I haven't heard back, I'll close this out but if you ever want to pick up on this again - let me know.  I'd be happy to help.
