### ISSUE TITLE
500 error is returned when creating an account.

### ISSUE THREAD

**Issue by pragex** [pglombardo/PasswordPusher#1882]
## 🐛 Bug Report

The apps generates an error when creating a new account.

## 🔬 How To Reproduce

1. Goto /en/users/sign_up
2. Enter your email and password. 
3. Click on «Create Account»
4. A 500 error is generated.

### Environment

Where are you running/using Password Pusher?

- [ ] pwpush.com
- [x] Docker Image
  - [x] pwpush
  - [ ] custom image
- [ ] Heroku
- [ ] Digital Ocean
- [ ] Microsoft Azure
- [ ] Google Cloud
- [ ] AWS
- [ ] Source Code
- [ ] Other (please specify)

If applicable, what version of Password Pusher?

### Screenshots

![image](https://github.com/pglombardo/PasswordPusher/assets/7633792/f5bfde73-f36e-482f-83de-b7b6d0ba4837)

## 📎 Additional context

```
asswordpusher_1  | I, [2024-02-13T14:03:02.391490 #14]  INFO -- : [b41bac78-9a04-48a3-b2c4-c8877f1203fa] method=POST path=/fr/utilisateurs/password format=turbo_stream controller=Users::PasswordsController action=create status=422 allocations=9208 duration=29.01 view=13.39 db=0.89 ip=*.*.*.* forwarded_for=*.*.*.*
passwordpusher_1  | I, [2024-02-13T14:03:09.824526 #15]  INFO -- : [67f2c415-21fb-4f99-9ba4-0982000aa63e] method=GET path=/fr/utilisateurs/sign_up format=html controller=Users::RegistrationsController action=new status=200 allocations=6411 duration=15.75 view=13.61 db=0.00 ip=*.*.*.* forwarded_for=*.*.*.*
passwordpusher_1  | I, [2024-02-13T14:03:22.859240 #14]  INFO -- : [4b3a5d19-c5fb-4986-a910-bf0c47c66263] method=POST path=/fr/utilisateurs format=turbo_stream controller=Users::RegistrationsController action=create status=500 allocations=6299 duration=292.34 view=0.00 db=27.12 ip=*.*.*.* forwarded_for=*.*.*.*
passwordpusher_1  | E, [2024-02-13T14:03:22.862598 #14] ERROR -- : [4b3a5d19-c5fb-4986-a910-bf0c47c66263]
passwordpusher_1  | [4b3a5d19-c5fb-4986-a910-bf0c47c66263] NameError (undefined local variable or method `arguments' for #<Devise::Mailer:0x000000000ab608>):
passwordpusher_1  | [4b3a5d19-c5fb-4986-a910-bf0c47c66263]
passwordpusher_1  | [4b3a5d19-c5fb-4986-a910-bf0c47c66263] app/controllers/application_controller.rb:18:in `custom_set_locale_from_url'
```

**Comment by pglombardo** [comment]
Hi @pragex - which container version/tag did this happen on?

**Comment by pragex** [comment]
```
/opt/PasswordPusher$ docker compose up --force-recreate --build
[+] Running 1/1
 ✔ Container passwordpusher-passwordpusher-1  Recreated                                                                                                                                  0.1s
Attaching to passwordpusher-1
passwordpusher-1  |
passwordpusher-1  | According to DATABASE_URL database backend is set to postgres:...
passwordpusher-1  |
passwordpusher-1  | Password Pusher: migrating database to latest...
passwordpusher-1  | Password Pusher Version: 1.37.4
passwordpusher-1  | Password Pusher: starting puma webserver...
passwordpusher-1  | [12] Puma starting in cluster mode...
passwordpusher-1  | [12] * Puma version: 6.4.2 (ruby 3.2.3-p157) ("The Eagle of Durango")
passwordpusher-1  | [12] *  Min threads: 5
passwordpusher-1  | [12] *  Max threads: 5
passwordpusher-1  | [12] *  Environment: production
passwordpusher-1  | [12] *   Master PID: 12
passwordpusher-1  | [12] *      Workers: 2
passwordpusher-1  | [12] *     Restarts: (✔) hot (✖) phased
passwordpusher-1  | [12] * Preloading application
passwordpusher-1  | Password Pusher Version: 1.37.4
passwordpusher-1  | [12] * Listening on http://0.0.0.0:5100
passwordpusher-1  | [12] Use Ctrl-C to stop
passwordpusher-1  | [12] - Worker 0 (PID: 14) booted in 0.01s, phase: 0
passwordpusher-1  | [12] - Worker 1 (PID: 16) booted in 0.02s, phase: 0
passwordpusher-1  | I, [2024-02-15T16:16:24.830668 #14]  INFO -- : [1be8f085-6f2c-449c-b231-cdbfd1765a06] method=GET path=/fr format=html controller=PasswordsController action=new status=200 allocations=59254 duration=178.24 view=75.57 db=10.60 ip=*.*.*.* forwarded_for=*.*.*.*
passwordpusher-1  | I, [2024-02-15T16:16:26.551277 #16]  INFO -- : [a72e3227-a0af-4b22-bc06-3b9ee1370c87] method=GET path=/fr/utilisateurs/sign_up format=html controller=Users::RegistrationsController action=new status=200 allocations=56825 duration=170.70 view=52.20 db=11.83 ip=*.*.*.* forwarded_for=*.*.*.*
passwordpusher-1  | I, [2024-02-15T16:16:45.147524 #16]  INFO -- : [c92c47a8-7100-44ac-99f8-61ba7631f8b7] method=POST path=/fr/utilisateurs format=turbo_stream controller=Users::RegistrationsController action=create status=422 allocations=10166 duration=337.00 view=8.43 db=2.94 ip=*.*.*.* forwarded_for=*.*.*.*
passwordpusher-1  | I, [2024-02-15T16:17:04.452444 #16]  INFO -- : [82e44b5d-550a-45a4-a0e4-280388f63efe] method=POST path=/fr/utilisateurs format=turbo_stream controller=Users::RegistrationsController action=create status=500 allocations=8508 duration=491.76 view=0.00 db=4.87 ip=*.*.*.* forwarded_for=*.*.*.*
passwordpusher-1  | E, [2024-02-15T16:17:04.455901 #16] ERROR -- : [82e44b5d-550a-45a4-a0e4-280388f63efe]
passwordpusher-1  | [82e44b5d-550a-45a4-a0e4-280388f63efe] Net::SMTPSyntaxError (501 Syntax error in parameters
passwordpusher-1  | ):
passwordpusher-1  | [82e44b5d-550a-45a4-a0e4-280388f63efe]
passwordpusher-1  | [82e44b5d-550a-45a4-a0e4-280388f63efe] app/controllers/application_controller.rb:18:in `custom_set_locale_from_url'
```

**Comment by pragex** [comment]
> Hi @pragex, I found this error using "docker compose" instead docker-compose" and having tabs and comments (\t and #) at the end of the line. Removing tabs and comments, the 500 error is gone. Regards,

Hi @michuzo, 

I don't understand about the special characters at the end of the line your talking about. For which file or command do you recommend this?

**Comment by pragex** [comment]
> Hi @pragex - which container version/tag did this happen on?

My initial test are in release version 1.36.5. I have the problem in latest version 1.37.4 but with more verbose on the error.

**Comment by pragex** [comment]
> > > Hi @pragex, I found this error using "docker compose" instead docker-compose" and having tabs and comments (\t and #) at the end of the line. Removing tabs and comments, the 500 error is gone. Regards,
> > 
> > 
> > Hi @michuzo,
> > I don't understand about the special characters at the end of the line your talking about. For which file or command do you recommend this?
> 
> Hi @pragex, (sorry for my poor explain and poor english ;-)
> 
> in docker inspect i saw this in Env: section
> 
> PWP__MAIL__SMTP_ENABLE_STARTTLS_AUTO=true **#Detects if STARTTLS is enabled in your SMTP server and starts to use it. Default: true"**,
> 
> Text in bold, are comments, that works in "docker-compose" but not in "docker compose". In "docker compose" it generates error 500. I hope I have explained myself better

Hi @michuzo ,

Thank you for the precision. In my case, I don't have comment at the end of line.

**Comment by IanRVic** [comment]
We were seeing a similar error (#500)

tried all weekend with various smtp settings (authenticated, not authenticated, different ports, etc...) - all comes down to any time it tries to send an email (whether on sign up or on "didn't receive confirmation") - both seem to fail the same way.

tried with:
docker-compose up --force-recreate --build
tried with 
tried smtp with only IP authentication, ports 25, 587, 2525 (using mailgun or smtp2go - tried both)
nothing hits the mail server - seems to fail before intiating the send

looks like a release was published ~4 hours ago

now more info is visible and by adding variables of:
        PWP__HOST_DOMAIN: "x.y.z"
        PWP__HOST_PROTOCOL: "https"

problem went away and messages started sending
not sure if the issue was something in the release or I was just missing this info - either way it's happy (for me) now...

**Comment by pglombardo** [comment]
That's great to hear @IanRVic - not sure why though honestly.

Email seems to be problematic under some conditions that I haven't identified yet.

@pragex have you made any progress?

**Comment by pragex** [comment]
Hi @pglombardo , 

No, even with the PWP__HOST_DOMAIN and PWP__HOST_PROTOCOL variables defined, the problem occurs.
The only solution in my case is to set PWP__MAIL__RAISE_DELIVERY_ERRORS to false. The process doesn't crash but the mail isn't send.

I'm waiting this weekend to work on this problem and try another email service provider. I use Sendgrid to send emails.

**Comment by pglombardo** [comment]
pwpush.com uses Sendgrid as well.  Can you post your `settings.yml` or list of environment variables with sensitive info removed?  If you prefer, you can email at my github username @pwpush.com.

If you can send them over, I'll see if I can recreate the issue.

**Comment by pragex** [comment]
Hi @pglombardo, 

I use environment variables for my config in a ".env" file. 

```
DATABASE_URL="postgres://pwadmin:PASSWORD@host.docker.internal:5432/pwpush"
PWP__DEFAULT_LOCALE=en
PWP__SHOW_VERSION=false
PWP__SHOW_GDPR_CONSENT_BANNER=false
PWP__TIMEZONE=America/New_York
PWP__HOST_DOMAIN=x.y.z
PWP__HOST_PROTOCOL=https

PWP__GEN__HAS_NUMBERS=true
PWP__GEN__TITLE_CASED=true
PWP__GEN__USE_SEPARATORS=true
PWP__GEN__SEPARATORS="-_=?%!+*&$"
PWP__GEN__MAX_SYLLABLE_LENGTH=4
PWP__GEN__MIN_SYLLABLE_LENGTH=2
PWP__GEN__SYLLABLES_COUNT=4

PWP__ENABLE_LOGINS=true
PWP__ALLOW_ANONYMOUS=true
PWP__MAIL__RAISE_DELIVERY_ERRORS=true
PWP__MAIL__SMTP_ADDRESS=smtp.sendgrid.net
PWP__MAIL__SMTP_PORT=587
PWP__MAIL__SMTP_USER_NAME=apikey
PWP__MAIL__SMTP_PASSWORD=""
PWP__MAIL__SMTP_AUTHENTICATION=plain
PWP__MAIL__SMTP_STARTTLS=true
PWP__MAIL__SMTP_ENABLE_STARTTLS_AUTO=false
PWP__MAIL__OPEN_TIMEOUT=10
PWP__MAIL__MAILER_SENDER='"envoi" <do-not-reply@domain.cloud>"'
PWP__SIGNUP_EMAIL_REGEXP="\A[^@\s]+@(domain\.ca|domain\.qc\.ca)\z"
PWP__DISABLE_SIGNUPS=false

PWP__BRAND__TITLE=Informatique
PWP__BRAND__TAGLINE=
PWP__BRAND__DISCLAIMER=
PWP__BRAND__SHOW_FOOTER_MENU=false
PWP__BRAND__LIGHT_LOGO="https://x.y.z/static/img/logo.svg"
PWP__BRAND__DARK_LOGO="https://x.y.z/static/img/logo.svg"

PWP__PW__EXPIRE_AFTER_DAYS_DEFAULT=1
PWP__PW__EXPIRE_AFTER_DAYS_MIN=1
PWP__PW__EXPIRE_AFTER_DAYS_MAX=7
PWP__PW__EXPIRE_AFTER_VIEWS_DEFAULT=3
PWP__PW__EXPIRE_AFTER_VIEWS_MIN=1
PWP__PW__EXPIRE_AFTER_VIEWS_MAX=3
PWP__PW__ENABLE_DELETABLE_PUSHES=true
PWP__PW__DELETABLE_PUSHES_DEFAULT=true
PWP__PW__ENABLE_RETRIEVAL_STEP=true
PWP__PW__RETRIEVAL_STEP_DEFAULT=true
PWP__PW__ENABLE_BLUR=true

PWP__ENABLE_URL_PUSHES=true
PWP__URL__EXPIRE_AFTER_DAYS_DEFAULT=1
PWP__URL__EXPIRE_AFTER_DAYS_MIN=1
PWP__URL__EXPIRE_AFTER_DAYS_MAX=7
PWP__URL__EXPIRE_AFTER_VIEWS_DEFAULT=3
PWP__URL__EXPIRE_AFTER_VIEWS_MIN=1
PWP__URL__EXPIRE_AFTER_VIEWS_MAX=3
PWP__URL__ENABLE_DELETABLE_PUSHES=true
PWP__URL__DELETABLE_PUSHES_DEFAULT=true
PWP__URL__ENABLE_RETRIEVAL_STEP=true
PWP__URL__RETRIEVAL_STEP_DEFAULT=true

PWP__ENABLE_FILE_PUSHES=true
PWP__FILES__STORAGE=local
PWP__FILES__ENABLE_BLUR=true
PWP__FILES__ENABLE_DELETABLE_PUSHES=true
PWP__FILES__DELETABLE_PUSHES_DEFAULT=true
PWP__FILES__ENABLE_RETRIEVAL_STEP=true
PWP__FILES__RETRIEVAL_STEP_DEFAULT=true
PWP__FILES__MAX_FILE_UPLOADS=30
PWP__FILES__EXPIRE_AFTER_DAYS_DEFAULT=1
PWP__FILES__EXPIRE_AFTER_DAYS_MIN=1
PWP__FILES__EXPIRE_AFTER_DAYS_MAX=7
PWP__FILES__EXPIRE_AFTER_VIEWS_DEFAULT=3
PWP__FILES__EXPIRE_AFTER_VIEWS_MIN=1
PWP__FILES__EXPIRE_AFTER_VIEWS_MAX=3
```

**Comment by pglombardo** [comment]
Great - just a quick take:  there is an extra quote here (second to last character):
 
 `PWP__MAIL__MAILER_SENDER='"envoi" <do-not-reply@domain.cloud>"'`

it should be:

`PWP__MAIL__MAILER_SENDER='"envoi" <do-not-reply@domain.cloud>'`

**Comment by pragex** [comment]
Hi @pglombardo,

Yes, that's it! 

My error was the " character in the end of the line. I hadn't seen this character.

Thanks!
