### ISSUE TITLE
Enabling debugging for email troubles

### ISSUE THREAD

**Issue by michuzo** [pglombardo/PasswordPusher#1883]
## Checklist

- [x] I've searched the project's [`issues`](https://github.com/pglombardo/PasswordPusher/issues?q=is%3Aissue).
- [x] I've searched the project's [`discussions`](https://github.com/pglombardo/PasswordPusher/discussions).

## ❓ Question

I'm using 1.36.5 docker version.
I have trouble sending emails across internal postfix smtp server.
I'm trying to enable debugging with next configuration in setting.yml but the production.log file is not created in /opt/PasswordPusher/log

log_level: 'debug'
log_to_stdout: false

Can someone help me?

**Comment by pglombardo** [comment]
Hi @michuzo - have you made any progress on this?

I just released version [1.37.9](https://github.com/pglombardo/PasswordPusher/releases/tag/v1.37.9) which improves container logging.  This may help in identifying the issue.  That container version will have the log file that you noted was missing: `/opt/PasswordPusher/log/production.log`

Let me know.

**Comment by pglombardo** [comment]
Hi @michuzo - n v1.39.8, I added a tool to test email configurations. Could you update to that version and try [this out](https://github.com/pglombardo/PasswordPusher/wiki/How-to-Validate-and-Test-Email-Settings)?

It should reveal where the issue is...

**Comment by pglombardo** [comment]
Hi @michuzo - I'll close this out since I haven't heard back.  But if you ever do, the updated documentation to diagnose email settings is here: https://docs.pwpush.com/docs/troubleshooting-email/
