### ISSUE TITLE
Daily docker update but no version updates in Github

### ISSUE THREAD

**Issue by SANCLA** [pglombardo/PasswordPusher#1886]
## 🐛 Bug Report

I was wondering something.
I have a docker running with watchtower set to auto-updates docker images.
And every night, passwordpusher receives a new docker image.
However, looking at the recent releases, I can't see a daily release.
Am I missing something here?

## 🔬 How To Reproduce

1. https://github.com/pglombardo/PasswordPusher/releases
2. https://hub.docker.com/r/pglombardo/pwpush

**Comment by pglombardo** [comment]
Hi @SANCLA - the nightly build updates the `latest` tag only.

I'd like to change this eventually to update a `development` tag instead.  And have `latest` point to the latest version released.

It's just for historical reasons it's like this currently.

Did I explain this well enough?
