### ISSUE TITLE
FR: Add an Admin Portal for self-hosted

### ISSUE THREAD

**Issue by jaychinut** [pglombardo/PasswordPusher#1903]
## Checklist

- [ x] I've searched the project's [`issues`](https://github.com/pglombardo/PasswordPusher/issues?q=is%3Aissue).
- [ x] I've searched the project's [`discussions`](https://github.com/pglombardo/PasswordPusher/discussions).

## ❓ Question

How can I check what users have signed up to my pwpush app? 

Do I need to log onto the database directly?

Is there an admin portal I can use to see users and make changes/deletes?

**Comment by pglombardo** [comment]
We don't have a admin dashboard currently.

As a work around, you can work through application console.

To log into the rails console, enter the container and run `rails c`.  

From there you can use the following:

`User.all` - list all users
`users = User.all` - save the array of all users into `users`
`users.first` - get the first user
`users.last` - last user
`users[3]` - get the fourth user (zero index)
`users[2].destroy` - delete the user (irreversible unless you have a backup)

I marked this issue as a feature request.  We should add an admin panel.

**Comment by jaychinut** [comment]
Thanks for that note, I'm running this app from a docker container as that is the recommended way to do it in the documentation.  When running `rails c` from the container, rails is not found.  This app is indeed running properly in docker though. 
```
~ $ pwd
/opt/PasswordPusher
~ $ echo $HOME
/opt/PasswordPusher
~ $ rails c
/bin/sh: rails: not found
```

If no other workaround is available, I'll wait for the feature to be released in a future update.

**Comment by pglombardo** [comment]
Right/apologies.  That `rails` executable is in the bin folder.  This also works: `./bin/rails c`.  Thanks @steffenbusch!

**Comment by pglombardo** [comment]
This is happening.  Here's the first draft.  Not much effort on beauty but very functional.  :-)


<img width="1616" alt="Screenshot 2024-03-13 at 18 11 26" src="https://github.com/pglombardo/PasswordPusher/assets/395132/9ddff736-7558-4e69-91b3-c46758fe10f3">

**Comment by jaychinut** [comment]
This is excellent, thank you!  I'll be sure to look for it to be included in the future updates.

**Comment by blaine07** [comment]
I see this admin portal portion is coming a long; not sure where else to post BUT...

How can this, a user be flagged as administrator, be done for a instance running on Unraid for example?

https://github.com/pglombardo/PasswordPusher/blob/master/Configuration.md#marking-a-user-as-an-administrator

**Comment by pglombardo** [comment]
@blaine07 I moved your question to #1973 in case the discussion gets long (hopefully not and it's an easy fix).

@jaychinut @steffenbusch - [v1.39.0](https://github.com/pglombardo/PasswordPusher/releases/tag/v1.39.0) with the new Admin dashboard has been released.  Let me know if you see/find any issues.  Documentation in the release text.

**Comment by pglombardo** [comment]
I'll close this issue out.  If any issues/questions - let me know!
