### ISSUE TITLE
Dutch translation error

### ISSUE THREAD

**Issue by Mo72mMeD** [pglombardo/PasswordPusher#1911]
## 🐛 Bug Report

Dutch translation error on app/views/passwords/preview.html.erb on if @push.deletable_by_viewer. The translation should be "kan worden" if viewers are able to delete the push instead of "kan zijn" and "kan NIET worden" if viewers are not able to delete the push instead of "kan NIET zijn".

## 🔬 How To Reproduce

1. Set the language to Dutch
2. Generate and push a password
3. Translation error on "can be" and "can NOT be", it says "kan zijn" and "kan NIET zijn" which is grammatically incorrect.

### Code sample

<span style="color:#00AEEF">
        <% if @push.deletable_by_viewer %>
          <strong><%= _('can be') %></strong> <%= _('deleted by viewers.') %>
        <% else %>
          <strong><%= _('can NOT be') %></strong> <%= _('deleted by viewers.') %>
        <% end %>
</span>
</strong>

### Environment

Where are you running/using Password Pusher?

- [x] Docker Image

If applicable, what version of Password Pusher?

1.37.3

### Screenshots

![image](https://github.com/pglombardo/PasswordPusher/assets/17150966/0efb46d5-f3b7-45ec-9002-fca26dbd2192)

## 📈 Expected behavior

Translation should be "kan worden verwijderd door kijkers" and "kan NIET worden verwijderd door kijkers" instead of "kan zijn verwijderd door kijkers" and "kan NIET zijn verwijderd door kijkers".

**Comment by pglombardo** [comment]
Thanks @Mo72mMeD!  I'll update those strings and push out a new version soon.
