### ISSUE TITLE
How to get a Password Pusher container shell in Unraid?

### ISSUE THREAD

**Issue by pglombardo** [pglombardo/PasswordPusher#1973]
I see this admin portal portion is coming a long; not sure where else to post BUT...

How can this, a user be flagged as administrator, be done for a instance running on Unraid for example?

https://github.com/pglombardo/PasswordPusher/blob/master/Configuration.md#marking-a-user-as-an-administrator

_Originally posted by @blaine07 in https://github.com/pglombardo/PasswordPusher/issues/1903#issuecomment-1997964687_

**Comment by pglombardo** [comment]
Hi @blaine07 - [v1.39.0](https://github.com/pglombardo/PasswordPusher/releases/tag/v1.39.0) has been released with the new Admin dashboard feature.

Re: Unraid - Under the covers, Unraid just runs Docker containers so the process is mostly the same to get an shell inside the container.

Since I don't have Unraid running myself, ChatGPT might help...

This will help you get a Password Pusher shell in Unraid, and then you can follow the [Mark a User as an Administrator](https://github.com/pglombardo/PasswordPusher/blob/master/Configuration.md#marking-a-user-as-an-administrator) documentation.

Let me know if this helps.  Others may be able to chime in as well.

---------------------------------------------------------

In Unraid, you can use the `docker exec` command to get a shell into one of the running Docker containers. Here's how you can do it:

1. First, SSH into your Unraid server or open the Terminal in the Unraid web interface.

2. List the running Docker containers to get the Container ID or Name of the container you want to access:

   ```bash
   docker ps
   ```

   This command will list all the running Docker containers along with their Container ID, Name, and other information.

3. Once you have identified the Container ID or Name of the container you want to access, use the following command to get a shell into the container:

   ```bash
   docker exec -it <container_id_or_name> /bin/bash
   ```

   Replace `<container_id_or_name>` with the Container ID or Name of the container you want to access.

   If you want to run a specific command inside the container instead of getting a shell, you can replace `/bin/bash` with the command you want to run.

4. You should now have a shell prompt inside the specified Docker container, allowing you to execute commands and interact with the container's filesystem.

5. When you're done, you can exit the container's shell by typing `exit`.

That's it! You've now accessed a shell inside a running Docker container on your Unraid server.

**Comment by blaine07** [comment]
![image](https://github.com/pglombardo/PasswordPusher/assets/63940698/4b3f07d0-eebb-4dff-9438-3fa42b04b2f8)

Did that then bin/rails console

Then PasswordPusher.grant_system_admin!('user@example.com')

then exit exit to back out. Thank you! /admin now works. All the thank you!

**Comment by pglombardo** [comment]
I'll close this out @blaine07.  Have a good weekend!

**Comment by blaine07** [comment]
Thank you 😊

Thanks,

Blaine

--
Sent by carrier pigeon
