### ISSUE TITLE
Marking a User as an Administrator, Could not find table 'users'

### ISSUE THREAD

**Issue by assices** [pglombardo/PasswordPusher#1991]
## 🐛 Bug Report

Hello,

I run Password Pusher v1.39.1 on Kubernetes and I get an error marking a User as an Administrator.

## 🔬 How To Reproduce

As per [Configuration Guide](https://github.com/pglombardo/PasswordPusher/blob/master/Configuration.md#marking-a-user-as-an-administrator) instructions.

### Code sample

Error message:

`/opt/PasswordPusher/vendor/bundle/ruby/3.2.0/gems/activerecord-7.1.3.2/lib/active_record/connection_adapters/sqlite3_adapter.rb:458:in 'table_structure': Could not find table 'users' (ActiveRecord::StatementInvalid)`

### Environment

Where are you running/using Password Pusher?

- [ ] pwpush.com
- [x] Docker Image
  - [x] pwpush
  - [ ] custom image
- [ ] Heroku
- [ ] Digital Ocean
- [ ] Microsoft Azure
- [ ] Google Cloud
- [x] AWS
- [ ] Source Code
- [ ] Other (please specify)

Thanks for help

**Comment by pglombardo** [comment]
Hi @assices - that's a bug.  I just tracked down the problem in the Dockerfile.

As a work-around, run `export DATABASE_URL=sqlite3:db/db.sqlite3` first to fix.

Note: That DB is ephemeral unless you put it on a persistent volume.  I think you know this already.

Thanks for reporting.

**Comment by assices** [comment]
Hi @pglombardo It works, Thank!

**Comment by pglombardo** [comment]
Fixed in #1995.  This will be in the next container release.  Thanks for reporting @assices!
