### ISSUE TITLE
Idk

### ISSUE THREAD

**Issue by orangetigger813** [pglombardo/PasswordPusher#1996]
## 🔬 How To Reproduce

1. ...

### Environment

Where are you running/using Password Pusher?

- [ ] pwpush.com
- [ ] Docker Image
  - [ ] pwpush
  - [ ] custom image
- [ ] Heroku
- [ ] Digital Ocean
- [ ] Microsoft Azure
- [ ] Google Cloud
- [ ] AWS
- [ ] Source Code
- [ ] Other (please specify)

If applicable, what version of Password Pusher?

**Comment by pglombardo** [comment]
Hi @orangetigger813 - I'll close this out but let me know if you need any help...

**Comment by orangetigger813** [comment]
Hi
