### ISSUE TITLE
URL push with passphrase redirects to the passphrase page after successful validation, rather to payload url

### ISSUE THREAD

**Issue by thekamilpro** [pglombardo/PasswordPusher#1997]
I think I found a bug, when creating a new URL push with your website or API, the link redirects back to the URL push, rather than the site hidden by the push; I think it should at this point redirect to the hidden path. You can see in the screenshot below the Link leads to the same address as the actual push.

![image](https://github.com/pglombardo/PasswordPusher/assets/19328074/c77771ff-0747-4720-9e09-89adb604f681)

I had quick at the code and I _think_ this the responsible line

https://github.com/pglombardo/PasswordPusher/blob/ff18f623dc5e33054102b400ac3350bdc5853ac4/app/controllers/urls_controller.rb#L91

**Comment by pglombardo** [comment]
Hi @thekamilpro - Hrm good find - the 1-click doesn't make much sense when the passphrase lockdown is in use....

I just tested it and the flow was "Click Here to Proceed", Passphrase lockdown form, "Click Here to Proceed" again and then the final URL.

Thanks/I'll fix soon.

**Comment by clmcavaney** [comment]
I hit this same issue today.

**Comment by pglombardo** [comment]
Ok I think I have the right fix in #2059.  A bit more testing later today and I'll push it out.

**Comment by pglombardo** [comment]
Released in [v1.40.4](https://github.com/pglombardo/PasswordPusher/releases/tag/v1.40.4).

**Comment by clmcavaney** [comment]
Just tested this but the view's count doesn't appear to be decreasing.
I can view the URL way more than the number I set.
Could the view check detection be faulty when a passphrase is in the mix?

**Comment by pglombardo** [comment]
Doh thats not good.  I have a fix in progress now.  Thanks for the find!

**Comment by pglombardo** [comment]
Fix released in [v1.40.8](https://github.com/pglombardo/PasswordPusher/releases/tag/v1.40.8) which is building now.  I added a bunch of tests to validate this going forward for each release.

Thanks for the helpful report @clmcavaney!
