### ISSUE TITLE
Admin Dashboard User creation error

### ISSUE THREAD

**Issue by Oestle** [pglombardo/PasswordPusher#2008]
## 🐛 Bug Report

We're trying to create users via the Admin Dashboard but always get the Error "Password can't be blank", even though we fill out the "Encrypted password" field. A "Password" field is not present like maybe it should be, at least according to the error message.

## 🔬 How To Reproduce

1. Open Admin Dashboard/Users
2. Click on New User
3. Fill out E-Mail and Encrypted Password fields
4. Click create user

### Environment

Docker Container 
pglombardo/pwpush:1.39.3

### Screenshots

<img width="1651" alt="Screenshot 2024-03-28 at 15 10 46" src="https://github.com/pglombardo/PasswordPusher/assets/9599974/e4ed1d39-3e98-4777-b781-e4736decf480">

## 📈 Expected behavior

A user should be created, when both of those fields are filled out

**Comment by pglombardo** [comment]
Hi @Oestle - I have a fix locally that I'll get out very soon.  Thanks for reporting!  I'll update here once it's out.

**Comment by pglombardo** [comment]
Hi @Oestle - a fix for this is released in [v1.39.4](https://github.com/pglombardo/PasswordPusher/releases/tag/v1.39.4).  Could you give that a try and let me know?

**Comment by Oestle** [comment]
Thanks for the quick fix, it's working now! 🙂
