### ISSUE TITLE
FR: Option to setup reCAPTCHA to protect signup, login and feedback forms

### ISSUE THREAD

**Issue by pglombardo** [pglombardo/PasswordPusher#2078]
### Discussed in https://github.com/pglombardo/PasswordPusher/discussions/2077

<div type='discussions-op-text'>

<sup>Originally posted by **ivancarlosti** April 24, 2024</sup>
/t</div>

**Comment by pglombardo** [comment]
Password Pusher now uses invisible captcha for the last couple months which seems to work really well.

**Comment by Yudis53732** [comment]
Baik

Pada Min, 1 Sep 2024 22.32, Peter Giacomo Lombardo ***@***.***>
menulis:
