### ISSUE TITLE
The parameter PWP__SIGNUP_EMAIL_REGEXP does not work

### ISSUE THREAD

**Issue by CorentinDeBoisset** [pglombardo/PasswordPusher#2082]
## 🐛 Bug Report

When setting the environment variable `PWP__SIGNUP_EMAIL_REGEXP`, it has no effect. When searching in the code for the usage of the string `"regexp"` the only matches are the declaration of the parameter but it does not seems to be used anywhere.

## 🔬 How To Reproduce

1. Configure pwpush with `PWP__DISABLE_SIGNUPS=false` and `PWP__SIGNUP_EMAIL_REGEXP="\A[^@\s]+@domain\.tld\z"`
2. Create an account for another domain, gmail.com for instance
3. Receive a sign-up email instead of an error

### Code sample

N/A

### Environment

Where are you running/using Password Pusher?

- [ ] pwpush.com
- [x] Docker Image
  - [x] pwpush
  - [ ] custom image
- [ ] Heroku
- [ ] Digital Ocean
- [ ] Microsoft Azure
- [ ] Google Cloud
- [ ] AWS
- [ ] Source Code
- [ ] Other (please specify)

If applicable, what version of Password Pusher? 1.35.0

### Screenshots

N/A

## 📈 Expected behavior

There should be an error when trying to sign up using an email that does not match the regexp.

## 📎 Additional context

N/A

**Comment by anikwai** [comment]
Use single quotation `''` for the environment variable works for me. PWP__SIGNUP_EMAIL_REGEXP:` '\A[^@\s]+@[^@\s]+\z'`

**Comment by pglombardo** [comment]
That's a good point @anikwai - @CorentinDeBoisset have you tried with single quotes?  Are you still having this issue?

**Comment by pglombardo** [comment]
Hi @CorentinDeBoisset - let me know if this is still an issue for you.  If not, I'll close out this issue soon but you can re-open or file another anytime.  I'd be happy to help out.

**Comment by riahc3** [comment]
I had to do it without quotes at all..... (PWP__SIGNUP_EMAIL_REGEXP)

**Comment by pglombardo** [comment]
Hi @CorentinDeBoisset - if you're still having trouble with this let me know.   Since I haven't heard back I'll close this out for now.

**Comment by CorentinDeBoisset** [comment]
I left the company where the setup is installed but maybe @niromancier could try ?
