### ISSUE TITLE
User Search feature in Admin Portal not working

### ISSUE THREAD

**Issue by jaychinut** [pglombardo/PasswordPusher#2103]
## 🐛 Bug Report

I'm using the latest stable version 1.40.2 and it seems that the user search in the new Admin Portal doesn't work. 

## 🔬 How To Reproduce

1. Go to Admin Portal. when using search feature the URL would look like this. https://localhost/admin?search=username
This returns a 500 Error
An error occurred while processing your request.

### Environment

Where are you running/using Password Pusher?

- [ ] pwpush.com
- [x ] Docker Image
  - [ ] pwpush
  - [ x] custom image
- [ ] Heroku
- [ ] Digital Ocean
- [ ] Microsoft Azure
- [ ] Google Cloud
- [ ] AWS
- [ ] Source Code
- [ ] Other (please specify)

If applicable, what version of Password Pusher? 1.40.2

### Screenshots

<img width="529" alt="image" src="https://github.com/pglombardo/PasswordPusher/assets/66562652/f14fd78f-9033-4a21-bdc2-d43f225bd172">

## 📈 Expected behavior

I would expect the search to be able to query users by a contains search on the email address field

**Comment by pglombardo** [comment]
Hi @jaychinut - that was a bug fixed in [v1.40.3](https://github.com/pglombardo/PasswordPusher/releases/tag/v1.40.3).

**Comment by jaychinut** [comment]
Thanks, I've confirmed that this works in v1.40.3!
