### ISSUE TITLE
PasswordPusher in a Docker container behind an Apache reverse proxy - incorrect URLs

### ISSUE THREAD

**Issue by on6zq** [pglombardo/PasswordPusher#2108]
## Checklist

- [x ] I've searched the project's [`issues`](https://github.com/pglombardo/PasswordPusher/issues?q=is%3Aissue).
- [x ] I've searched the project's [`discussions`](https://github.com/pglombardo/PasswordPusher/discussions).

## ❓ Question

I am trying to run PasswordPusher in a Docker container accessible via an Apache reverse proxy on https://mydomain.com/pwpush/  .

This does not appear to work well as the URLs returned are absolute from "mydomain.com/" without the "pwpush/" part, so the resources (css, etc.) are not found.

I have tried all I could think of with X-Forwarded-Port, X-Forwarded-Host, X-Forwarded-Proto, X-Forwarded-Ssl in the Apache configuration, and PWP__OVERRIDE_BASE_URL in the container environment, but without success so far.

Would some one please post the relevant part of an Apache configuration that works to do this ?

Thank you in advance.

**Comment by pglombardo** [comment]
Hi @on6zq - running Password Pusher in a subfolder doesn't work.  It's best if you host it at a dedicated subdomain such as `pwpush.mydomain.com`.

I previously tried to add this functionality but I never could get it to work.

**Comment by on6zq** [comment]
>> dedicated subdomain

Thank you Peter.  I'll try that.

**Comment by on6zq** [comment]
OK.  With a subdomain, it works fine.  Thank you again.

Next question: setting the theme like below in docker-compose.yml does not work.  Tried with quotes and without.
Any clues ?


   passwordpusher:
      image:                        'pglombardo/pwpush:latest'
      container_name:               'WWW_passwordpusher'
      environment:
        - PWPUSH_MASTER_KEY=***
        - PWP__THEME=slate
      restart:                      'always'

**Comment by pglombardo** [comment]
Excellent - that's great to hear!  I'll close out this issue but if anything remains, feel free to re-open or file a new issue.
