### ISSUE TITLE
Admin panel 404

### ISSUE THREAD

**Issue by ados8** [pglombardo/PasswordPusher#2110]
## 🐛 Bug Report

When visiting domain.com/admin or IP:PORT/admin you get 404 page
![image](https://github.com/pglombardo/PasswordPusher/assets/49982433/c0fc6565-a9dc-4a35-9654-7b35c68c3027)

## 🔬 How To Reproduce

This happens when using all in one docker or docker + postgres.
Enable user sign-ups and other requirements as per docs (including admin).
Attempt to visit the URL.

![image](https://github.com/pglombardo/PasswordPusher/assets/49982433/1714c73a-ab1f-4ce2-b320-f27fb057e400)

### Environment

Where are you running/using Password Pusher?

Unraid (Linux)

If applicable, what version of Password Pusher?

Latest official image (v1.35.0), many fresh installs.

Based on photos of the admin panel I assumed this would load when accessing.
Using NGINX with nothing but the minimum to make it load, nothing fancy.

**Comment by pglombardo** [comment]
> Latest official image (v1.35.0), many fresh installs.

Hi @ados8 - the admin dashboard was added in [v1.39.0](https://github.com/pglombardo/PasswordPusher/releases/tag/v1.39.0).  There have also been many updates, fixes and improvements since then so if you can update to `latest` tag or the [current version v1.40.10](https://github.com/pglombardo/PasswordPusher/releases).

**Comment by ados8** [comment]
Default installation uses the latest tag on Unraid `pglombardo/pwpush-postgres`
Even specifying `pglombardo/pwpush-postgres:latest` still installed 1.35.0.
Manually specified the tag `1.40.10` and fails.
Using `pglombardo/pwpush-postgres:1.40.10` works, admin panel and all.
Seems the Unraid template is incorrect and might need fixing, explains why it was so out of date update.
Thanks @pglombardo, I didn't think it would have been an old image when it was fresh installs.

**Comment by pglombardo** [comment]
That's great to hear then @ados8!

I posted an update to the [Unraid template thread here](https://forums.unraid.net/topic/104128-support-passwordpusher-pwpush-corneliousjd-repo/?do=findComment&comment=1414439).  I'll look into whether I can get that template updated soon.

I'll close out this issue then.  If anything else comes up, feel free to re-open or file another issue.
