### ISSUE TITLE
/r/:url_token.json - Doesn't allow to pass passphrase

### ISSUE THREAD

**Issue by thekamilpro** [pglombardo/PasswordPusher#2114]
## 🐛 Bug Report

When creating a URL token with passphrase, there's no (at least documented) parameter to pass the passphrase - hence it's impossible to retrieve the URL push

## 🔬 How To Reproduce

In PowerShell land:

1. Generate API Key
2. Install-Module kppwpush
3. Connect-KpPwpush -Credential (Get-Credential)
4. $t = New-KpPwpushUrl -Payload "http://www.bbc.com" -Note "yak" -Passphrase bla
5. Get-KpPwpushUrl -UrlToken $t.url_token

Api returns error: This push has a passphrase that was incorrect or not provided.

### Code sample

Docs: https://pwpush.com/api/1.0/urls/show.en.html

### Environment

Where are you running/using Password Pusher?

- [x ] pwpush.com
- [ ] Docker Image
  - [ ] pwpush
  - [ ] custom image
- [ ] Heroku
- [ ] Digital Ocean
- [ ] Microsoft Azure
- [ ] Google Cloud
- [ ] AWS
- [ ] Source Code
- [ ] Other (please specify)

If applicable, what version of Password Pusher?

## 📈 Expected behavior

Ability to pass passphrase

**Comment by pglombardo** [comment]
Hi @thekamilpro - good point.  Fixed in #2118

**Comment by pglombardo** [comment]
Fix released in [v1.40.11](https://github.com/pglombardo/PasswordPusher/releases/tag/v1.40.11).  Closing - thanks @thekamilpro!

**Comment by pglombardo** [comment]
Hi @thekamilpro - Just an update that the API has some cleanup coming.  I'm adding support for `Authorization` headers as well.  It shouldn't break anything but just a heads up.  See #3068 

Hope all is well!
