### ISSUE TITLE
Can "© 2024 Pedro Giacomo Lombardo" be removed with a variable?

### ISSUE THREAD

**Issue by riahc3** [pglombardo/PasswordPusher#2182]
## 🚀 Feature Request

Remove © 2024 Pedro Giacomo Lombardo

## 🔈 Motivation

Make it cleaner

## 📎 Additional context

I know its your project and this might be a license issue even :) but just to make it cleaner and more corporate like

**Comment by pglombardo** [comment]
Hi @riahc3 - That footer area is not configurable.  It's the only place where I get humble credit for derivative work.

It would be nice if users left that copyright but if people remove it, I have no problem with that.

BTW I'll be catching up on your other issues soon.  Just juggling with the day job.

I'll close this issue but if anything remains, let me know!
