### ISSUE TITLE
Deleted note still perserve 1 click retrieval?

### ISSUE THREAD

**Issue by thecoffeebin** [pglombardo/PasswordPusher#2222]
I created a note which will be deleted after one view and enabled 1 click retrieval step.

After 1 view the note is deleted however when I visited the link I can still see the "Click here to proceed" link and then I was shown "We apologize but this secret link has expired.".

Expectation:
When note is deleted and user visited the shared link he/she should be seeing the message "We apologize but this secret link has expired." directly without the 1 step retrieval link.

Example
https://pwpush.com/en/p/ew4i-nifj2yrog/r

**Comment by thecoffeebin** [comment]
@pglombardo Can you perhaps have a look at this issue? It's still present in the latest release :)
Is there a mechanism (eg. cron) that removes the 1 step retrieval for expired/destroyed note? As I noticed the 1 step retrieval is eliminated after some time.

**Comment by pglombardo** [comment]
Hi @thecoffeebin - apologies I missed this issue.  That 1-click through page is really dumb and doesn't check the state of the push ahead of time.  It really is just a click through.

What is your motivation for the request?  Does this cause an issue for you?  Looking to understand why if you could tell me.

**Comment by thecoffeebin** [comment]
@pglombardo The reason I'm asking for is just that it requires an extra click to know that the secret has been vanished. Although that extra click doesn't really cost a lot of time ;) However the experience isn't that "smooth" in regards of expired notes. I come from privnote.com (just a user not self-hosting this) so it's based on that "biased" experience ;)

**Comment by pglombardo** [comment]
Hi @thecoffeebin - I'm adding this into the next release with #2285..  It should be out sometime soon.  Thanks for the suggestion!
