### ISSUE TITLE
Session Setting Warning in config/initializers/secret_token.rb

### ISSUE THREAD

**Issue by pglombardo** [pglombardo/PasswordPusher#23]
[Security issue from Hakiri](https://hakiri.io/projects/ff2039e94a5d4f/stacks/2105665b707a3a/builds/530271919cf221/warnings/41851316570826): Session secret should not be included in version control in config/initializers/secret_token.rb

**Comment by pglombardo** [comment]
Since pwpush is currently hosted on Heroku, I set a config and updated the app to try to retrieve the token from the environment first: https://github.com/pglombardo/PasswordPusher/commit/93451a4d991da1888342aff74ed4b23c3788304f

I populated the env var with the output from `rake secret`.

I'll be pushing out this change late night EST time tonight.

**Comment by davidsawyer** [comment]
:+1:
