### ISSUE TITLE
Admin page?

### ISSUE THREAD

**Issue by zarevskaya** [pglombardo/PasswordPusher#2326]
Hi :)

❓ Question

I use the :latest, Is there an administration page?

I couldn't find any information about this, or how to reach this page. I'm not saying the information doesn't exist, just that I haven't found it.

Thanks, have a nice day!

**Comment by pglombardo** [comment]
Hi @zarevskaya - coincidentally I'm writing a new centralized documentation portal today to better explain this.  :-)

The current documentation is hidden here:
https://github.com/pglombardo/PasswordPusher/blob/master/Configuration.md#admin-dashboard

The new docs portal will be released in a week or so.  Apologies for the issue.

If you have any questions/issues, let me know!

**Comment by zarevskaya** [comment]
Don't worry, thanks for the quick answer and your work. 👍

**Comment by zarevskaya** [comment]
Oh, ok! 👍

Thanks for the quick answer and to share your work!

**Comment by zarevskaya** [comment]
Amazing, that work very fine!

**Comment by pglombardo** [comment]
Thanks for the nice words @zarevskaya!  Here is the new documentation portal: https://docs.pwpush.com/docs/quick-start-guide/

Most everything has been moved there now.

**Comment by zarevskaya** [comment]
I'm already on it and it's well designed ;)

**Comment by zarevskaya** [comment]
https://belginux.com/installer-password-pusher-avec-docker/

**Comment by pglombardo** [comment]
That is an excellent article.  If you don't mind, I shared it on X: https://x.com/pwpush/status/1809902511303577905

**Comment by zarevskaya** [comment]
Thanks Monsieur! Everything is self-service, without copyright, we must promote open source developers!
