### ISSUE TITLE
[Docker] How to make DB persistent 

### ISSUE THREAD

**Issue by CWempe** [pglombardo/PasswordPusher#235]
As mentioned [here](https://github.com/pglombardo/PasswordPusher/issues/122#issuecomment-924737858): 

> since the DB doesn't persist

I just checked and verified a Password-Link is not valid after the container (pwpush-ephemeral) is removed and created/run again.

I guess the solution would be to mount the Database file as a volume.
Is this possible? Where is the file located?

**Comment by CWempe** [comment]
Thanks.

I will look into it, when I have some time.

**Comment by pglombardo** [comment]
I'm not sure if you got around to this @CWempe but we've updated that documentation and now have improved docker-compose files.  Any issues, let me know.
