### ISSUE TITLE
Email: Error 500 with localhost email

### ISSUE THREAD

**Issue by Cripix** [pglombardo/PasswordPusher#2360]
## 🐛 Bug Report

Error 500

![image](https://github.com/user-attachments/assets/e9352972-04c3-44c1-818e-b665faa474d9)

## 🔬 How To Reproduce

Sending a confirmation e-mail

### Environment

Where are you running/using Password Pusher?

- [ ] pwpush.com
- [ ] Docker Image
  - [ X ] pwpush + postgreSQL
  - [ ] custom image
- [ ] Heroku
- [ ] Digital Ocean
- [ ] Microsoft Azure
- [ ] Google Cloud
- [ ] AWS
- [ ] Source Code
- [ ] Other (please specify)

Version : 1.42.1

### Screenshots

![image](https://github.com/user-attachments/assets/4f61de2a-2b2f-4793-ae59-dc34e222b66b)

## 📎 Additional context
I use this method to send mail :
https://learn.microsoft.com/en-us/Exchange/mail-flow-best-practices/how-to-set-up-a-multifunction-device-or-application-to-send-email-using-microsoft-365-or-office-365?redirectSourcePath=%252fen-us%252farticle%252fHow-to-set-up-a-multifunction-device-or-application-to-send-email-using-Office-365-69f58e99-c550-4274-ad18-c805d654b4c4#settings-for-direct-send

**Comment by pglombardo** [comment]
Hi @Cripix - apologies for the issue.  I believe I have the fix in #2361.  I'll release shortly.

**Comment by pglombardo** [comment]
Excellent - that's great news.  If anything else comes up, let me know!
