### ISSUE TITLE
Tip not accurate after new auto-language selection

### ISSUE THREAD

**Issue by ivancarlosti** [pglombardo/PasswordPusher#2362]
## 🐛 Bug Report

The tip appears when we push something (I noticed after pushing a file):
`Tip: Pushing to an international user? Change the secret link language using the dropdown menu to the right of the URL.`
But the language selection is no longer displayed (at least for logged users)

## 🔬 How To Reproduce

1. Log in
2. Push a file
3. See the tip

### Environment

Where are you running/using Password Pusher?

- [ ] pwpush.com
- [x] Docker Image
  - [x] pwpush
  - [ ] custom image
- [ ] Heroku
- [ ] Digital Ocean
- [ ] Microsoft Azure
- [ ] Google Cloud
- [ ] AWS
- [ ] Source Code
- [ ] Other (please specify)

If applicable, what version of Password Pusher?

**Comment by pglombardo** [comment]
Hi @ivancarlosti - good point.  After some feedback though, I think I'm going to bring back the language dropdown soon.  I'll post back here soon.  Thanks for reporting!

**Comment by ivancarlosti** [comment]
look fine now
