### ISSUE TITLE
Upgrade v1.31.3 to v1.35.0 docker

### ISSUE THREAD

**Issue by vinkin56** [pglombardo/PasswordPusher#2393]
## Checklist

- [х] I've searched the project's [`issues`](https://github.com/pglombardo/PasswordPusher/issues?q=is%3Aissue).
- [х] I've searched the project's [`discussions`](https://github.com/pglombardo/PasswordPusher/discussions).

## ❓ Question

Hello!
Used v1.31.3 postgresql version of docker compose will be updated to v1.35.0
The log says that the version of postgresql 10 needs to be updated to 15.

I created a new database and launched it with version 15 of postgresql.

On version 10 of postgresql I made a full backup via pg_dumpall.

When I load data into v1.35.0 + postgresql 15 
psql -U passwordpusher_user -d postgres -f /var/lib/postgresql/15/data/dump_2024-08-05_10_04_52.sql
PasswordPusher doesn't work, I get a 500 error

Apparently the structure of the database has changed since version v1.31.3.

Is it possible to transfer data from v1.31.3 database to v1.35.0 postgresql?

**Comment by pglombardo** [comment]
Hi @vinkin56,

For future reference, you should be able to do an in-place upgrade.  Just upgrade the postgres container, and the new version of postgres will auto-upgrade your database.

As for structure changes, the pwpush Docker container, [automatically migrates the database](https://github.com/pglombardo/PasswordPusher/blob/master/containers/docker/entrypoint.sh#L17-L18) to the latest version on boot.

Could you:

1. Post the container boot logs

2. Inside the container, there is a `/opt/PasswordPusher/log` directory.  Could you look into those log files and post the stack trace of the error 500 here?

This should tell us quickly where the issue is.

**Comment by vinkin56** [comment]
Thank you!

I did this:
I added the old postgresql 10 to docker compose and mounted volume /OLDDB.

Made a dump in old postgresql 10
pg_dump -U passwordpusher_user -d passwordpusher_db -f bddump_`date +%Y-%m-%d"_"%H_%M_%S`.sql

Copied the file to volume/DB of the new postgresql 15

Drop database:
psql -U passwordpusher_user -d postgres -c "DROP DATABASE passwordpusher_db WITH (FORCE);"

Created a database:
psql -U passwordpusher_user -d postgres -c "CREATE DATABASE passwordpusher_db;"

Loaded data from dump:
psql -U passwordpusher_user -d passwordpusher_db < /var/lib/postgresql/15/data/bddump_2024-08-05_14_16_41.sql

**But after restarting docker compose, the database is cleared!**

-- table_exists?(:active_storage_blobs)
   -> 0.0005s
-- create_table(:active_storage_variant_records, {:id=>:primary_key, :if_not_exists=>true})
   -> 0.0034s
== 20221113194838 CreateActiveStorageVariantRecords: migrated (0.0040s) =======
Migrating to RemoveNotNullOnActiveStorageBlobsChecksum (20221113194839)
== 20221113194839 RemoveNotNullOnActiveStorageBlobsChecksum: migrating ========
-- table_exists?(:active_storage_blobs)
   -> 0.0006s
-- change_column_null(:active_storage_blobs, :checksum, true, nil)
   -> 0.0003s
== 20221113194839 RemoveNotNullOnActiveStorageBlobsChecksum: migrated (0.0010s) 
Migrating to CreateFilePushes (20221222153323)
== 20221222153323 CreateFilePushes: migrating =================================
-- create_table(:file_pushes)
   -> 0.0109s
== 20221222153323 CreateFilePushes: migrated (0.0110s) ========================
Migrating to AddFilePushToViews (20221223103402)
== 20221223103402 AddFilePushToViews: migrating ===============================
-- add_column(:views, :file_push_id, :integer, {:default=>nil, :index=>true})
   -> 0.0007s
== 20221223103402 AddFilePushToViews: migrated (0.0008s) ======================
Migrating to CreateUrls (20221228160730)
== 20221228160730 CreateUrls: migrating =======================================
-- create_table(:urls)
   -> 0.0110s
== 20221228160730 CreateUrls: migrated (0.0110s) ==============================
Migrating to AddUrlToViews (20221228161228)
== 20221228161228 AddUrlToViews: migrating ====================================
-- add_column(:views, :url_id, :integer, {:default=>nil, :index=>true})
   -> 0.0009s
== 20221228161228 AddUrlToViews: migrated (0.0009s) ===========================
Migrating to RemoveDeletableFromUrls (20230113173429)
== 20230113173429 RemoveDeletableFromUrls: migrating ==========================
-- remove_column(:urls, :deletable_by_viewer, :boolean, {:default=>true})
   -> 0.0005s
== 20230113173429 RemoveDeletableFromUrls: migrated (0.0006s) =================
Migrating to AddPassphraseToModels (20230406094931)
== 20230406094931 AddPassphraseToModels: migrating ============================
-- add_column(:passwords, :passphrase_ciphertext, :text, {:null=>false, :default=>"", :limit=>2048})
   -> 0.0008s
-- add_column(:file_pushes, :passphrase_ciphertext, :text, {:null=>false, :default=>"", :limit=>2048})
   -> 0.0006s
-- add_column(:urls, :passphrase_ciphertext, :text, {:null=>false, :default=>"", :limit=>2048})
   -> 0.0005s
== 20230406094931 AddPassphraseToModels: migrated (0.0020s) ===================
Migrating to FixPassphraseDefault (20230420175410)
== 20230420175410 FixPassphraseDefault: migrating =============================
-- change_column_null(:passwords, :passphrase_ciphertext, true, nil)
   -> 0.0004s
-- change_column_null(:file_pushes, :passphrase_ciphertext, true, nil)
   -> 0.0002s
-- change_column_null(:urls, :passphrase_ciphertext, true, nil)
   -> 0.0002s
-- change_column_default(:passwords, :passphrase_ciphertext, nil)
   -> 0.0018s
-- change_column_default(:file_pushes, :passphrase_ciphertext, nil)
   -> 0.0018s
-- change_column_default(:urls, :passphrase_ciphertext, nil)
   -> 0.0016s
== 20230420175410 FixPassphraseDefault: migrated (0.0062s) ====================
Password Pusher: precompiling assets for customisations...
/opt/PasswordPusher/vendor/bundle/ruby/3.2.0/gems/rack-3.0.8/lib/rack/file.rb:5: warning: Rack::File is deprecated and will be removed in Rack 3.1
Password Pusher Version: 1.35.0
I, [2024-08-05T15:27:30.422027 #11]  INFO -- : Writing /opt/PasswordPusher/public/assets/application-11c79a14736c9666427f1a4bf31fcf185fe6c1902c22f92b4c3ee1c117ce8864.css
I, [2024-08-05T15:27:30.422284 #11]  INFO -- : Writing /opt/PasswordPusher/public/assets/application-11c79a14736c9666427f1a4bf31fcf185fe6c1902c22f92b4c3ee1c117ce8864.css.gz
Password Pusher: starting puma webserver...
[246] Puma starting in cluster mode...
[246] * Puma version: 6.4.0 (ruby 3.2.2-p53) ("The Eagle of Durango")
[246] *  Min threads: 5
[246] *  Max threads: 5
[246] *  Environment: production
[246] *   Master PID: 246
[246] *      Workers: 2
[246] *     Restarts: (✔) hot (✖) phased
[246] * Preloading application
/opt/PasswordPusher/vendor/bundle/ruby/3.2.0/gems/rack-3.0.8/lib/rack/file.rb:5: warning: Rack::File is deprecated and will be removed in Rack 3.1
Password Pusher Version: 1.35.0
[246] * Listening on http://0.0.0.0:5100
[246] Use Ctrl-C to stop
[246] - Worker 0 (PID: 248) booted in 0.01s, phase: 0
[246] - Worker 1 (PID: 249) booted in 0.01s, phase: 0

**Comment by pglombardo** [comment]
Do you have the beginning of that boot log?

If you don't, shell into the container and tell me what the `DATABASE_URL` environment variable is.

**Comment by vinkin56** [comment]
DATABASE_URL: 'postgres://passwordpusher_user:mypasswd@postgres15:5432/passwordpusher_db'

          ##########################################################################          
          ###                 !!END OF SUPPORT NOTIFICATION!!                    ###          
          ###            THIS IMAGE HAS REACHED END-OF-SUPPORT STATE.            ###          
          ###       THERE WILL BE NO MORE NEW FEATURES OR SECURITY UPDATES.      ###          
          ###        PLEASE MIGRATE TO THE NEW IMAGE AS SOON AS POSSIBLE.        ###          
          ###                                                                    ###          
          ###                      FOR MORE INFORMATION GOTO                     ###          
          ###            https://github.com/pglombardo/PasswordPusher            ###          
          ###                 !!END OF SUPPORT NOTIFICATION!!                    ###          
          ##########################################################################          
According to DATABASE_URL database backend is set to postgres:...
Password Pusher: migrating database to latest...
/opt/PasswordPusher/vendor/bundle/ruby/3.2.0/gems/rack-3.0.8/lib/rack/file.rb:5: warning: Rack::File is deprecated and will be removed in Rack 3.1
Migrating to DropLegacyEncryptionFields (20220524163629)
== 20220524163629 DropLegacyEncryptionFields: migrating =======================
-- remove_column(:passwords, :payload_legacy)
   -> 0.0007s
-- remove_column(:passwords, :note_legacy)
   -> 0.0002s
== 20220524163629 DropLegacyEncryptionFields: migrated (0.0010s) ==============
Migrating to AddAuthenticationTokenToUsers (20220816102729)
== 20220816102729 AddAuthenticationTokenToUsers: migrating ====================
-- add_column(:users, :authentication_token, :string, {:limit=>30})
   -> 0.0008s
-- add_index(:users, :authentication_token, {:unique=>true, :name=>"index_users_on_authentication_token"})
   -> 0.0023s
== 20220816102729 AddAuthenticationTokenToUsers: migrated (0.0033s) ===========
Migrating to AddServiceNameToActiveStorageBlobs (20221113194837)
== 20221113194837 AddServiceNameToActiveStorageBlobs: migrating ===============
-- table_exists?(:active_storage_blobs)
   -> 0.0006s
-- column_exists?(:active_storage_blobs, :service_name)
   -> 0.0013s
== 20221113194837 AddServiceNameToActiveStorageBlobs: migrated (0.0020s) ======
Migrating to CreateActiveStorageVariantRecords (20221113194838)
== 20221113194838 CreateActiveStorageVariantRecords: migrating ================
-- table_exists?(:active_storage_blobs)
   -> 0.0005s
-- create_table(:active_storage_variant_records, {:id=>:primary_key, :if_not_exists=>true})
   -> 0.0032s
== 20221113194838 CreateActiveStorageVariantRecords: migrated (0.0038s) =======
Migrating to RemoveNotNullOnActiveStorageBlobsChecksum (20221113194839)
== 20221113194839 RemoveNotNullOnActiveStorageBlobsChecksum: migrating ========
-- table_exists?(:active_storage_blobs)
   -> 0.0006s
-- change_column_null(:active_storage_blobs, :checksum, true, nil)
   -> 0.0003s
== 20221113194839 RemoveNotNullOnActiveStorageBlobsChecksum: migrated (0.0009s) 
Migrating to CreateFilePushes (20221222153323)
== 20221222153323 CreateFilePushes: migrating =================================
-- create_table(:file_pushes)
   -> 0.0113s
== 20221222153323 CreateFilePushes: migrated (0.0115s) ========================
Migrating to AddFilePushToViews (20221223103402)
== 20221223103402 AddFilePushToViews: migrating ===============================
-- add_column(:views, :file_push_id, :integer, {:default=>nil, :index=>true})
   -> 0.0009s
== 20221223103402 AddFilePushToViews: migrated (0.0009s) ======================
Migrating to CreateUrls (20221228160730)
== 20221228160730 CreateUrls: migrating =======================================
-- create_table(:urls)
   -> 0.0110s
== 20221228160730 CreateUrls: migrated (0.0111s) ==============================
Migrating to AddUrlToViews (20221228161228)
== 20221228161228 AddUrlToViews: migrating ====================================
-- add_column(:views, :url_id, :integer, {:default=>nil, :index=>true})
   -> 0.0010s
== 20221228161228 AddUrlToViews: migrated (0.0011s) ===========================
Migrating to RemoveDeletableFromUrls (20230113173429)
== 20230113173429 RemoveDeletableFromUrls: migrating ==========================
-- remove_column(:urls, :deletable_by_viewer, :boolean, {:default=>true})
   -> 0.0005s
== 20230113173429 RemoveDeletableFromUrls: migrated (0.0006s) =================
Migrating to AddPassphraseToModels (20230406094931)
== 20230406094931 AddPassphraseToModels: migrating ============================
-- add_column(:passwords, :passphrase_ciphertext, :text, {:null=>false, :default=>"", :limit=>2048})
   -> 0.0008s
-- add_column(:file_pushes, :passphrase_ciphertext, :text, {:null=>false, :default=>"", :limit=>2048})
   -> 0.0006s
-- add_column(:urls, :passphrase_ciphertext, :text, {:null=>false, :default=>"", :limit=>2048})
   -> 0.0005s
== 20230406094931 AddPassphraseToModels: migrated (0.0021s) ===================
Migrating to FixPassphraseDefault (20230420175410)
== 20230420175410 FixPassphraseDefault: migrating =============================
-- change_column_null(:passwords, :passphrase_ciphertext, true, nil)
   -> 0.0006s
-- change_column_null(:file_pushes, :passphrase_ciphertext, true, nil)
   -> 0.0003s
-- change_column_null(:urls, :passphrase_ciphertext, true, nil)
   -> 0.0003s
-- change_column_default(:passwords, :passphrase_ciphertext, nil)
   -> 0.0020s
-- change_column_default(:file_pushes, :passphrase_ciphertext, nil)
   -> 0.0019s
-- change_column_default(:urls, :passphrase_ciphertext, nil)
   -> 0.0018s
== 20230420175410 FixPassphraseDefault: migrated (0.0071s) ====================
Password Pusher: precompiling assets for customisations...
/opt/PasswordPusher/vendor/bundle/ruby/3.2.0/gems/rack-3.0.8/lib/rack/file.rb:5: warning: Rack::File is deprecated and will be removed in Rack 3.1
Password Pusher Version: 1.35.0

**Comment by vinkin56** [comment]
After booting or restarting
![image](https://github.com/user-attachments/assets/e4c0d9ea-3dec-4243-8b9c-dd70a71644e1)

![image](https://github.com/user-attachments/assets/2c72fcbb-d562-48db-a3f2-83ee7c2b8175)

![image](https://github.com/user-attachments/assets/9c3fc277-77c0-4249-928b-7ff2ef8d338f)

![image](https://github.com/user-attachments/assets/45c41c89-e916-4bf9-b091-782ef952f420)

After restarting database is clear

**Comment by pglombardo** [comment]
Hrm ok.  If it runs through those migrations on boot, it's not using the DB you imported with `psql`.  We are missing something.  Let me give it some thought...

**Comment by vinkin56** [comment]
Solved a problem.

My fault.

To migrate from postgresql 10 to 15 I changed the mount paths.

https://github.com/tianon/docker-postgres-upgrade/tree/master

Original:
 - /docker/pwpusher/DB/:**/var/lib/postgresql/data**

Modified by me:
- /docker/pwpusher/DB/:**/var/lib/postgresql/15/data**

Returned the original path to compose.

Thanks for the tip. The task can be closed.

**Comment by pglombardo** [comment]
Excellent - that's great to hear.

When you can - migrating to the new pwpush container is a [simple changing the docker image.](https://docs.pwpush.com/docs/how-to-universal/#how-to-migrate)

If any other issues come up, let me know.
