### ISSUE TITLE
Setting view count to 1 has unintuitive outcome

### ISSUE THREAD

**Issue by psteinweber** [pglombardo/PasswordPusher#24]
First of all, I love pwpush - thanks for the time that you are putting in there.

I'm using it for receiving passwords from clients occasionally, and sometimes they set the view count to 1. Unfortunately the one view seems to be used when they're being redirected to the site for copying the link. So I'm getting expired passwords quite frequently. 
Any chance to fix this, so that the first view of the person copying the link isn't counted?

Thanks,
Philipp

**Comment by pglombardo** [comment]
I know this has been a minor aggravation for some people.  I've finally fixed this locally and will be pushing out the change late night EST time tonight.

With this change, it doesn't record the first view which is always given to the password creator.

This should have been fixed sooner - thanks for everyone's patience!
