### ISSUE TITLE
TIme/Timezone not right?

### ISSUE THREAD

**Issue by a1010s** [pglombardo/PasswordPusher#2403]
## 🔬 How To Reproduce

1. Generating a password push, the generating time in dashboard is for ex.: 
Freitag, 09. August 2024, 02:39 Uhr  and my actual time is:
Freitag, 09. August 2024, 08:39 Uhr

Locale setting are setted to DE.

It looks like a timezone problem.
### Environment

Where are you running/using Password Pusher?

- [ ] pwpush.com
- [ ] Docker Image
  - [ ] pwpush
  - [ ] custom image
- [ ] Heroku
- [ ] Digital Ocean
- [ ] Microsoft Azure
- [ ] Google Cloud
- [ ] AWS
- [ ] Source Code
- [ x ] Other (please specify)
Kubernetes on Azure AKS.
If applicable, what version of Password Pusher?
latest

**Comment by pglombardo** [comment]
Hi @a1010s - set the `PWP__TIMEZONE` environment variable [documented here](https://docs.pwpush.com/docs/other-configurations/).

In the pipeline, I have per user timezone settings coming but for now, use the above option.

<img width="911" alt="pwpush-edit-profile" src="https://github.com/user-attachments/assets/21230c4b-c967-4bd4-8309-fe0242bf31c2">

**Comment by a1010s** [comment]
Wow! Thanks a lot for your fast help! It worked perfectly. Redeployed on Kubernetes -> took about 20 seconds and now the timezone is the right one!

**Comment by a1010s** [comment]
Thank you for your help Peter!
