### ISSUE TITLE
protocol and port not taken into account in the environment variable PWP__OVERRIDE_BASE_URL

### ISSUE THREAD

**Issue by tibo59** [pglombardo/PasswordPusher#2437]
## 🐛 Bug Report

Hello, the protocol and port defined in the environment variable PWP__OVERRIDE_BASE_URL are not taken into account.
Regards,
Thibaut

## 🔬 How To Reproduce

1. shell command 
_docker run -e PWP__OVERRIDE_BASE_URL='https://test.domain:12345' -d -p "5100:5100" pglombardo/pwpush:latest_

2. push generated :
http://test.domain:5100/p/bzggdmmvgqogpq

### Environment

Where are you running/using Password Pusher?

- [X] Docker Image

If applicable, what version of Password Pusher?

### Screenshots

<img width="680" alt="image" src="https://github.com/user-attachments/assets/ddf49d29-dafb-438c-914f-a11e71160962">

## 📈 Expected behavior

According to the comments in the settings.yml file, the protocol and port are supported in the environment variable.
The result should be :
https://test.domain:12345/p/bzggdmmvgqogpq

**Comment by pglombardo** [comment]
Doh - thanks for reporting @tibo59!  I have the fix in progress.

**Comment by pglombardo** [comment]
v1.45.3 is building now:
https://github.com/pglombardo/PasswordPusher/releases/tag/v1.45.3

**Comment by tibo59** [comment]
Thanks a lot @pglombardo !
