### ISSUE TITLE
Push links with a custom language aren't displayed in the selected language when "Use a 1-click retrieval step" is enable.

### ISSUE THREAD

**Issue by mathsyx69** [pglombardo/PasswordPusher#2443]
## 🔬 How To Reproduce

Create a push with "Use a 1-click retrieval step" enable, on the push link sharing page select a language.

For example this push : 
https://pwpush.com/p/zwdkjecpac_ctayv/r?locale=es

When you access the link the message "1-click retrieval step" message is display in spanish:

![image](https://github.com/user-attachments/assets/c471886a-b370-4904-88bc-f5e2fa4a4aa3)

We can see that the additional link (displayed bottom right) to click does not contain the GET variable “?locale=es”.

When you click on it the page to retreive the push is display in your browser language (for myself English) : 
![image](https://github.com/user-attachments/assets/1e15146c-9a4d-47ad-94ee-5711c6e40876)

I think it was forgotten when the language menu was reinstalled.

### Environment

Where are you running/using Password Pusher?

- [x] pwpush.com
- [x] Docker Image on podman
  - [x] pwpush

This bug exist on pwpush.com and my instance.

If applicable, what version of Password Pusher?

1.45.3

## 📈 Expected behavior

The page to retreive the password should be display in the language selected when creating the push.

**Comment by pglombardo** [comment]
Doh - Thanks for reporting @mathsyx69 - I'll fix this very soon.

**Comment by pglombardo** [comment]
This is fixed in [v1.45.4](https://github.com/pglombardo/PasswordPusher/releases/tag/v1.45.4).  Thanks again @mathsyx69!

**Comment by mathsyx69** [comment]
Thank you for the quick fix @pglombardo !
