### ISSUE TITLE
Testing MySQL beta

### ISSUE THREAD

**Issue by clmcavaney** [pglombardo/PasswordPusher#245]
referring to Pull request https://github.com/pglombardo/PasswordPusher/pull/244

Looks to be working (except for the [default value issue for the note field in the passwords table](https://github.com/pglombardo/PasswordPusher/pull/244#issuecomment-944873856)).

One thing I did notice is that the IP address in the views table was the IP address of the docker service.  Should that be the IP address of the viewer?

**Comment by clmcavaney** [comment]
G'day,
MySQL version is:
`mysqld  Ver 5.7.35-0ubuntu0.18.04.2 for Linux on x86_64 ((Ubuntu`

I did add the column manually - I was then able to get past the error.
Does that field need a default value or could be be allowed to have NULL?

**Comment by pglombardo** [comment]
> Does that field need a default value or could be be allowed to have NULL?

I need to test it but I don't believe the default value is necessary.  NULL should be fine.  Once I get some time, I'll likely just modify that migration file to remove the default value.

**Comment by clmcavaney** [comment]
I have the ephemeral version up - will transition to mysql over the next couple of days.

**Comment by pglombardo** [comment]
Some final testing remains but I believe this should be it.  The default value has been removed from the migration in #256.

**Comment by clmcavaney** [comment]
Cool - I will test again and let you know.

**Comment by clmcavaney** [comment]
Working well - thanks Peter

**Comment by pglombardo** [comment]
Ok that's great to hear.  I also added the new container to the build process so we get tagged containers:
https://hub.docker.com/r/pglombardo/pwpush-mysql/tags
