### ISSUE TITLE
Unauthenticated SMTP fails "No SMTP username provided"

### ISSUE THREAD

**Issue by kaffe19** [pglombardo/PasswordPusher#2471]
## 🔬 How To Reproduce

1. pull pglombardo/pwpush:latest
2.  set PWP__MAIL__SMTP_ENABLE_STARTTLS_AUTO -> false
3. do not set PWP__MAIL__SMTP_AUTHENTICATION, PWP__MAIL__SMTP_USER_NAME or PWP__MAIL__SMTP_PASSWORD
(exactly as when it was working before)

4. send test mail from console: password-pusher(prod)> TestMailer.send_test_email("abc@cde.ef").deliver_now

--> Configured FROM: address: 'abc@abc.abc'
app/mailers/test_mailer.rb:7:in `send_test_email': No SMTP username provided: smtp_user_name (StandardError)

SMTPsettings:

password-pusher(prod)> Rails.application.config.action_mailer.smtp_settings
=> {:address=>"mysmtpserver.example.com", :port=>25, :open_timeout=>10, :read_timeout=>10, :enable_starttls_auto=>false}

Where are you running/using Password Pusher?

- [ ] pwpush.com
- [x] Docker Image
  - [x] pwpush
  - [ ] Custom image
- [ ] Heroku
- [ ] Digital Ocean
  - [ ] App Platform
  - [ ] Kubernetes Service
- [ ] Microsoft Azure
  - [ ] App Service
  - [ ] Container Instances (ACI)
  - [ ] Kubernetes Service (AKS)
- [ ] Google Cloud
  - [ ] App Engine
  - [ ] Cloud Run
  - [ ] Kubernetes Engine
- [ ] AWS
  - [ ] Elastic Container Service (ECS)
  - [ ] Kubernetes Service (AKS)
- [ ] Source Code
- [ ] Other (please specify)

## 📈 Expected behavior

Mail should be deliverd to SMTP server unauthenticaded on port 25, in case user is not set.

**Comment by MadWalnut** [comment]
I have the exact same problem, also using Docker. 

@pglombardo Perhaps adding a configuration example for unauthenticated SMTP on port 25 to [the docs](https://docs.pwpush.com/docs/troubleshooting-email/#known-working-configurations) would be helpful as well?

**Comment by tol0** [comment]
Same here, would be great to have this fixed. Any workaround?

**Comment by pglombardo** [comment]
Hi all - just an update.  I'm looking at this today.

**Comment by pglombardo** [comment]
I think it's been more than ~10 years since I setup a local postfix instance.  :-) 

I made some fixes and got email working with postfix on localhost:25.  [v1.45.10](https://github.com/pglombardo/PasswordPusher/releases/tag/v1.45.10) is building now.

Could you update your containers and revalidate with the TestMailer?  Fingers crossed, this should be an improvement.

@MadWalnut - once I get validations, I'll add local mail server instructions to the docs for sure.

**Comment by pglombardo** [comment]
FWIW, this was my output with the updated `TestMailer`.

I left `smtp_address` and `smtp_port` commented out and the system defaults to `localhost:25`.

```
password-pusher(dev)> TestMailer.send_test_email("pglombardo@hey.com").deliver_now

--> Configured FROM: address: '"Password Pusher" <oss@pwpush.com>'
--> No SMTP address provided. Mail subsystem should default to localhost.

The settings.yml mail configuration is:
----------
raise_delivery_errors: false
smtp_port: 587  <--- ignore: this is the default.  Not used unless smtp_address is set
smtp_enable_starttls_auto: true
smtp_open_timeout: 10
smtp_read_timeout: 10
mailer_sender: "Password Pusher" <oss@pwpush.com>
----------

The Mail subsystem SMTP configuration is:
----------
address:
port:
open_timeout: 10
read_timeout: 10
enable_starttls_auto: true
----------

--> raise_delivery_errors is set to false.  Set to true to see errors if the email fails to send.

--> Attempting to send a test email to pglombardo@hey.com...
--> ✅  It seems that the Email was accepted by the SMTP server!  Check destination inbox for the test email.

--> If you see an error, please paste this output into a GitHub issue for help.
  --> Make sure that no sensitive data is included.
  --> https://github.com/pglombardo/PasswordPusher/issues/new/choose

TestMailer#send_test_email: processed outbound mail in 11.2ms
Delivered mail 66f2fd7326504_1a6716a84233c@postfix10onubuntu2404-s-1vcpu-2gb-ams3-01.mail (89.8ms)
Date: Tue, 24 Sep 2024 17:57:07 +0000
From: Password Pusher <oss@pwpush.com>
To: pglombardo@hey.com
Message-ID: <66f2fd7326504_1a6716a84233c@postfix10onubuntu2404-s-1vcpu-2gb-ams3-01.mail>
Subject: Test Email from Password Pusher
Mime-Version: 1.0
Content-Type: text/plain;
 charset=UTF-8
Content-Transfer-Encoding: quoted-printable

=E2=AD=90 If you are reading this, sending email works! =E2=AD=90=

=> #<Mail::Message:28360, Multipart: false, Headers: <Date: Tue, 24 Sep 2024 17:57:07 +0000>, <From: "Password Pusher" <oss@pwpush.com>>, <To: pglombardo@hey.com>, <Message-ID: <66f2fd7326504_1a6716a84233c@postfix10onubuntu2404-s-1vcpu-2gb-ams3-01.mail>>, <Subject: Test Email from Password Pusher>, <Mime-Version: 1.0>, <Content-Type: text/plain>, <Content-Transfer-Encoding: quoted-printable>>

```

**Comment by kaffe19** [comment]
It seems to work. I do now recieve password reset emails aswell as emails from TestMailer. Well done!

This is my TestMailer output:

```
The settings.yml mail configuration is:
----------
raise_delivery_errors: false
smtp_port: 25
smtp_enable_starttls_auto: false
smtp_open_timeout: 10
smtp_read_timeout: 10
smtp_starttls: false
smtp_address: xxxxx.yy
mailer_sender: aaa@bb.cc
----------

The Mail subsystem SMTP configuration is:
----------
address: xxxxx.yy
port: 25
open_timeout: 10
read_timeout: 10
enable_starttls_auto: false
----------

--> raise_delivery_errors is set to false.  Set to true to see errors if the email fails to send.

--> Attempting to send a test email to abc@cde.ef...
--> ✅   It seems that the Email was accepted by the SMTP server!  Check destination inbox for the test email.

--> If you see an error, please paste this output into a GitHub issue for help.
  --> Make sure that no sensitive data is included.
  --> https://github.com/pglombardo/PasswordPusher/issues/new/choose

=> #<Mail::Message:165740, Multipart: false, Headers: <Date: Tue, 24 Sep 2024 19:46:21 +0000>, <From: aaa@bb.cc>, <To: abc@cde.ef>, <Message-ID: <66f3170dd027e_781450955a2@pwd.private.mail>>, <Subject: Test Email from Password Pusher>, <Mime-Version: 1.0>, <Content-Type: text/plain>, <Content-Transfer-Encoding: quoted-printable>>
```

**Comment by pglombardo** [comment]
That's excellent news.  Then I'll close this out soon unless there are any remaining issues.  Thanks all for reporting and help in investigating.

**Comment by pglombardo** [comment]
Closing.  @tol0 - if you still have email issues let me know and I can re-open.  Thanks all!

**Comment by pglombardo** [comment]
Hi @Kbche - the environment variable `PW__MAIL__SMTP_PORT` is incorrect.  It should be `PWP__MAIL__SMTP_PORT`.  Could you try that out and let me know?

**Comment by Kbche** [comment]
thanks a lot  !!   what a mistake , i spend a lot of time on it

**Comment by pglombardo** [comment]
No problem!  That has happened to me more times than I can count. :-)
