### ISSUE TITLE
customize template

### ISSUE THREAD

**Issue by radunan** [pglombardo/PasswordPusher#2474]
## Checklist

- [ x] I've searched the project's [`issues`](https://github.com/pglombardo/PasswordPusher/issues?q=is%3Aissue).
- [x ] I've searched the project's [`discussions`](https://github.com/pglombardo/PasswordPusher/discussions).

## ❓ Question

How can I customize just one template? For example i want to customize template which appears when user click on the link and u see the password. I want to add logo here. I tried to use volume in docker-compose.yml but it didnt work. Thanks

**Comment by Yudis53732** [comment]
@radunan

**Comment by pglombardo** [comment]
Hi @radunan - are you using pwpush.com or self-hosting the application?

**Comment by pglombardo** [comment]
> I tried to use volume in docker-compose.yml but it didnt work.

Ah ok/missed this - currently, push branding is released as a premium feature on pwpush.com.

See below for an example.  This is part of the new [feature pipeline](https://docs.pwpush.com/posts/feature-pipeline/#feature-pipeline) for the project..

I have this lined up to be added to the open source version soon.  There are a couple other items that have to be pushed out first.

![premium-delivery-page](https://github.com/user-attachments/assets/04b32346-32ff-4931-bd45-15fe36e0b330)

**Comment by radunan** [comment]
Ok thank you for the information. Keep going. Good work.

**Comment by radunan** [comment]
Sorry i have one more question. Im trying to set my own favicon. I again tried it through volumes and the icons are in the container. But when i set it into docker-compose.yml it doesnt change anything.

**Comment by radunan** [comment]
Nevermind i already figured out my mistake. Thank you
