### ISSUE TITLE
Some docker .env variable are not getting applied

### ISSUE THREAD

**Issue by wedowhateverwewant** [pglombardo/PasswordPusher#2475]
## Checklist

- [x ] I've searched the project's [`issues`](https://github.com/pglombardo/PasswordPusher/issues?q=is%3Aissue).
- [ x] I've searched the project's [`discussions`](https://github.com/pglombardo/PasswordPusher/discussions).

## ❓ Question

I am self hosting my instance on docker , everything works except that some env variables will not apply. for example all of the mail, branding, signup stuff works. but trying to set the env variables below for Password, Files, URL, will not work and instead uses the system defaults which are 7 for expire days after and 5 view limit

the ones I cant get it to use:
PWP__PW__EXPIRE_AFTER_DAYS_DEFAULT=1
PWP__PW__EXPIRE_AFTER_VIEWS_DEFAULT=1
PWP__FILES__EXPIRE_AFTER_DAYS_DEFAULT=1
PWP__FILES__EXPIRE_AFTER_VIEWS_DEFAULT=1
PWP__URL__EXPIRE_AFTER_DAYS_DEFAULT=1
PWP__URL__EXPIRE_AFTER_VIEWS_DEFAULT=1

oh and also this one works for Files and URL, but not for password
PWP__PW__RETRIEVAL_STEP_DEFAULT='true'

any thoughts ?

**Comment by pglombardo** [comment]
Hi @wedowhateverwewant - which container and tag are you using?

**Comment by wedowhateverwewant** [comment]
I am using 
  pwpush:
    image: docker.io/pglombardo/pwpush:latest

with 

  db:
    image: mysql:8.0.32

**Comment by pglombardo** [comment]
Could you open an [application console](https://docs.pwpush.com/docs/application-console/) and paste here the output from these commands?

```ruby
Settings.pw.map { |k, v| k.to_s.include?("expire_after") ? [k, v] : nil }.compact
Settings.files.map { |k, v| k.to_s.include?("expire_after") ? [k, v] : nil }.compact
Settings.url.map { |k, v| k.to_s.include?("expire_after") ? [k, v] : nil }.compact
```

**Comment by wedowhateverwewant** [comment]
see below:

Settings.pw.map { |k, v| k.to_s.include?("expire_after") ? [k, v] : nil }.compact

=> [[:expire_after_days_default, 1], [:expire_after_days_min, 1], [:expire_after_days_max, 20], [:expire_after_views_default, 1], [:expire_after_views_min, 1], [:expire_after_views_max, 100]]

Settings.files.map { |k, v| k.to_s.include?("expire_after") ? [k, v] : nil }.compact

=> [[:expire_after_days_default, 1], [:expire_after_days_min, 1], [:expire_after_days_max, 7], [:expire_after_views_default, 1], [:expire_after_views_min, 1], [:expire_after_views_max, 100]]

Settings.url.map { |k, v| k.to_s.include?("expire_after") ? [k, v] : nil }.compact

=> [[:expire_after_days_default, 1], [:expire_after_days_min, 1], [:expire_after_days_max, 7], [:expire_after_views_default, 1], [:expire_after_views_min, 1], [:expire_after_views_max, 100]]


ENV.map { |k, v| k.to_s.include?("EXPIRE_AFTER") ? [k, v] : nil }.compact

=>
[["PWP__URL__EXPIRE_AFTER_DAYS_MIN", "1"],
 ["PWP__PW__EXPIRE_AFTER_VIEWS_MIN", "1"],
 ["PWP__FILES__EXPIRE_AFTER_VIEWS_MIN", "1"],
 ["PWP__URL__EXPIRE_AFTER_VIEWS_MIN", "1"],
 ["PWP__FILES__EXPIRE_AFTER_DAYS_DEFAULT", "1"],
 ["PWP__URL__EXPIRE_AFTER_VIEWS_DEFAULT", "1"],
 ["PWP__PW__EXPIRE_AFTER_DAYS_DEFAULT", "1"],
 ["PWP__URL__EXPIRE_AFTER_DAYS_DEFAULT", "1"],
 ["PWP__URL__EXPIRE_AFTER_VIEWS_MAX", "100"],
 ["PWP__FILES__EXPIRE_AFTER_VIEWS_MAX", "100"],
 ["PWP__PW__EXPIRE_AFTER_VIEWS_MAX", "100"],
 ["PWP__URL__EXPIRE_AFTER_DAYS_MAX", "7"],
 ["PWP__PW__EXPIRE_AFTER_VIEWS_DEFAULT", "1"],
 ["PWP__PW__EXPIRE_AFTER_DAYS_MIN", "1"],
 ["PWP__FILES__EXPIRE_AFTER_DAYS_MIN", "1"],
 ["PWP__FILES__EXPIRE_AFTER_DAYS_MAX", "7"],
 ["PWP__PW__EXPIRE_AFTER_DAYS_MAX", "20"],
 ["PWP__FILES__EXPIRE_AFTER_VIEWS_DEFAULT", "1"]]

**Comment by pglombardo** [comment]
I copied the env vars and tested this locally and it works for me.  Further I have tests to validate this I believe and so far there haven't been any other reports of this issue.

I'm trying to imagine what else could be the cause here.  When you boot the app, you don't see defaults like this?

![Screenshot 2024-08-30 at 22 21 14](https://github.com/user-attachments/assets/9ad5fcdb-7811-44a5-a30c-6769d5e62ce1)

I'll give this some thought.

**Comment by pglombardo** [comment]
Could it be that you have a local cookie saved?  Try in a new private browser and see which defaults come up.

**Comment by wedowhateverwewant** [comment]
oh wow, I never thought this could be the reason but it was the cache. 

I was under impression that settings would get updated to the system default but I guess not.

Thank you

**Comment by pglombardo** [comment]
Ok that's great to hear!  I should have seen that sooner but better late then never.  

I'll close out this issue but if you hit any other issues, feel free to contact/file another issue anytime.
