### ISSUE TITLE
How to enable reCAPTCHA?

### ISSUE THREAD

**Issue by ivancarlosti** [pglombardo/PasswordPusher#2483]
As noted in #[2078](https://github.com/pglombardo/PasswordPusher/issues/2078) loks like we some kind of reCAPTCHA support, but I am unable to find how to setup it.

Please, do we have any documentation about this?

**Comment by pglombardo** [comment]
Hi @ivancarlosti -  I haven't added reCaptcha support to the app.  I first went with [invisible_captcha](https://github.com/markets/invisible_captcha) and has worked well.  It's enabled by default doesn't require any configuration.

Side note: Have you seen the [public gateway](https://docs.pwpush.com/docs/public-gateway/)?  Could it be useful in your case?

What pages are you having a problem on regarding the captcha?

**Comment by ivancarlosti** [comment]
aaaah got it, I supposed you were talking about reCAPTCHA :/

Waiting for something like that but np 🥲
