### ISSUE TITLE
You cannot save your settings anymore

### ISSUE THREAD

**Issue by PwPusherIsBroken** [pglombardo/PasswordPusher#2489]
The settings/sliders under where it says "Expire this push and delete after:" do not save anymore. You must reset them every single time you refresh the page. 

This was an extremely useful feature. Please bring it back!

**Comment by pglombardo** [comment]
Hi @PwPusherIsBroken - Great name by the way.  😆 

That shouldn't be the case.

Where are you using Password Pusher?  Self-hosted?

**Comment by PwPusherIsBroken** [comment]
pwpush.com
We believe there used to be a save button somewhere to accomplish this? But we don't see that anywhere anymore

**Comment by PwPusherIsBroken** [comment]
Oh great! When I think "Policy" I think legal documents that I don't need to see which is why I didn't even try that. 
"Settings" i think would be a better choice of words. Either way, thank you for the solution.

**Comment by pglombardo** [comment]
Agree - the term "Policy" was intended towards teams.  For one man shops, maybe I should use another term (like settings).

I'll close out this issue but if there's ever anything else, feel free to contact me anytime.
