### ISSUE TITLE
Local Files Storage

### ISSUE THREAD

**Issue by BehzadInc** [pglombardo/PasswordPusher#2496]
## Checklist

- [ x] I've searched the project's [`issues`](https://github.com/pglombardo/PasswordPusher/issues?q=is%3Aissue).
- [ x] I've searched the project's [`discussions`](https://github.com/pglombardo/PasswordPusher/discussions).

## ❓ Question

I have a self hosted pwpusher docker instance, all works good. except for files. 
when I go to upload a file thats 157.35 MB in size or just any files in general that are uploaded the loading bar fills up but then its loading for ever, restarting the page clears everything. as if it was never uploading. I do have it set for local storage ( see my env variables below). tried both in private mode and still same thing. the instance is behind a nginx proxy but even when it wasn't I had the same issue. I suspect my storage setup is messed up. 

#Files
 PWP__ENABLE_FILE_PUSHES='true'
 PWP__FILES__EXPIRE_AFTER_DAYS_DEFAULT=1
 PWP__FILES__EXPIRE_AFTER_DAYS_MIN=1
 PWP__FILES__EXPIRE_AFTER_DAYS_MAX=7
 PWP__FILES__EXPIRE_AFTER_VIEWS_DEFAULT=1
 PWP__FILES__EXPIRE_AFTER_VIEWS_MIN=1
 PWP__FILES__EXPIRE_AFTER_VIEWS_MAX=100
 PWP__FILES__ENABLE_RETRIEVAL_STEP='true'
 PWP__FILES__RETRIEVAL_STEP_DEFAULT='true'
 PWP__FILES__ENABLE_DELETABLE_PUSHES='true'
 PWP__FILES__DELETABLE_PUSHES_DEFAULT='true'
 PWP__FILES__BLUR='true'
 PWP__FILES__MAX_FILE_UPLOADS=10
 PWP__FILES_STORAGE='local'

and in the docker compose file storage for the pwpush container is like so:
    volumes:
      - ./FilesStorage:/opt/PasswordPusher/storage

am I doing something wrong ?

anything is appreciated.

**Comment by pglombardo** [comment]
Hi @BehzadInc - try accessing the pwpush container directly and uploading a file there (bypassing nginx).  This will tell us if the problem is with nginx or pwpush.

**Comment by BehzadInc** [comment]
Okay so I tried accessing it via localhost and the same happens. Now I also went inside the container into the path /opt/PasswordPusher/storage and created a text file which just appeared fine in the host side inside  ./FilesStorage and that operations works. but via UI either localhost or proxy does not work. I tried zip, exe files ....

**Comment by pglombardo** [comment]
Check the docker logs for the container.  It's likely that there might be a permissions issue for the mounted volume you have.

The pwpush container is a non-root container.  The app runs under uid:gid 1000:1000.  You might have to set ownership to that uid:gid to work.

Could you post the docker logs here after you attempt to upload a file?

**Comment by BehzadInc** [comment]
ok giving the container root permissions or I guess permission to write resolved the issue.
