### ISSUE TITLE
The identity of this website has been verified by PositiveSSL CA 2 but does not have public audit records.

### ISSUE THREAD

**Issue by davidsawyer** [pglombardo/PasswordPusher#25]
![screen shot 2014-12-08 at 1 07 23 pm](https://cloud.githubusercontent.com/assets/724087/5344256/b15dc784-7edb-11e4-9aa2-f0bf5d9a2e82.png)

**Comment by vaindil** [comment]
Just a note: I don't know if Chrome displayed it this way in the past, but version 42 updated a ton of security updates and pwpush.com is now shown (to general users) as having completely insecure SSL. I don't know what specifically is causing it to be marked that way, as other sites without public audit records display without the red X just fine, and it specifically says the cryptography is up-to-date. It is using SHA1, however; I'm guessing that's the problem.

![pwpush](https://cloud.githubusercontent.com/assets/771134/7236906/ef8f3644-e765-11e4-9512-f27b13f4c448.png)

**Comment by pglombardo** [comment]
Ugh that's not good.  Thanks for letting me know.  I'll see about getting a re-issued cert.

**Comment by pglombardo** [comment]
Fixed - I had the cert re-issued which used SHA2.  Thanks @davidsawyer + @vaindil !

![screenshot 2015-05-03 16 25 08](https://cloud.githubusercontent.com/assets/395132/7445398/593dc484-f1b1-11e4-839c-3d70ab6cd5a5.png)
