### ISSUE TITLE
Protocol set to HTTPS, but im seeing pwpush attempt to touch http behind reverse proxy

### ISSUE THREAD

**Issue by rivalsystems** [pglombardo/PasswordPusher#2535]
## 🐛 Bug Report

I have pwpush hidden behind an haproxy instance which is doing the SSL. This works fine until you try to push a password, as the pwpush instance still tries to hit an http endpoint, which is blocked.

## 🔬 How To Reproduce

PWP__HOST_PROTOCOL is set to https in my docker env
### Environment

Where are you running/using Password Pusher?

- [x] Docker Image
  - [x] pwpush

### Screenshots
![image](https://github.com/user-attachments/assets/694a2ef4-bcaf-4cf9-899e-cd9547568712)

## 📈 Expected behavior

WIth https chosen as my host protocol, should pressing the button not try to hit an https;// endpoint? We dont enable port 80

**Comment by rivalsystems** [comment]
Found my answer shortly after in the documentation, sorry 

https://docs.pwpush.com/docs/proxies/

**Comment by pglombardo** [comment]
That's great!   ...and good to know the docs are useful. :-)
