### ISSUE TITLE
Provide `release` docker-image-tag

### ISSUE THREAD

**Issue by tempuser5432** [pglombardo/PasswordPusher#255]
When watching for the `latest`-tag at dockerhub, it seems like this tag gets updated every day.

Can you additionally provide a `release`-tag such that one may watch that to have a stable entrypoint for new releases (i.e. currently, it would point to `1.10.2`)?

Thanks!

**Comment by pglombardo** [comment]
Good idea.  Done:

https://hub.docker.com/layers/pglombardo/pwpush-ephemeral/release/images/sha256-796001c9755b3f557f3c7381a63a1db66a4ab581e42db7c5bcd706cffe5ea44d?context=repo

Going forward I'll update the release tags when I tag new versions.

**Comment by pglombardo** [comment]
All done - thanks for pointing this out!

**Comment by tempuser5432** [comment]
Wow, that was quick. Thanks a lot!
