### ISSUE TITLE
invalid http format

### ISSUE THREAD

**Issue by wedowhateverwewant** [pglombardo/PasswordPusher#2561]
## Checklist

- [x ] I've searched the project's [`issues`](https://github.com/pglombardo/PasswordPusher/issues?q=is%3Aissue).
- [x ] I've searched the project's [`discussions`](https://github.com/pglombardo/PasswordPusher/discussions).

## ❓ Question

I have the pwpusher server with mysql  +gateway setup, however gateway logs are saying:

gateway-1  | 2024-09-25 22:27:38 +0000 HTTP parse error, malformed request: #<Puma::HttpParserError: Invalid HTTP format, parsing fails. Are you trying to open an SSL connection to a non-SSL Puma?>
gateway-1  | 2024-09-25 22:27:39 +0000 HTTP parse error, malformed request: #<Puma::HttpParserError: Invalid HTTP format, parsing fails. Are you trying to open an SSL connection to a non-SSL Puma?>

I have the gateway behind nginx proxy , any thoughts ?

**Comment by pglombardo** [comment]
Hi @wedowhateverwewant,

I sounds like SSL traffic is being forwarded to the gateway container.  It might be an nginx config issue.

Make sure you are [forwarding the nginx proxy headers](https://docs.pwpush.com/docs/proxies/) too.

**Comment by wedowhateverwewant** [comment]
Ive added those nginx proxy headers and the same errors is happening:
gateway-1  | 2024-09-26 17:28:20 +0000 HTTP parse error, malformed request: #<Puma::HttpParserError: Invalid HTTP format, parsing fails. Are you trying to open an SSL connection to a non-SSL Puma?>
gateway-1  | 2024-09-26 17:29:50 +0000 HTTP parse error, malformed request: #<Puma::HttpParserError: Invalid HTTP format, parsing fails. Are you trying to open an SSL connection to a non-SSL Puma?>

honestly not sure whats happening

**Comment by pglombardo** [comment]
Hey @wedowhateverwewant - did you ever find what was causing this?

**Comment by wedowhateverwewant** [comment]
Hi yes I did figure it out, turns out it wasn't an issue with Password Pusher or PassowrdPusher gateway, my proxy was passing the traffic as https which I changed to http but with this change I kept going back and forth like an idiot as it was not working turns out the firewall rule I put in place earlier to allow port 5101 from my proxy to password pusher gateway was never deployed. so user error , haha

**Comment by wedowhateverwewant** [comment]
oh also, I didnt add the advanced proxy settings https://docs.pwpush.com/docs/proxies/ , and it works just fine without them.

**Comment by pglombardo** [comment]
Excellent - that's great to know as I've seen this pop up in a few other places.
