### ISSUE TITLE
OpenAPI Document for API

### ISSUE THREAD

**Issue by Viajaz** [pglombardo/PasswordPusher#2571]
## 🚀 Feature Request

Publish an [OpenAPI 3.1 Document](https://www.openapis.org/) for the [PasswordPusher API](https://pwpush.com/api/).

## 🔈 Motivation

OpenAPI Documents for APIs are useful to developers and security testers. This can allow tools to rapidly adapt to various APIs, whether to perform automatic code scaffolding (e.g., generating client SDKs or server stubs) or to establish a scope for security testing (e.g., Dynamic Application Security Testing). It's can also be used to rapidly introduce developers to the API within tools like Postman, Insomnia etc.

## 🛰 Alternatives

Whilst one could be manually written and maintained (the API is simple enough and I was considering doing this myself) options such as the [rswag](https://github.com/rswag/rswag) gem exist to automate the process within Rails.

**Comment by pglombardo** [comment]
Hi @Viajaz - the project uses [apipie](https://github.com/Apipie/apipie-rails?tab=readme-ov-file#static-swagger-openapi-20-files) which can export an OpenAPI document.  It seems [only OpenAPI 2.0 is supported](https://github.com/Apipie/apipie-rails?tab=readme-ov-file#known-limitations-of-the-current-implementation).

[schema_swagger_form_data.json](https://github.com/user-attachments/files/17270813/schema_swagger_form_data.json)

I should probably add this to the documentation...

**Comment by pglombardo** [comment]
I create this too sometime back and just updated it now.   I'll add these to documentation this week:

https://www.postman.com/spaceflight-operator-13153338/password-pusher/overview

**Comment by pglombardo** [comment]
Hi @Viajaz - I'll close this out but let me know if I missed anything.  Thanks!
