### ISSUE TITLE
max file upload 

### ISSUE THREAD

**Issue by wedowhateverwewant** [pglombardo/PasswordPusher#2580]
## Checklist

- [ x] I've searched the project's [`issues`](https://github.com/pglombardo/PasswordPusher/issues?q=is%3Aissue).
- [ x] I've searched the project's [`discussions`](https://github.com/pglombardo/PasswordPusher/discussions).

## ❓ Question

I have it set so max file upload is  PWP__FILES__MAX_FILE_UPLOADS=5 

yet when I try to upload 5 files it does not work it kicks back to default files page but if do 4 files it works fine. is this normal behavior?

**Comment by pglombardo** [comment]
Hi @wedowhateverwewant - thanks for reporting - that sounds like a bug.  I'll try to validate this myself before EOD tomorrow.

**Comment by pglombardo** [comment]
Hi @wedowhateverwewant - This was an odd issue but is fixed now in [v1.45.11](https://github.com/pglombardo/PasswordPusher/releases/tag/v1.45.11).   Thanks for reporting!

Could you try out that version and confirm that it's fixed for you now?

**Comment by wedowhateverwewant** [comment]
Hi,

I can confirm that the upload issue is fixed, I was able to upload 5 files and access them via the push link.

**Comment by pglombardo** [comment]
Excellent.  Thanks for reporting the issue!
