### ISSUE TITLE
Typo in documentation image for Requests

### ISSUE THREAD

**Issue by reggatur** [pglombardo/PasswordPusher#2587]
## 🐛 Bug Report

In the documentation for Requests under What Do End Users See, the images contain this text:
LAW FIRM
Put You Tagline Here

It should read "Your"

## 🔬 How To Reproduce

1. ...

### Environment

Where are you running/using Password Pusher?

- [x] pwpush.com
- [ ] Docker Image
  - [ ] pwpush
  - [ ] Custom image
- [ ] Heroku
- [ ] Digital Ocean
  - [ ] App Platform
  - [ ] Kubernetes Service
- [ ] Microsoft Azure
  - [ ] App Service
  - [ ] Container Instances (ACI)
  - [ ] Kubernetes Service (AKS)
- [ ] Google Cloud
  - [ ] App Engine
  - [ ] Cloud Run
  - [ ] Kubernetes Engine
- [ ] AWS
  - [ ] Elastic Container Service (ECS)
  - [ ] Kubernetes Service (AKS)
- [ ] Source Code
- [ ] Other (please specify)

If applicable, what version of Password Pusher?

## 📈 Expected behavior

The image should appear with the word, Your, not the word, You

## 📎 Additional context

Lawyers are picky about misspellings!

**Comment by pglombardo** [comment]
Hi @reggatur - you are 100% correct.  I got those logos from a free Mac app and the mis-spelling was already there.  I thought it was funny so I just used them.  

When I get a chance, I'll change those to Acme Corp or something.  Thanks for reporting but this one was intended (for now). 😉

**Comment by pglombardo** [comment]
BTW what are your impressions with Requests?  Any issues?

**Comment by reggatur** [comment]
Thanks for asking for feedback. Responding is the least I can do short of subscribing. Speaking of subscribing, I think the price points are a bit high. You might get many more Premium subscribers at $6 per month, a point at which people don't need to think much about the cost.

#1  I did find a real bug:
I put it in Github. With my dark theme, the Request text is white on white, visible only if highlighted with the mouse.

#2  As for other feedback, the Autodetect button made me stop and think. I love the Web design book, Don't Make Me Think. First I was thinking, "What is there to Autodetect?" Then after clicking I thought, "Oh, language." Then, "Hmmm, how can a URL be in another language?" Maybe I am just hopelessly Anglo-centric.

#3  For usability, on the Response Retrieval page, I'd put The Request and The Response (dropping Recipient's) near the top of the page and the other unimportant :-) stuff lower down.

#4  Some of the Audit Log items confused me.
a. For the second (green) item, "Successful view *of Request* on..." would be clearer.
b. For the third (blue) item,  what? What anonymous person or agent received the Response? I expected the Response to be received only by me, the Requestor, in my Wells Anderson account.
c. For the fourth (orange) item, who tried to view the Response? Wasn't me!

FYI, I used the Brave browser to send the Request and the Firefox browser on the same machine to receive and respond to the Request.

Oh, and I get it about the humor of "you" instead of "your." That said, lawyers don't tend to think typos are funny. I used to have a lot riding on my flyspecking of documents for any tiny error that could be disastrous. Obviously, that's not an issue here, and yet the lawyer's "muscle memory" is still triggered: "OMG! A typo! The author must be an untrustworthy idiot." That wasn't my response, mind you, but I was mildly concerned that lawyers, one of your target markets, would be put off by it.

All of this feedback is intended as a way to show my appreciation for your putting out there a fine service, far better than the competition (I'm looking at you, www.onetimesecret.com).

Thank you!

Wells H. Anderson, J.D., CEO
SecureMyFirm Inc.
952.922.1120
https://www.securemyfirm.com
Protecting you from computer disasters

**Comment by pglombardo** [comment]
Excellent feedback!  Let me work through it and I'll post back soon.
