### ISSUE TITLE
Request dialog shows white on white text when using dark theme

### ISSUE THREAD

**Issue by reggatur** [pglombardo/PasswordPusher#2592]
## 🐛 Bug Report

Request dialog shows white on white text when using dark theme

## 🔬 How To Reproduce

1. ...

### Environment

Where are you running/using Password Pusher?

- [x] pwpush.com
- [ ] Docker Image
  - [ ] pwpush
  - [ ] Custom image
- [ ] Heroku
- [ ] Digital Ocean
  - [ ] App Platform
  - [ ] Kubernetes Service
- [ ] Microsoft Azure
  - [ ] App Service
  - [ ] Container Instances (ACI)
  - [ ] Kubernetes Service (AKS)
- [ ] Google Cloud
  - [ ] App Engine
  - [ ] Cloud Run
  - [ ] Kubernetes Engine
- [ ] AWS
  - [ ] Elastic Container Service (ECS)
  - [ ] Kubernetes Service (AKS)
- [ ] Source Code
- [ ] Other (please specify)

If applicable, what version of Password Pusher?

### Screenshots

![001590_A4](https://github.com/user-attachments/assets/4fca7780-04c8-44cf-bea8-ee53474e4fb9)

## 📎 Additional context

Brave browser

**Comment by reggatur** [comment]
Hi Peter,

Yes, dark mode is working great. Thank you.

Another suggestion:  Delete:  
"and will be in touch with you soon"
from what the Responder sees upon opening the secret link.
The Requestor typically is waiting for a response and is not expecting to have to re-contact the Responder, who, after all, is supposed to respond.

Another suggestion:  We Pwpush users are used to links that expire immediately upon opening to prevent attacker-in-the-middle from intercepting an email and opening the link. Can there be an option for the Response to expire immediately upon retrieving it by the Requestor? Now that I think about it, I don't think that is even how it works. Maybe no one can see the Response except the Requestor through the Requestor's account. If that is so, maybe it is worth explaining that somewhere. We users are pretty paranoid about passwords getting exposed. It would be good to be reassured that when someone sends us a password in response to a Request, no one else will be able to see it (without, of course, compromising our computer or our Pwpush account).

Oh, and is there any way for the Requestor to receive an email or a text notification when the Responder has responded, short of opening Pwpush, or maybe if Pwpush is logged in, a desktop or mobile notification? Maybe these are Pro features?

Wells H. Anderson, J.D., CEO
SecureMyFirm Inc.
952.922.1120
https://www.securemyfirm.com
Protecting you from computer disasters

**Comment by pglombardo** [comment]
This is excellent feedback @reggatur!  I'll be following up with this over the weekend and should have some changes out soon.

**Comment by pglombardo** [comment]
Hi @reggatur - late update but email notifications for requests are out - you've probably have already seen this.

> "and will be in touch with you soon"

This text will be changed soon.

> Maybe no one can see the Response except the Requestor through the Requestor's account. If that is so, maybe it is worth explaining that somewhere. 

I've filed an issue to better document this and make it a bit clearer.

**Comment by pglombardo** [comment]
Since the original issue is resolved here I'll close this issue out.

On the other updates, I'll likely post an update here once the changes go out!

Thanks @reggatur!  Happy holidays!
