### ISSUE TITLE
Trnslation missing on login and logout

### ISSUE THREAD

**Issue by ecoutinho** [pglombardo/PasswordPusher#2621]
## 🐛 Bug Report

On a local instalation using docker image 1.46.1, whenever I login and logout, I get the following error at the top:

- Translation missing. Options considered were: - pt-PT.devise.sessions.user.signed_in - pt-PT.devise.sessions.signed_in 
- Translation missing. Options considered were: - pt-PT.devise.sessions.user.signed_out - pt-PT.devise.sessions.signed_out 

## 🔬 How To Reproduce

1. Run a local docker image.
2. Create an account.
3. Login

### Environment

Where are you running/using Password Pusher?

- [x] Docker Image
  - [x] pwpush

If applicable, what version of Password Pusher? 1.46.1

### Screenshots

<img width="867" alt="Screenshot 2024-10-15 143838" src="https://github.com/user-attachments/assets/e864f8bf-f2e3-44c8-855f-998b9a64244b">

## 📈 Expected behavior

If there is no translation, an English message would be preferred to the error message.

## 📎 Additional context

How can I contribute to the translation?

**Comment by pglombardo** [comment]
Hi @ecoutinho - my apologies that I didn't get to respond to your email yet either.  It's been a crazy couple days.  I believe I should have this fixed in the next release.  I'll test again and update once it's out.

**Comment by ecoutinho** [comment]
Hi Peter, thanks for looking into it!

**Comment by pglombardo** [comment]
This should be fixed in [v1.46.2](https://github.com/pglombardo/PasswordPusher/releases/tag/v1.46.2) which is building now.  I'll close this out but if you see any remaining issue, let me know!

Thanks for reporting!
