### ISSUE TITLE
Set default language with environment variable

### ISSUE THREAD

**Issue by C4ArtZ** [pglombardo/PasswordPusher#267]
Hi!

Would nice to set the default language from within the environment variables.
The variable could be called DEFAULT_LANGUAGE and accept two letter ISO 639-1 codes (eg, de/en/es).

Thank you for your great work! :)

**Comment by pglombardo** [comment]
That's a good and fair request.  I'll see if I can add this soon.

**Comment by pglombardo** [comment]
Thanks for requesting this @C4ArtZ!  The code is complete.  I'll be pushing to pwpush.com and building new containers before Monday.
