### ISSUE TITLE
Expose PostgreSQL database, user and password with environment variables

### ISSUE THREAD

**Issue by C4ArtZ** [pglombardo/PasswordPusher#269]
The current approach is to edit the dockerfile, which is kind of unusual. [See here](https://github.com/pglombardo/PasswordPusher/tree/master/containers/docker#pwpush-postgres)

Is there a security reason for not using environment variables? Or is DATABASE_URL intended to be used here?

**Comment by pglombardo** [comment]
`DATABASE_URL` environment variable is the suggested route.

> You can either configure your PostgreSQL server to use these credentials or override the environment var in the command line:
>
> `docker run -d -p "5100:5100" -e "DATABASE_URL=postgresql://user:passwd@postgres:5432/my_db" pglombardo/pwpush-postgres:release`

**Comment by pglombardo** [comment]
Those docs should eventually be updated/revised to make them a bit more readable with the most popular strategies first.

**Comment by C4ArtZ** [comment]
DATABASE_URL doesn't seem to work with an unmodified container. I'm thinking it might be because it's hardcoded in the dockerfile.

**Comment by pglombardo** [comment]
Ok that is good news.  I'll close this issue then.  If anything remains, feel free to update here or create a new issue.
