### ISSUE TITLE
"ActiveRecord::ValueTooLong - Mysql2::Error: Data too long" when posting secret over 40 000 characters

### ISSUE THREAD

**Issue by jeffdesc** [pglombardo/PasswordPusher#270]
Hey

We launched a version of PasswordPusher and we are noticing internally that secrets over 40 000 characters have an issue. After investigating it seems like the issue starts happening at 47 522 characters.

The error log: 
```
F, [2021-11-25T08:49:50.295215 #11] FATAL -- : [494652e6-4e6e-42d8-a663-1bc45a472117]
[494652e6-4e6e-42d8-a663-1bc45a472117] ActiveRecord::ValueTooLong (Mysql2::Error: Data too long for column 'payload_ciphertext' at row 1):
[494652e6-4e6e-42d8-a663-1bc45a472117]
[494652e6-4e6e-42d8-a663-1bc45a472117] app/controllers/passwords_controller.rb:98:in `block in create'
[494652e6-4e6e-42d8-a663-1bc45a472117] app/controllers/passwords_controller.rb:97:in `create'
```

Backend is MySQL and this is the explain of the table:
```
mysql> explain table passwords\G
*************************** 1. row ***************************
           id: 1
  select_type: SIMPLE
        table: passwords
   partitions: NULL
         type: ALL
possible_keys: NULL
          key: NULL
      key_len: NULL
          ref: NULL
         rows: 41
     filtered: 100.00
        Extra: NULL
1 row in set, 1 warning (0.00 sec)
```

What can be done to mitigate this issue, so we can have secrets that are over 40 000 characters?

Kind regards
Jeffrey

**Comment by pglombardo** [comment]
This might be a MySQL specific issue.  The `payload_ciphertext` field is type `text` which can hold megabytes so something is amiss.

Can you do a describe of that table to see the field types for each column?

**Comment by pglombardo** [comment]
Apparently, MySQL will default to the small text (64kb limit) column type unless its specifically called out.

https://stackoverflow.com/questions/4443477/rails-3-migration-with-longtext

As for the migration, I might have to do a conditional check (`if MysQL`) to specify a column limit which will then create the appropriate column type.  I'll give this some thought.

To fix your issue immediately, you can manually alter that column type to `mediumtext` which has a limit of 16MB or `longtext` with a 4GB limit.

I may be able to figure out an automatic fix with an update but not sure on ETA yet.

**Comment by jeffdesc** [comment]
Thanks for the debugging thus far. The describe was in the initial post (it outputs the same).
I'll check if I can alter the database (if we have a need), it would be nice if it could be patched officially.

Thanks again, @pglombardo!

**Comment by pglombardo** [comment]
This has been fixed.  The fix happens automatically once you move to the latest container.  Docker tag `1.11.3` is building now.

Once it's done, I'll test some more and if all goes well point update the `release` tag to point there.

Let me know once you get a chance to update.

**Comment by pglombardo** [comment]
The release tag now points to `1.11.3` which includes this fix.  I hope all is working well for you know.  If any issues remain, please let me know.
