### ISSUE TITLE
How to update Set an Admin in azure

### ISSUE THREAD

**Issue by BNWEIN** [pglombardo/PasswordPusher#2719]
## Checklist

- [X] I've searched the project's [`issues`](https://github.com/pglombardo/PasswordPusher/issues?q=is%3Aissue).
- [X] I've searched the project's [`discussions`](https://github.com/pglombardo/PasswordPusher/discussions).

## ❓ Question

Could anyone tell me how i update our Azure instance to the latest version by any chance?

**Comment by BNWEIN** [comment]
ok scrap that. I have managed to update, but cannot for the life of me work out how to set an admin. Unsure how to connect to the application console?  

I have bash access to the VM running, but from there, i am not sure how to run the command:  PasswordPusher.grant_system_admin!('user@example.com')

**Comment by BNWEIN** [comment]
So my hunch here is that SSH is not enabled on the container. Any chance we can have a "Custom" version where we have an environmental variable that allows us to enable/disable SSH? I think if we had that, i can SSH to it from the Kudu proxy using 

ssh -p 2222 root@localhost
password is Docker!

**Comment by BNWEIN** [comment]
Ugh

I wish this was in the full docs:

https://github.com/pglombardo/PasswordPusher/issues/2405

Just in case anyone else needs help on it, that solution is far simpler! 

Case closed!

**Comment by pglombardo** [comment]
Good suggestion!  I just added those instructions to the [Admin dashboard documentation page](https://docs.pwpush.com/docs/admin-dashboard/#alternative-direct-database-access).

Thanks for pointing that out!
