### ISSUE TITLE
Feature Request: Password protect pushes

### ISSUE THREAD

**Issue by pglombardo** [pglombardo/PasswordPusher#273]
Incoming feature request from a few sources in the past.  Most recent from yesteday.

This would include the ability to set a password for a push being that the push wouldn't be visible until the right password is given.

Unknown: Unlimited tries or lock push after a certain failed attempts?

The URL is secret to random brute forcing is unlikely...

**Comment by nilldot** [comment]
Hi,

Any traction on this one ? The current functionality is great, but password protection is really nice feature worth adding.
Thank you!

**Comment by pglombardo** [comment]
I have to give some thought on how to implement in regards to security.  It could be implemented entirely in Javascript or a two step process with an authentication cookie.

I agree we need this feature though.  Let's see if I can get on it in my next coding blitz.

**Comment by pglombardo** [comment]
Hi @nilldot - The support for per push passphrases has been added in [release v1.28.0](https://github.com/pglombardo/PasswordPusher/releases/tag/v1.28.0).  🎉 

Please try it out - if you have any issues let me know and I'll re-open this issue.
