### ISSUE TITLE
Dutch translation error

### ISSUE THREAD

**Issue by xaetacore** [pglombardo/PasswordPusher#2755]
## 🔬 How To Reproduce

1. Set the language to Dutch
2. Generate and push a password
3. Translation error is in the string "Deze geheime link and alle inhoud" "and" has to be "en"

### Code sample

```
msgid "This secret link and all content will be deleted in"
msgstr "Deze geheime link and alle inhoud wordt verwijderd in"
```
### Environment

Where are you running/using Password Pusher?

- [X] Docker Image
  - [X] pwpush

If applicable, what version of Password Pusher?

v1.48.1

### Screenshots

![vivaldi_XHDzTetHnT](https://github.com/user-attachments/assets/730e805e-fddc-460f-a925-76fae067bf94)

## 📈 Expected behavior

Translation should be "Deze geheime link en alle inhoud wordt verwijderd in"

**Comment by pglombardo** [comment]
HI @xaetacore - thanks for pointing this out!  I've updated the translation in the backend and this change will go out in the next few days or so!

![Screenshot 2024-11-13 at 09 12 25](https://github.com/user-attachments/assets/760493bb-833b-4b84-a062-9745816847fb)

I'll close out this issue but if anything remains, please let me know!
