### ISSUE TITLE
Authentication via Proxies Does Not Appear to Work

### ISSUE THREAD

**Issue by a-morton** [pglombardo/PasswordPusher#2766]
Hi,

We are running pwpush on docker latest with mariadb as outlined in the pre-created compose file.  Everything works until we put pwpush behind a proxy.  After this signups and logins do not work.  We have tested with both nginx following the YouTube guide in the documentation and with our own proxy.  both currently come out with links that don't seem to action requests.

We also tried the proxy environment variable from the proxies section in the documentation: PWP__OVERRIDE_BASE_URL.

https://docs.pwpush.com/docs/proxies/

## 🔬 How To Reproduce

1. ...

### Code sample

http://YOURDOMAIN.com - working - non-proxied

https://YOURPROXIEDDOMAIN.com - not working - proxied

### Environment

Where are you running/using Password Pusher?

- [ ] pwpush.com
- [x ] Docker Image
  - [ x] pwpush
  - [ ] Custom image
- [ ] Heroku
- [ ] Digital Ocean
  - [ ] App Platform
  - [ ] Kubernetes Service
- [ ] Microsoft Azure
  - [ ] App Service
  - [ ] Container Instances (ACI)
  - [ ] Kubernetes Service (AKS)
- [ ] Google Cloud
  - [ ] App Engine
  - [ ] Cloud Run
  - [ ] Kubernetes Engine
- [ ] AWS
  - [ ] Elastic Container Service (ECS)
  - [ ] Kubernetes Service (AKS)
- [ ] Source Code
- [ ] Other (please specify)

If applicable, what version of Password Pusher?
v1.46.3

## 📈 Expected behavior

We are to use the login and signup links behind a proxy

**Comment by pglombardo** [comment]
Hi @a-morton,

> both currently come out with links that don't seem to action requests.

Could you explain what you are seeing exactly when running behind a proxy?

**Comment by pglombardo** [comment]
Hi @a-morton - could you check the browser console for any errors?  I suspect something may be getting blocked.

**Comment by a-morton** [comment]
@pglombardo , Yes, you appear to be right.  The return seems to be in http.
![ConsoleError](https://github.com/user-attachments/assets/bfa18cec-780e-4839-8b25-ae387b0000f8)

**Comment by pglombardo** [comment]
Ok that's great.  Potential fixes are:

1. Make sure the proxy is [passing the X-Forwarded-* headers](https://docs.pwpush.com/docs/proxies/#required-proxy-headers) to the backend application (pwpush)
2. If that doesn't work (number 1 should be the fix but if not...) try setting `FORCE_SSL` environment for the pwpush container.

One of those should definitely be the fix.

**Comment by a-morton** [comment]
@pglombardo thanks!  That did resolve it: at least on the main shared frontend of a pfSense proxy enabling forwardfor worked.  I think with the NGINX proxy testing the first time my variables may have been off: I copied the PWP__OVERRIDE_BASE_URL omitting https:// in the value field.  I realise that should be there from your settings document here in GitHub.

Thanks a lot for your assistance, I was sure I'd tested X-Forwarded headers in both.  Keen to see this project grow!

**Comment by pglombardo** [comment]
Excellent - that's great to hear!

I'll close out this issue but if anything else comes up - feel free to ping me anytime.
