### ISSUE TITLE
How to install on Azure?

### ISSUE THREAD

**Issue by alig26** [pglombardo/PasswordPusher#277]
Does anyone have the documentation on how to install this on Azure? The blog site by Craig McLaren doesn't exist anymore.

Thanks

**Comment by pglombardo** [comment]
At least for me, I haven't ever deployed to Azure although I know they have fair documentation on how to deploy containers and container sets.

If it helps, we have a docker-compose file [available here](https://github.com/pglombardo/PasswordPusher/blob/master/containers/docker/pwpush-postgres/docker-compose.yaml) that Azure should be able to import as well.

Issue #175 also covered some Azure details.

Hopefully someone else will jump in with some Azure experience.

I'll remove the link to the now removed blog post soon.

**Comment by alig26** [comment]
Thanks, we figured it out, we were able to import the docker into Azure and it worked. 
Thank you

**Comment by jlucgauthier** [comment]
Hi, it could be a bit late, but you could also use the Azure App Service. It's quite simple and you can also link your repo for simple deployment. Docker his easy too, but if your looking at the easiest way, App Service -from my experience, is the way to go.

_P.N. there's many ways to get to a point, what's most important... it's using the one your the most confortable with!_

**Comment by pglombardo** [comment]
Thanks for pointing this out.  I agree and would love if someone would contribute documentation on this.  I tried the App Service once but couldn't get it to work and haven't had a chance to revisit it yet.

There are a good number of Azure users.  Not having documentation on the how isn't ideal for this project.

**Comment by Ramses26** [comment]
We tried the App Service route, but ended up using it as an Azure Docker, App Service would probably be better since we can easily update it by linking the repo. Could you share how you did it, and anyone likes can publish our steps for future reference for everyone.

**Comment by jlucgauthier** [comment]
Hi, yes I can. I could also get you an ARM model or Bicep file. I'll give you the info as soons as I can and you'll be able to let me know what you think about it.

**Comment by jlucgauthier** [comment]
@Ramses26, did you use the Docker option via App Service or Azure Docker -the real deal?! The App Service let you use a container based on Docker. I'm using the firts option, as I see it, it's the better of both wolrd. I'll get you posted.

**Comment by jlucgauthier** [comment]
To use PasswordPusher on Azure via App Service, there's a few options you got and should look at:

1. Use your own domain name -optional.
2. Add your own certificate -optional and linked with the previous point..
3. How many people could/would use the app -optimize the cost.
4. From container or code source.

The firts step is to create, if you don't already have one, an **App Service plan**. I suggest the Free Tier (F1) for Dev/Test if you would like to get around and test it first. This plan, doesn't have the personal domain or SSL options and you'll use the default Azure service DNS and SSL certificate -that's find for dev/test.

If you already have an App Service Plan, you can go to the **App Service section**.

### App Service Plan
1. In your Azure Resource Group, use the **+ Create** option. 
![image](https://user-images.githubusercontent.com/34319312/156892327-777cda6c-42eb-4bbd-9d86-5982df174ad2.png)
2. In the **Create resource** window, search for **App Service Plan** and select it. You'll then click on **Create**. 
![image](https://user-images.githubusercontent.com/34319312/156892423-3e6e7517-f34f-44f8-9ccb-11bcb835a610.png)
3. Type in your service plan name, stay with Linux for the OS, choose your region -not every region give access to the free tier option you'll maybe have the change it acordingly. In Pricing Tier, click on **Change** and go to **Dev/Test** and select the **F1 plan** and hit **Apply**.
5. Click on **Review + create** and then **Create**.
![image](https://user-images.githubusercontent.com/34319312/156892693-9a1cf808-08ee-4ad1-9783-9746808499f4.png)
6. Once finished, you'll have acces to your new plan.

### App Service - w/Docker
1. Go back to your resource group and use the **+ Create** option. ![image](https://user-images.githubusercontent.com/34319312/156892327-777cda6c-42eb-4bbd-9d86-5982df174ad2.png)
2. In the **Create resource** window, click on Web App in the **Popular products** list and then click on **Create**. 
![image](https://user-images.githubusercontent.com/34319312/156898573-fa399036-f8eb-45cf-8df4-1eba1180d6a4.png)
3. Enter the name of your app, select **Docker Container**, use Linux, make sure the region and Linux plan are correct an click on **Next Docker**. 
![image](https://user-images.githubusercontent.com/34319312/156898636-720d8cf7-11ac-4989-ab7c-5c14fc433c14.png)
4. Use **Single Container** for options and **Docker Hub** for the image source. **Public** should already be selected for **Access Type** and for Image an tag enter **pglombardo/pwpush-ephemeral:latest**. Click on **Review + create** and then **Create**. 
![image](https://user-images.githubusercontent.com/34319312/156898726-e14ab01f-ec25-46ea-867b-3207017e3dc6.png)
5. When the resource is created, you'll see on the right side, the URL of your application. You can also use the **Browse** option in the menu bar. 
![image](https://user-images.githubusercontent.com/34319312/156898837-c7e18825-c582-428a-b0f2-42f33e4a6a94.png)
7. Wait for about 15 minutes before accessing the web site, even if the resource is functional, the deployment isn't finished yet. Go to the left panel and select **Deployment Center** and click on **Logs**. It's only when you get the confirmation that the application is ready to go! 
![image](https://user-images.githubusercontent.com/34319312/156898919-0e892cf3-7832-4060-9b47-01af2d3f30ed.png)

### Security Basic Best Practice
1. Disable FTP acces or set it to FTPS 
![image](https://user-images.githubusercontent.com/34319312/156899062-b3e4ff0d-2097-4386-b2e9-c5f68e09735a.png)
2. Use an identity provider -if you can. There's a few available: 
![image](https://user-images.githubusercontent.com/34319312/156899183-2d4fd3c8-d9d1-4f6b-bedd-b6078e495ba8.png)
3. Once selected, you'll need to configure app id, secret, etc. depending on the provider. ![image](https://user-images.githubusercontent.com/34319312/156899196-b5b9cbd7-6031-4a22-a51d-213d8b0ccf11.png)

I'll add the **App Service w/Code** version soon.

BTW, my first language is french so if there's errors or misspelled words, feel free to correct me!

**Comment by Rameez96** [comment]
How can I deploy it on EC2 AWS?

**Comment by pglombardo** [comment]
Documentation on how to deploy a docker container to Amazon LightSail or ECS is here:
https://aws.amazon.com/getting-started/guides/deploy-webapp-decision/?pg=gs&sec=lyfa

Added #391 to document the AWS process.

**Comment by jnhrv** [comment]
Hi, I love the tool - thank you @pglombardo - and I'm kinda new to Azure App Service and Docker things but managed to deploy the image to Azure App Service according to the instructions provided by @jlucgauthier . However, I would like to customize our instance and change CSS and logo images directly in the docker image. Does anyone know how to access the image in the Azure App Service Docker container and replace the files? I'm not sure what to google for and if it is possible. Thank you!

**Comment by pglombardo** [comment]
Hi @jnhrv!

Password Pusher supports rebranding out of the box.  See these links for info:

1. https://github.com/pglombardo/PasswordPusher/blob/master/Configuration.md
2.  [Rebranding details](https://github.com/pglombardo/PasswordPusher/blob/master/Configuration.md#rebranding)
3. If you need to customize beyond what's supported in branding, [see here](https://github.com/pglombardo/PasswordPusher/discussions/295).

Hopefully this helps.  Let me know if you have any issues.

**Comment by jgudmundson-RETSD** [comment]
I tweaked this during my deployment, but the instructions works well.  I just need it to be backed by a database.  
1. docker image and tag needs to be changed to "pglombardo/pwpush-postgres:latest"
2. Create "Azure Database for PostgreSQL flexible server"
3. app service\configuration\app settings.  add app setting.  Name: "DATABASE_URL" Value: "postgresql://REPLACEDBUSER:REPLCEDBPassword@REPLACEPGSERVERURL.postgres.database.azure.com:5432/REPLACEWITHDATABASE"

**Comment by Manu-H** [comment]
Hey!

I also deployed Password Pusher to an Azure WebAPp thanks to the input from @jlucgauthier
Everything works fine.

I'm just curious if its possible to change the "text" (from config/locales/localization.it.yml) if Password Pusher is deployed through Azure Web App?
I'd like to modify a few text settings...

Anyone an Idea?

Thanks!

**Comment by pglombardo** [comment]
Hi @Manu-H - I'll put a response into the issue you posted in #1439

**Comment by rafabiasotto** [comment]
Can I create the application by pulling from my repository and cloning it from yours? example: in the Full Image Name and Tag part I put myrepository/pwpush-ephemeral:latest

**Comment by pglombardo** [comment]
Hi @rafabiasotto - if you are building your own Docker containers and pushing them to your Docker Hub account - then yes.

Also a side note.  There is now a single universal Docker container ([pglombardo/pwpush](https://hub.docker.com/r/pglombardo/pwpush)).  See [here for info](https://github.com/pglombardo/PasswordPusher/wiki/How-to-migrate-to-the-Universal-Container).

**Comment by rafabiasotto** [comment]
Tks pglombardo for the answer, I need another help. I create a webapp with Identity Provider, but other users can´t access
<img width="196" alt="image" src="https://github.com/pglombardo/PasswordPusher/assets/119950050/b04d1260-1367-4546-af46-38a5290fd487">

How can I give this permissions the other user can view?

**Comment by pglombardo** [comment]
Hi @rafabiasotto - My Portuguese is poor but I believe that is a firewall message.  You may have to approve the URL with your company IT team.

This message is not from Password Pusher and is open by default (no blocking).

Let me know how it goes.

**Comment by jgudmundson-RETSD** [comment]
@rafabiasotto, to me that looks suspiciously like the image below. It's for Entra AD Application Consent (OAUTH permissions) control.
I'm with @pglombardo I don't think its related to pwpush, unless we recently got logins with OAUTH....  Which TBH would be handy.
https://learn.microsoft.com/en-us/entra/identity-platform/application-consent-experience
![image](https://github.com/pglombardo/PasswordPusher/assets/11094546/2b39ec27-6db1-4232-a42e-f52ad7328672)

**Comment by rafabiasotto** [comment]
I fogot to give admin consent. Thanks for help.

**Comment by az-pz** [comment]
I created an azure web app by using the docker image and mapping port 80 to 5100. I am attaching the ARM template for others to use. I am sure there are better ways to do it but I could get it  work only this way.
[template.json](https://github.com/pglombardo/PasswordPusher/files/13823666/template.json)

**Comment by BNWEIN** [comment]
I have been able to get it up and running on azure, but can't get it to connect to the postgres DB

@jgudmundson-RETSD dont suppose you have any additional info to share on the way you did that? 

under config > Application Settings > Connection Strings, i already had some values from when the resource was created (I created it with postgres)

I have tried also adding a new application setting:
"Database_URL" 
with a value of:
"postgresql://username:password@db-server.postgres.database.azure.com:5432/dbname"

However i am getting: 

2024-01-25T22:40:22.297Z ERROR - Container pwpushapp_1_ccdff39e didn't respond to HTTP pings on port: 5100, failing site start. See container logs for debugging.
2024-01-25T22:40:22.334Z INFO - Stopping site pwpushapp because it failed during startup.

**Comment by pglombardo** [comment]
Hi @BNWEIN,

> See container logs for debugging.

If you could post the container logs, that will tell us exactly where the issue is.

Two other things to make note of:

1. The [Guide to DATABASE_URL](https://github.com/pglombardo/PasswordPusher/wiki/Guide-to-DATABASE_URL) if needed
2. See #1602

**Comment by BNWEIN** [comment]
> Hi @BNWEIN,
> 
> > See container logs for debugging.
> 
> If you could post the container logs, that will tell us exactly where the issue is.
> 
> Two other things to make note of:
> 
> 1. The [Guide to DATABASE_URL](https://github.com/pglombardo/PasswordPusher/wiki/Guide-to-DATABASE_URL) if needed
> 2. See [Database hostnames with underscores are not supported #1602](https://github.com/pglombardo/PasswordPusher/issues/1602)

Thanks. I got this sorted by changing the network settings on the postgres server

**Comment by RafaelBiasotto** [comment]
Can I change the nome on footer: © 2023 Peter Giacomo Lombardo ?

**Comment by RafaelBiasotto** [comment]
@pglombardo we try to change theme but Isnt work

![MicrosoftTeams-image (6)](https://github.com/pglombardo/PasswordPusher/assets/154610968/14ed90ec-8040-419a-88e5-128c4f94f703)

And we can change this name bar
<img width="644" alt="image" src="https://github.com/pglombardo/PasswordPusher/assets/154610968/a85ec6cb-fb10-459e-ba31-030d5d37ad7d">

**Comment by pglombardo** [comment]
> @pglombardo Can I change the name on footer: © 2023 Peter Giacomo Lombardo ?

You can but that is the entirety of my compensation for this project.   😂   

If you want to change it, you can always fork the repo and build custom containers.  It's not configurable currently.  I have no strong feelings about it though.  Feel free.

> @pglombardo we try to change theme but Isnt work

Set the environment variable `PWP_PRECOMPILE=true` for the container.  That setting in `settings.yml` has a bug.

Make sure to read [this section](https://github.com/pglombardo/PasswordPusher/blob/master/Configuration.md#configuring-a-theme):

> Note: Precompiling all application assets for a new theme on container boot can add 30-90 seconds to the boot process (depending on the system). Make sure to allow this time in your health checks before declaring the container as unresponsive.

**Comment by LucasDouradoLinx** [comment]
@pglombardo we can change this name bar?

![image](https://github.com/pglombardo/PasswordPusher/assets/119966133/73ceea73-3a2e-40aa-9044-b67672ce68c0)

**Comment by Julian0o** [comment]
Hi there, im trying to host passwordpusher on Azure with persistent storage. A seperate "Azure Database for PostgreSQL flexible server" costs about 15 $ per month. Is there another way to do that? I tried to bin a storage account but i did not get it working. 

Has anybody get i working with persistent storage without paying extra fees for a PostgreSQL Server?

**Comment by pglombardo** [comment]
Hi @Julian0o - you could use the SQLite3 database backend as persistent storage if you mounted a persistent volume to `/opt/PasswordPusher/db`.  The default SQLite3 database file path is `/opt/PasswordPusher/db/db.sqlite3`.

Other users have done this.  See the [SQLite3 docs here](https://docs.pwpush.com/docs/database_url/).

Note though the SQLite3 isn't the best at concurrency so if you expect a lot of users, this will have it's limits.  But for light traffic it's fine.

**Comment by Julian0o** [comment]
> Hi @Julian0o - you could use the SQLite3 database backend as persistent storage if you mounted a persistent volume to `/opt/PasswordPusher/db`. The default SQLite3 database file path is `/opt/PasswordPusher/db/db.sqlite3`.
> 
> Other users have done this. See the [SQLite3 docs here](https://docs.pwpush.com/docs/database_url/).
> 
> Note though the SQLite3 isn't the best at concurrency so if you expect a lot of users, this will have it's limits. But for light traffic it's fine.

Thank you! I got it working. In Azure Web App you can use the /home Folder for persistent storage. All you have to do is set the following Environment Variables via Azure Web Interface:

DATABASE_URL
sqlite3:/home/db.sqlite3

WEBSITES_ENABLE_APP_SERVICE_STORAGE
true

I think we will use it for a max of 100 Passwords per day. Do you think sqlite will do this fine?

**Comment by pglombardo** [comment]
Excellent - I think 100 passwords/day should be fine.

**Comment by pglombardo** [comment]
Hi all - just an update here that a community user has graciously contributed [new Azure installation documentation](https://docs.pwpush.com/docs/installation/#microsoft-azure).

**Comment by Jr7468** [comment]
Hi there, I have pwpush deployed on Azure and I'm struggling to get an admin user added. I can't find a way to access the console to run the necessary commands.

**Comment by pglombardo** [comment]
Hi @Jr7468 - It seems more than a few users have trouble accessing an application console in Azure.  I just updated the Admin Dashboard docs with instructions on how to [mark a user via SQL](https://docs.pwpush.com/docs/admin-dashboard/#alternative-direct-database-access).

Related: https://github.com/pglombardo/PasswordPusher/issues/2719#issuecomment-2452264648
