### ISSUE TITLE
 `full_message': no implicit conversion of Symbol into Integer (TypeError) "Mail"

### ISSUE THREAD

**Issue by Mikael57fr** [pglombardo/PasswordPusher#2781]
Hello

I apologize for the English as I use the translation because I'm French.

I tried to configure the email part on my exchange server and on this configuration, impossible to make it work as you can see below.

I tried to disable auto authentication but it ends in enthentification failed.

can you help me.

Thanks
------------------------------------
The Mail subsystem SMTP configuration is:
----------
address: 132.140.160.16
port: 25
open_timeout: 10
read_timeout: 10
authentication: plain
user_name:xxx
password: xxx
openssl_verify_mode: none
enable_starttls_auto: true
----------

--> raise_delivery_errors is set to true in the configuration.  This will raise an error if the email fails to send.

--> Attempting to send a test email to xxx@xxxx...
--> ✅   It seems that the Email was accepted by the SMTP server!  Check destination inbox for the test email.

--> If you see an error, please paste this output into a GitHub issue for help.
  --> Make sure that no sensitive data is included.
  --> https://github.com/pglombardo/PasswordPusher/issues/new/choose

/opt/PasswordPusher/vendor/bundle/ruby/3.3.0/gems/irb-1.14.1/lib/irb.rb:1260:in `full_message': no implicit conversion of Symbol into Integer (TypeError)

      OpenSSL::SSL::SSLSocket.new socket, context
                                  ^^^^^^^^^^^^^^^

**Comment by pglombardo** [comment]
Hi @Mikael57fr - two questions:

1. which docker container version are you using?
2. Did this ever work or is it a new install?

**Comment by Mikael57fr** [comment]
Good evening.

Merco and sorry if I don't reply quickly, it's 9:30PM for me.

This is a new installation in a docker on Synology. Everything works except
the mail part.

Thanks

**Comment by pglombardo** [comment]
Hi @Mikael57fr - I suspect this has something to do with the TLS connection.

You might have to play with `smtp_starttls` and `smtp_enable_starttls_auto` in the [settings.yml file](https://github.com/pglombardo/PasswordPusher/blob/master/config/settings.yml#L749-L755).

These other issues/users had the same issue:

* https://github.com/pglombardo/PasswordPusher/issues/755#issuecomment-1429803307
* https://github.com/pglombardo/PasswordPusher/issues/982 <- specific to Office 365 SMTP

Could you look into the issues and potentially try toggling the above settings?  The answer should be in one or both of those issues above.

**Comment by Mikael57fr** [comment]
Hi
PWP__MAIL__SMTP_ENABLE_STARTTLS_AUTO=false
PWP__MAIL__SMTP_STARTTLS=true
PWP__MAIL__MAILER_SENDER="xxxxxxx" <xxxx@xxx.lu>

**/opt/PasswordPusher/vendor/bundle/ruby/3.3.0/gems/irb-1.14.1/lib/irb.rb:1260:in `full_message': 504 5.7.4 Unrecognized authentication type (Net::SMTPAuthenticationError)**

PWP__MAIL__SMTP_ENABLE_STARTTLS_AUTO=false
PWP__MAIL__SMTP_STARTTLS=false
PWP__MAIL__MAILER_SENDER="xxxxxxx" <xxxx@xxx.lu>

**/opt/PasswordPusher/vendor/bundle/ruby/3.3.0/gems/irb-1.14.1/lib/irb.rb:1260:in `full_message': 504 5.7.4 Unrecognized authentication type (Net::SMTPAuthenticationError)**

PWP__MAIL__SMTP_ENABLE_STARTTLS_AUTO=true
PWP__MAIL__SMTP_STARTTLS=false
PWP__MAIL__MAILER_SENDER="xxxxxxx" <xxxx@xxx.lu>

**/opt/PasswordPusher/vendor/bundle/ruby/3.3.0/gems/irb-1.14.1/lib/irb.rb:1260:in `full_message': no implicit conversion of Symbol into Integer (TypeError)

      OpenSSL::SSL::SSLSocket.new socket, context
                                  ^^^^^^^^^^^^^^^**

PWP__MAIL__SMTP_ENABLE_STARTTLS_AUTO=true
PWP__MAIL__SMTP_STARTTLS=true
PWP__MAIL__MAILER_SENDER="xxxxxxx" <xxxx@xxx.lu>

**/opt/PasswordPusher/vendor/bundle/ruby/3.3.0/gems/irb-1.14.1/lib/irb.rb:1260:in `full_message': no implicit conversion of Symbol into Integer (TypeError)

      OpenSSL::SSL::SSLSocket.new socket, context
                                  ^^^^^^^^^^^^^^^**

Thanks, I've tried all the combinations and it doesn't work. Sorry to waste your time.

**Comment by pglombardo** [comment]
Not a problem at all.  The first two with `Net::SMTPAuthenticationError` is progress.  It made it past the TLS problem and then had an authentication problem.  

I would focus on one of the first two configurations you posted.  Then try to resolve the authentication issue.  

Does your mail server require authentication?

Should auth type be 'plain'?  

The documentation for possible values are here: https://docs.pwpush.com/docs/self-hosted-configuration/

**Comment by Mikael57fr** [comment]
Yesssssssssssssssssss

Thank you. I appreciate people like you. I concentrated on the login/password part.

Unlike my other dockers where I can send a mail with an anonymous sender mail. Here I need a mail that exists.

So exchange 2016 port 25 in anonymous.

I need 
PWP__MAIL__SMTP_ENABLE_STARTTLS_AUTO=true
PWP__MAIL__SMTP_STARTTLS=false
PWP__MAIL__MAILER_SENDER="existing mail”

Thank you very much for your software

**Comment by pglombardo** [comment]
Excellent - that's great to hear and thanks for the nice words!  I'll close this out but if anything else comes up feel free to ping me anytime.
