### ISSUE TITLE
Lockout Feature After Multiple Login Attempts

### ISSUE THREAD

**Issue by jaychinut** [pglombardo/PasswordPusher#2798]
## Checklist

- [x ] I've searched the project's [`issues`](https://github.com/pglombardo/PasswordPusher/issues?q=is%3Aissue).
- [ x] I've searched the project's [`discussions`](https://github.com/pglombardo/PasswordPusher/discussions).

## ❓ Question

I am writing to inquire about the configuration options available for setting a maximum number of failed login attempts, after which a user would be locked out either for a specified period or until an administrator unlocks the account. Specifically, I would like to know:

Is there a current default setting for the maximum number of failed login attempts before a user is locked out?
Can this setting be configured via environment variables or through the Admin Dashboard?
What are the available options for the lockout mechanism (e.g., temporary lockout period vs. admin intervention)?

## 📎 Additional context

To provide some context, I have attempted to log into a user account with the incorrect password 11 times, yet the account has not been locked out. This raises a security concern, as a brute force attacker could potentially try millions of passwords without being stopped.  I am running my own instance of the pwpush app.

**Comment by pglombardo** [comment]
Hi @jaychinut,

This isn't configurable currently but I'll point out what protections exist today.

1. There is a built in rate limiter that throttles log in attempts [here](https://github.com/pglombardo/PasswordPusher/blob/master/config/initializers/rack_attack.rb#L49-L80).  So trying millions of passwords would take years theoretically.
2. The authentication system [will lock the account after 20 failed attempts](https://github.com/pglombardo/PasswordPusher/blob/master/config/initializers/devise.rb#L196-L214) which is a bit high really.

I think we should reduce that to 10 failed attempts no?  I should also have this documented somewhere.

**Comment by pglombardo** [comment]
Hi @jaychinut - this has been released in [v1.49.1](https://github.com/pglombardo/PasswordPusher/releases/tag/v1.49.1).  Thanks for pointing this out!

https://x.com/pwpush/status/1862504308937199850
