### ISSUE TITLE
Change subdomain

### ISSUE THREAD

**Issue by vaindil** [pglombardo/PasswordPusher#28]
Is it possible to specify a subdomain for this to run on? I don't want it to run on my site's root, but I'm not too familiar with Ruby to be able to change this myself.

**Comment by pglombardo** [comment]
That should be possible - depends largely on how you are hosting your existing app though.

* Are you using Apache with virtual hosts or nginx?
* Is your current app Ruby based?

Let me know how your current site is setup and I'll see if I can help out.

**Comment by vaindil** [comment]
I'm running Apache with virtual hosts. I don't have an existing app; I'm planning to install it using the instructions in the readme file. So I guess that means I'll be using Ruby.

**Comment by pglombardo** [comment]
Good - with apache vhosts, you can setup a vhost for every app you host.  So you would have one for your main site and another at `ServerName pwpush.mysite.com`.

This guide may help: https://www.digitalocean.com/community/tutorials/how-to-setup-a-rails-4-app-with-apache-and-passenger-on-centos-6

**Comment by vaindil** [comment]
Ah, beautiful, got it all set. Thank you, I appreciate it!
