### ISSUE TITLE
Still problems with register/login because of 'locale'?

### ISSUE THREAD

**Issue by OlafV83** [pglombardo/PasswordPusher#2808]
I have rolled out a new server but I am encountering the same problem of not being able to register or log in (500 error).
The log file keeps showing that it concerns the 'locale', but I get the same error when this is included in the docker-compose.yml of the pwpusher with postgresql.

[2024-11-24T14:42:57.837976 #119]  INFO -- : [252748ef-8729-4e9c-8fb6-a60c5864dacb] method=POST path=/users/confirmation format=turbo_stream controller=Users::ConfirmationsController action=create status=500 allocations=30096 duration=1984.48 view=0.00 db=89.24 user_id= ip=95.x.x.x forwarded_for=95.x.x.x
E, [2024-11-24T14:42:57.840603 #119] ERROR -- : [252748ef-8729-4e9c-8fb6-a60c5864dacb]
[252748ef-8729-4e9c-8fb6-a60c5864dacb] TypeError (no implicit conversion of Symbol into Integer):
[252748ef-8729-4e9c-8fb6-a60c5864dacb]
[252748ef-8729-4e9c-8fb6-a60c5864dacb] app/controllers/concerns/set_locale.rb:9:in `set_locale'

services:
  postgres:
    image: docker.io/postgres:15
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: passwordpusher_user
      POSTGRES_PASSWORD: passwordpusher_passwd
      POSTGRES_DB: passwordpusher_db
      LANG: 'C.UTF-8'
      LANGUAGE: 'C.UTF-8'
      LC_ALL: 'C.UTF-8'
      LC_COLLATE: 'C.UTF-8'
      LC_CTYPE: 'C.UTF-8'

  passwordpusher:
    image: docker.io/pglombardo/pwpush:latest
    container_name: pwpush
    volumes:
      - ./storage:/opt/PasswordPusher/storage:rw
    environment:
      DATABASE_URL: 'postgres://passwordpusher_user:passwordpusher_passwd@postgres:5432/passwordpusher_db'

**Comment by pglombardo** [comment]
Hi @OlafV83 - `set_locale` is a red-herring.  All requests are wrapped in that to set the proper language.

I suspect the real error is with the email system.

Could you try this [email troubleshooting page](https://docs.pwpush.com/docs/troubleshooting-email/)?

**Comment by OlafV83** [comment]
password-pusher(prod)> TestMailer.send_test_email("[HIDDEN]").deliver_now

--> Configured FROM: address: '[HIDDEN]'
--> Default port is 587 but will only be used if smtp_address is set.
--> SMTP authentication is requested & enabled.

The settings.yml mail configuration is:
----------
raise_delivery_errors: true
smtp_port: 587
smtp_enable_starttls_auto: true
smtp_open_timeout: 10
smtp_read_timeout: 10
smtp_password: [HIDDEN]
smtp_openssl_verify_mode: none
smtp_starttls: true
open_timeout: 10
read_timeout: 10
smtp_authentication: plain
smtp_address: [HIDDEN]
mailer_sender: [HIDDEN]
smtp_user_name: [HIDDEN]
----------

The Mail subsystem SMTP configuration is:
----------
address: [HIDDEN]
port: 587
open_timeout: 10
read_timeout: 10
authentication: plain
user_name: [HIDDEN]
password: [HIDDEN]
openssl_verify_mode: none
enable_starttls_auto: true
----------

--> raise_delivery_errors is set to true in the configuration.  This will raise an error if the email fails to send.

--> Attempting to send a test email to olaf@cloudingit.nl...
--> ✅   It seems that the Email was accepted by the SMTP server!  Check destination inbox for the test email.

--> If you see an error, please paste this output into a GitHub issue for help.
  --> Make sure that no sensitive data is included.
  --> https://github.com/pglombardo/PasswordPusher/issues/new/choose

TestMailer#send_test_email: processed outbound mail in 3.6ms
Failed delivery of mail 6743b67c61433_9814a018733@ff7a263b1f54.mail error_class=TypeError error_message="no implicit conversion of Symbol into Integer"
Date: Mon, 25 Nov 2024 00:27:56 +0100
From: [HIDDEN]
To: [HIDDEN]
Message-ID: <6743b67c61433_9814a018733@ff7a263b1f54.mail>
Subject: Test Email from Password Pusher
Mime-Version: 1.0
Content-Type: text/plain;
 charset=UTF-8
Content-Transfer-Encoding: quoted-printable

=E2=AD=90  If you are reading this, sending email works! =E2=AD=90 =

/opt/PasswordPusher/vendor/bundle/ruby/3.3.0/gems/irb-1.14.1/lib/irb.rb:1260:in `full_message': no implicit conversion of Symbol into Integer (TypeError)

      OpenSSL::SSL::SSLSocket.new socket, context

**Comment by pglombardo** [comment]
Hi @OlafV83 - another user just had this issue and resolved it [in this thread](https://github.com/pglombardo/PasswordPusher/issues/2781#issuecomment-2480495541).

> You might have to play with smtp_starttls and smtp_enable_starttls_auto in the settings.yml file.
> Could you look into the issues and potentially try toggling the above settings? The answer should be in one or both of those issues above.

Could you take a peek at that issue?

**Comment by OlafV83** [comment]
Thank you, the problem is solved!

After trying multiple SMTP servers (all with the same error), I disabled **smtp_openssl_verify_mode: none** and enabled **smtp_enable_starttls_auto** after that the mail is working and the 500 server error went away.

**Comment by pglombardo** [comment]
Excellent - that's great to hear!  I'll close this issue out but if anything else comes up, please let me know.
