### ISSUE TITLE
Can't have retrieval_step working if you're pushing a password via API on self hosted instance.

### ISSUE THREAD

**Issue by mistermania** [pglombardo/PasswordPusher#2819]
## 🔬 How To Reproduce

1. Host your instance
2. Send a password via API & Curl with retrieval_step on true 
3. Observe json response with "retrieval_step":true
4. Open your link, there is no retrieval step

If I'm doing a push by UI, retrieval step is working.

### Code sample

`curl -X POST -F "password[payload]=my_secure_payload" -F "password[expire_after_days]=2" -F "password[expire_after_views]=1" -F "password[retrieval_step]=true" https://your_domain/p.json`

### Environment

Where are you running/using Password Pusher?

- [ ] pwpush.com
- [ ] Docker Image
  - [ ] pwpush
  - [ ] Custom image
- [ ] Heroku
- [ ] Digital Ocean
  - [ ] App Platform
  - [ ] Kubernetes Service
- [ ] Microsoft Azure
  - [ ] App Service
  - [ ] Container Instances (ACI)
  - [ ] Kubernetes Service (AKS)
- [ ] Google Cloud
  - [ ] App Engine
  - [ ] Cloud Run
  - [ ] Kubernetes Engine
- [ ] AWS
  - [ ] Elastic Container Service (ECS)
  - [x ] Kubernetes Service (EKS) via ephemeral manifest (https://github.com/pglombardo/PasswordPusher/tree/master/containers/kubernetes)
- [ ] Source Code
- [ ] Other (please specify)

If applicable, what version of Password Pusher?
Latest image docker

## 📎 Additional context

I also tried to set default values on my containers to get retrieval_step by default, but it changes nothing, still doesn't appear if password is sent by API

**Comment by pglombardo** [comment]
Hi @mistermania,

The `retrieval_step` simply adds `/r` to the end of the final push URL.

If you create a push via `p.json` and then call `/p/<url_token>/preview.json`, it will return a push URL with the `/r` at the end of the URL.

```
> curl -X POST -F "password[payload]=my_secure_payload" -F "password[expire_after_days]=2" -F "password[expire_after_views]=1" -F "password[retrieval_step]=true" https://your_domain/p.json

{
   "expire_after_days":2,
   "expire_after_views":1,
   "expired":false,
   "url_token":"zzg5dg3gvt9oqxzfj18",
   "created_at":"2024-11-30T09:09:35.742Z",
   "updated_at":"2024-11-30T09:09:35.742Z",
   "deleted":false,
   "deletable_by_viewer":true,
   "retrieval_step":true,
   "expired_on":null,
   "days_remaining":2,
   "views_remaining":1
}

> curl https://oss.pwpush.com/p/zzg5dg3gvt9oqxzfj18/preview.json
{
   "url":"https://oss.pwpush.com/p/zzg5dg3gvt9oqxzfj18/r"
}
```

https://your_domain/p/**zzg5dg3gvt9oqxzfj18**/r

It's not required to call `preview.json`.  You could just add `/r` to the end of the url for force the `retrieval_step` option.

I hope I explained this well enough.  Let me know if not!

**Comment by mistermania** [comment]
Hello, yeah, I was building the url myself without calling the preview.json, and I missed the /r part, that's my bad. Thank you for the explanation.
