### ISSUE TITLE
display bug in Expire secret link and delete after

### ISSUE THREAD

**Issue by tibo59** [pglombardo/PasswordPusher#283]
Hello,
there is a display bug when you select more than 1 day in the _Expire secret link and delete after_ function.

This bug appears in the French version.

Regards,
Thibaut Leduc
![Capture_pass_push](https://user-images.githubusercontent.com/92431904/152760272-af0d7246-d7ed-4cf6-8be1-2c76071075a5.PNG)

**Comment by pglombardo** [comment]
Ohh nice find thanks.  That is likely a bad translation.  I'll fix soon.

**Comment by tibo59** [comment]
May be i can help ?
(i did the french translation)

**Comment by pglombardo** [comment]
That's right/just saw :-)  The string `Days` would likely be the culprit.

**Comment by tibo59** [comment]
That's right,  I just fixed the error.

**Comment by pglombardo** [comment]
Great thanks @tibo59!  The change is on the [staging site](https://pwp-stage.herokuapp.com/fr/p/Nouveau).  I'll try and push it to pwpush.com soon when traffic is low.

And thanks as always for the great French translation.  It's the second most used language after English.  Spanish is number 3.  💪
