### ISSUE TITLE
zero knowledge?

### ISSUE THREAD

**Issue by anarcat** [pglombardo/PasswordPusher#30]
is there a clear-text copy of the password on the server?

**Comment by pglombardo** [comment]
There is no clear-text copy of the password saved to database or anywhere else.  

The password is submitted via HTTPS form post.  The application then encrypts the received password and stores only the encrypted hash to the database.

But to be extremely thorough, it's possible that the POST params will still exist in memory (RAM) which theoretically could be located if the server was compromised.  But then again, the password will still have no context - e.g. where to use it.  And to add to the complexity, after the request, the Ruby garbage collector (which runs every few minutes) could reclaim and re-use that address space.

I would love any suggestions or feedback for improvement if you have them!  Hope this helps.

**Comment by pglombardo** [comment]
Closing this issue.  Feel free to comment if you have any more questions!
