### ISSUE TITLE
500 error performing mail functions

### ISSUE THREAD

**Issue by matstocks** [pglombardo/PasswordPusher#301]
When creating an account or doing a password reset an error is output : 500 We're sorry, but something went wrong. 

This would appear to be related maybe to the email sender? I'm not sure how to collect any logs though to investigate.

**Comment by matstocks** [comment]
Found this in the production log:
[c2fd2b7a-5c47-4ca1-81f7-36e50198e5d1] Net::SMTPSyntaxError (501 <'"company name" noreply@mycompany.co.uk'>: "@" or "." expected after "'"):

this is the output of my env variables:

PATH=/opt/PasswordPusher:/usr/local/bundle/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=010bf49c0980
PWP__MAIL__SMTP_USER_NAME=companyname.co.uk
PWP__MAIL__SMTP_ADDRESS=mail.smtp2go.com
PWP__MAIL__OPEN_TIMEOUT=10
PWP__MAIL__SMTP_AUTHENTICATION=plain
PWP__ENABLE_LOGINS=true
PWP__MAIL__MAILER_SENDER='"nompany name" noreply@companyname.co.uk'
PWP__MAIL__SMTP_STARTTLS=true
PWP__MAIL__SMTP_PORT=587
PWP__HOST_PROTOCOL=https
PWP__MAIL__READ_TIMEOUT=10
PWP__HOST_DOMAIN=pass.companyname.co.uk
PWP__MAIL__SMTP_PASSWORD=redacted
PWP__MAIL__RAISE_DELIVERY_ERRORS=true
LANG=C.UTF-8
RUBY_MAJOR=3.0
RUBY_VERSION=3.0.2
RUBY_DOWNLOAD_SHA256=570e7773100f625599575f363831166d91d49a1ab97d3ab6495af44774155c40
GEM_HOME=/usr/local/bundle
BUNDLE_SILENCE_ROOT_WARNING=1
BUNDLE_APP_CONFIG=/usr/local/bundle
APP_ROOT=/opt/PasswordPusher
HOME=/opt/PasswordPusher
DATABASE_URL=mysql2://passwordpusher_user:redacted@mysql:3306/passwordpusher_db
BUNDLE_GEMFILE=./gemfiles/Gemfile-mysql
RACK_ENV=production
RAILS_ENV=production
RAILS_SERVE_STATIC_FILES=true

**Comment by pglombardo** [comment]
You missed the brackets (`<>`) in `PWP__MAIL__MAILER_SENDER`.  Change it to this format:

export PWP__MAIL__MAILER_SENDER='"Company Name" <user@example.com>'

That should be it - let me know.

**Comment by pglombardo** [comment]
BTW if you are reading this in email, the Github email system strips the brackets so it doesn't show up correctly.  This Github issue shows it correctly:

![Screen Shot 2022-03-06 at 13 54 49](https://user-images.githubusercontent.com/395132/156924148-0e65a60b-b186-46a6-88ab-b3113f6c4968.png)

**Comment by matstocks** [comment]
I tried this, but getting the same error:

root@b66a56ee722e:~/log# cat production.log 
F, [2022-03-06T14:11:47.453194 #14] FATAL -- : [2d0d005b-75c9-4a80-9da2-1a25478c8651]   
[2d0d005b-75c9-4a80-9da2-1a25478c8651] Net::SMTPSyntaxError (501 <'"Company Name" <noreply@companyname.co.uk>'>: "@" or "." expected after "'"
):

**Comment by matstocks** [comment]
Worked it out. It was because the content of my docker-compose was incorrect. I misunderstood what the end result should be and assumed when the variable was finally set it should include the single "'" but it shouldn't . I added the < > as you described, and corrected my compose file and this now works thanks.
