### ISSUE TITLE
HTTPS using already-in-place reverse proxy

### ISSUE THREAD

**Issue by azaloum90** [pglombardo/PasswordPusher#305]
I'm running a Windows Web Application Proxy Server which does of my internal redirections.  Works for all services, including pwpush, but I have a problem with the URL's being created

I have pwpush running on URL https://password.domain.net, running on port 443, of which the site is completely accessible without issue.  The back end configuration of the proxy forwards the application operations to this address: http://password.domain.net:5100

I can create a password then press "push it", and as expected pwpush spits out a URL.  However, the issue is as follows:

The URL that is provided by pwpush is: http://password.domain.net:5100/en/p/*************
However, I wish for the URL to show as the following: https://password.domain.net/en/p/*************

Is there a way to force this change in the PWPush configuration?  Or does the application *only* provide a URL that matches the URL of which I was accessing behind the proxy (in this case, the http:5100 page)?

**Comment by pglombardo** [comment]
Hi @azaloum90 - To fix the HTTPS part, you can set the [`FORCE_SSL` environment variable](https://github.com/pglombardo/PasswordPusher/blob/master/Configuration.md#forcing-ssl-links) to force it regardless.

As for the `host:port` part, the proxy _should_ set the `X-Forward-Host/Port/Proto` headers when making a request to the backend Password Pusher instance.

If those headers are sent by the relaying proxy, then the correct URLs should show up.

Some links:

https://stackoverflow.com/questions/19084340/real-life-usage-of-the-x-forwarded-host-header
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Host

Could you see if you can have your proxy forward those headers to the backend and let me know what you find?

**Comment by pglombardo** [comment]
Ok I confirmed this by sending a `X-Forwarded-Host: mcdonalds.com` request header using the requestly browser extension.

This was the staging site URL if needed:
http://pwp-stage.herokuapp.com/en/p/f26og_0jyyqr/preview

![Screen Shot 2022-03-20 at 21 24 12](https://user-images.githubusercontent.com/395132/159184644-dad8e644-5dbb-4593-918d-db3dcc0a92e8.png)



![Screen Shot 2022-03-20 at 21 24 02](https://user-images.githubusercontent.com/395132/159184649-dfdd5eb1-de1a-4c25-96e4-313e98e4d528.png)

So given this, also sending `X-Forwarded-Proto: https` and `X-Forwarded-Port: 443` should fix the URL generation.

I hope this helps.

**Comment by pglombardo** [comment]
Hi @azaloum90 - did you have any luck with this?

**Comment by azaloum90** [comment]
> Hi @azaloum90 - did you have any luck with this?

Thanks for replying, it seems the Windows Web App Proxy doesn't let me modify these settings, so for now I am out of luck on this one, but I appreciate you taking the time!  The information is helpful, if I ever get around to doing a double reverse proxy I will try that.

Thanks!
Adam

**Comment by pglombardo** [comment]
This might be a work-around but my Microsoft Server knowledge is outdated: https://blog.frankfu.com.au/2018/11/13/correcting-host-headers-with-azure-websites-when-using-it-behind-an-application-gateway-or-reverse-proxy/

**Comment by ben71fl** [comment]
Mine had been working until recently, we are pulling from docker, I have set FORCE_SSL=true in the enviornment but not setup inside the docker , maybe thats where I need it? when I goto https://mysite.com I get the gui but then the secret is generated in http:// and I cant get it, if I flip the broken url to https:// it works .. so its just the url generation.

**Comment by pglombardo** [comment]
Hi @ben71fl - [this documentation](https://github.com/pglombardo/PasswordPusher/blob/master/Configuration.md#proxies) should help.  Best case is to have the proxy forward the appropriate headers (which specified HTTPS), but if that isn't easily possible - there is an environment variable override to force the base URL.

**Comment by pglombardo** [comment]
An Ubuntu update wouldn't modify the pwpush container so maybe something changed in nginx?

The options are to make sure nginx are passing the proper headers or use the container environment variables listed in that documentation above.

With either of those, you should be set.  Please let me know how it goes - I'd be happy to help further.
