### ISSUE TITLE
Add Config to Force base URL for generated links

### ISSUE THREAD

**Issue by pglombardo** [pglombardo/PasswordPusher#309]
The Windows Server proxy doesn't seem to send `X-Forward-Host/Port/Proto` HTTP headers to the backend.  This is the usual method to have generated URLs with the correct external address.

To support this case, we could add an environment variable to force the base url, proto and port if needed.

This comes from #305

**Comment by azaloum90** [comment]
If this could be accomodated, that would be AWESOME

**Comment by pglombardo** [comment]
I'll get this out soon:

![Screen Shot 2022-05-07 at 15 00 41](https://user-images.githubusercontent.com/395132/167255777-a71bb3df-3716-496e-a5f3-48f7bdd30a80.png)


https://github.com/pglombardo/PasswordPusher/pull/330

**Comment by pglombardo** [comment]
Hi @azaloum90  - this has been released in [v1.12.0](https://github.com/pglombardo/PasswordPusher/releases/tag/v1.12.0).

Documentation here:
https://github.com/pglombardo/PasswordPusher/blob/master/Configuration.md#proxies

Let me know if you have any issues with this.  Thanks for reporting!

**Comment by azaloum90** [comment]
Worked like a charm for me!  Had to manually specify the version for my Docker instance to pull it, but all is well now!  Thanks again!

**Comment by pglombardo** [comment]
Ok that's great to hear.  I'll update the Docker `release` tag to point to that latest version soon.
