### ISSUE TITLE
Deploy to Heroku - Couldn't find add-on service or the add-on traceview

### ISSUE THREAD

**Issue by adamnoffie** [pglombardo/PasswordPusher#31]
Getting this error message (and one about another add-on which I forget now) when trying to use the "Deploy to Heroku" link you have in the README.txt

![error](http://i.imgur.com/pmi7HVo.png)

**Comment by pglombardo** [comment]
Doh my apologies for that @adamnoffie.  TraceView was recently removed from Heroku.  I'll update once I put a fix in.

**Comment by pglombardo** [comment]
Thanks @adamnoffie for letting me know.  We're back in business.  I removed the offending addons and just deployed a new app without problem.

Let me know that you see the same.  Best.
