### ISSUE TITLE
How to configure certificates on pwpusher?

### ISSUE THREAD

**Issue by Kyawn88** [pglombardo/PasswordPusher#313]
I'm probably being an absolutely massive noob here! I've very rarely used Ubuntu and Docker, but wanted to utilise Password Pusher.

I've got everything setup and can use pwpusher fine when using HTTP, but I wanted to secure it. I've created certificates using Certbot, but I cannot see how I would utilise these in the environment configuration file for the container itself? I can only see the option to force SSL links.

Is it possible to install the certificates on the web server that password pusher creates itself? Or do I need to use a proxy like nginx to achieve HTTPS connectivity?

Yet again I apologise, I'm a very unlearned Ubuntu and Docker user, this is probably extremely easy to solve!

**Comment by pglombardo** [comment]
Hi @Kyawn88 - absolutely no problem to ask questions.

The correct answer is to use nginx as a SSL termination point in front of Password Pusher.

I spent some time researching on how to simplify this process (or make it work out of the box) but unfortunately there isn't a better answer currently.

If you deploy to a cloud like Heroku, then you get SSL with a single click.

You can find some past discussions about SSL [here](https://github.com/pglombardo/PasswordPusher/issues?q=is%3Aissue+ssl+).

Hopefully this gives you a starting point.  If you have any other issues/questions, don't hesitate.

**Comment by Kyawn88** [comment]
Got this working in the end, had some issues with the certificates not generating properly from Certbot. Then I had some redirect issues, which just ended up being a security group misconfiguration in AWS. The Password Pusher is now working flawlessly with SSL :)
