### ISSUE TITLE
Move Container Volume to another drive

### ISSUE THREAD

**Issue by azaloum90** [pglombardo/PasswordPusher#317]
What's the docker-compose volume command to set the volume of the container to another disk?

For reference, I am not referring to the DB volume -- I see those in the Docker Compose files!

**Comment by pglombardo** [comment]
Hi @azaloum90 - I wish I knew or somebody who did would chime in.  Did you ever figure this out?

**Comment by azaloum90** [comment]
> Hi @azaloum90 - I wish I knew or somebody who did would chime in. Did you ever figure this out?

I believe I figured it out!  Portainer showed this as the configuration:

/opt/PasswordPusher

So if you wanted to hard-store the app files on their own volume you would use that for the Volume Map, something like:

/mnt/docker/pwpush:/opt/PasswordPusher

Since Password Pusher doesn't really store any data within the application itself, this probably isn't useful, but hey, it should work!

**Comment by pglombardo** [comment]
Excellent - that's great to hear.  And you're right - no data in the app itself besides some logs possibly.

Closing but feel free to open another if other issues/questions.
