### ISSUE TITLE
Ergonomic improvement proposal

### ISSUE THREAD

**Issue by tibo59** [pglombardo/PasswordPusher#332]
Hello Peter,
In the page to see a published secret,
there is this sentence :

"Your password is blurred out. Click below to reveal it."

![image](https://user-images.githubusercontent.com/92431904/169003739-bffd32c3-ec87-42b8-8aea-ab48f9aab274.png)

But under the sentence it is the "Copy to Clipboard" button which is placed and not the blurred zone.

We are using Password Pusher in production (French educational institution) and see that some users (not very experienced ...) have difficulty with this : they click on the "copy.." button to reveal the secret.

My suggestion is : move the "Your password is blurred out. Click below to reveal it. " sentence below the "copy" button.

Thank for this great work,

Thibaut

**Comment by pglombardo** [comment]
Hey Thibaut - sure thing.  I'll make the change once I get pass this cold.

**Comment by pglombardo** [comment]
I made the change in the code and is available on the [staging site](https://pwp-stage.herokuapp.com/en).  I'll push this to pwpush.com this weekend when traffic is low.
