### ISSUE TITLE
Feature Req - Disable Front Page when no one logged in

### ISSUE THREAD

**Issue by blaine07** [pglombardo/PasswordPusher#342]
Feature Request:

disable front page unless someone is logged in. 

I am trying to block PW PUsher main screen/screen passwords are “sent” from in Nginx Proxy Manager BUT I want to allow receiver to open the password Push without a login requirement. 

Any consideration would be greatly appreciated!

https://www.reddit.com/r/nginxproxymanager/comments/u0ks9n/protect_subdomain_with_access_list_not_protect/?utm_source=share&utm_medium=ios_app&utm_name=iossmf

![56F47B52-DC18-483E-8FF4-1236DF413464](https://user-images.githubusercontent.com/63940698/170905046-3713aa01-aa96-48e3-b331-1bc2646221d4.jpeg)
![2601F414-4D4B-4FEC-A545-3FC715F51884](https://user-images.githubusercontent.com/63940698/170905056-5403983d-a0e9-4db8-af45-b12963d5b9f4.png)

All the thanks!

**Comment by pglombardo** [comment]
Hi @blaine07 - sounds good.  Let me see if I can get this done this weekend.

**Comment by pglombardo** [comment]
Implemented and released in #343 on tag `1.14.0`.
