### ISSUE TITLE
settings for allow creation from allow-ip list only and access to shared pws everwhere

### ISSUE THREAD

**Issue by fuco809** [pglombardo/PasswordPusher#347]
how to configure a webserver to allow the creation only from some ip addresses? or is there an app option to to this like the "allowed registrated user only"

**Comment by pglombardo** [comment]
Hi @fuco809 -

The two options I see are:

1. Put a proxy (such as nginx) in front of the application with a black/white list of ip blocks to `POST /p`
2. PasswordPusher [has an option](https://github.com/pglombardo/PasswordPusher/blob/master/Configuration.md#enabling-logins) to require login to push passwords (environment variable: `PWP__ALLOW_ANONYMOUS=false`)

Hopefully one of these helps.
