### ISSUE TITLE
Error 505 when Sign Up using mailgun

### ISSUE THREAD

**Issue by JonasBarcat** [pglombardo/PasswordPusher#353]
Hello, I've been trying to setup mailgun in pwpusher using a local docker container with a local mysql db in another container.
I use this command to run the container. It works but when I fill the sign up form and send it, it gives me the error.

`docker run -d -p "5100:5100" -e DATABASE_URL=mysql2://root:jonas@172.17.0.2:3306/pwpush_db -e PWP__ENABLE_LOGINS=true -e PWP__MAIL__RAISE_DELIVERY_ERRORS=true -e PWP__MAIL__SMTP_PORT=587 -e PWP__MAIL__SMTP_ADDRESS=smtp.mailgun.org -e PWP__MAIL__SMTP_USER_NAME=<my-username> -e PWP__MAIL__SMTP_PASSWORD=<my-password> -e PWP__MAIL__SMTP_AUTHENTICATION=plain -e PWP__MAIL__SMTP_STARTTLS=true -e PWP__MAIL__OPEN_TIMEOUT=10 -e PWP__MAIL__READ_TIMEOUT=10 -e PWP__HOST_PROTOCOL=https -e PWP__MAIL__MAILER_SENDER='"Company Name" <user@example.com>' -e PWP__ALLOW_ANONYMOUS=true  pglombardo/pwpush-mysql:release`

I tried to setting it up from config/settings.yml but I get the same error. Thank you for your help.

**Comment by pglombardo** [comment]
Ugh I have to move those config vars into a config file :-)

I don't see an error here.

The related error message should be in `/opt/PasswordPusher/log/*.log` inside the container.

Could you find that log file and post the error message you find there?  That should point us in the right direction.

**Comment by pglombardo** [comment]
That's great to hear.  Anything else - don't hesitate.
