### ISSUE TITLE
Option to configure rack throttle limits

### ISSUE THREAD

**Issue by stephenmahood** [pglombardo/PasswordPusher#358]
We'd like the ability to either disable or configure the rack throttle limits through environment variables so that we can pass these to the container images.

**Comment by pglombardo** [comment]
This shouldn't be too much work.  Let me see if I can get some time to work on this soon.

https://github.com/dryruby/rack-throttle

**Comment by pglombardo** [comment]
The code for this has been merged into master and new containers will be released later today.  pwpush.com will get updated this weekend.

There is no on/off switch for throttling but you can now increase/decrease limits [via environment variables](https://github.com/pglombardo/PasswordPusher/blob/master/config/settings.yml#L58-L95).

Thanks for pointing this out!
