### ISSUE TITLE
Bigger Text Field for Input

### ISSUE THREAD

**Issue by nocode99** [pglombardo/PasswordPusher#36]
I'm not familiar with Ruby on Rails, but I would like to deploy this app but have the input be a multiple line text field.  I believe this piece is generating the html file but I'm not sure how to specify a larger text field:

https://github.com/pglombardo/PasswordPusher/blob/6b71cab195e4d164b756d58ef53f482d0ce1ba09/app/views/passwords/new.html.haml

The reason for this is I would use this to send more than just passwords.

**Comment by pglombardo** [comment]
Hi @nocode99.  I like and have had the same idea myself in the past.  Unfortunately, there are some problems with doing this:

- The database field where the encrypted text is stored has a max length of 255 characters
- The javascript on the page enforces a max length
- The input is a text field and not a textarea

Although all of the above could be modified, it would take a fair amount of work and may not be worth the effort.

You could instead use something like [pastebin](http://pastebin.com/) that allows you to set an expiration for the paste.  Although if you are self-hosting, this wouldn't be a solution for you.

**Comment by pglombardo** [comment]
I was just poking around and it seems there are a good number of new tools in this space that you might find useful:

https://quickforget.com/
https://onetimesecret.com/
https://dead-drop.me/

**Comment by nocode99** [comment]
@pglombardo thanks for the links.  I came across your site via Reddit and remembered in the past, similar solutions that offered multiline text box but my google-fu failed me.  I will definitely check those out.  Thanks!
