### ISSUE TITLE
JSON API Authentication

### ISSUE THREAD

**Issue by mtchetch** [pglombardo/PasswordPusher#366]
Auditing is a feature we need to have for our use case and it does not seem to be possible to have an "Admin" style account that could see and manage all the entries in a self hosted instance.

I have gotten the JSON API working when the installation is setup for anonymous access. I did not find documentation on how to authenticate the API requests. 

The API requests go through when sending them through a browser with an active session cookie, but this does not allow using an external system for sending the requests. 

Please provide info on how to authenticate the API-requests for an existing user account.

**Comment by pglombardo** [comment]
We don't have this ability currently in the API.  The same goes for an admin style account.  I've given some thought on how to add these but haven't had the chance to do so you.

I'll keep this issue open and update again when this is added.

**Comment by mtchetch** [comment]
We have decided to implement a hacky workaround for our use case.

We will run the mysql-flavored container behind an nginx reverse proxy that is set to protect the main page, login page etc with simple auth and only expose the json api and password links in desired localisations to unauthenticated users outside our local networks.

The "admin" panel / admin user will be created with a mysql workaround that will run a query to set the owner-ID for all password entries to the admin user and do so via cron script every 5 min.

That way the system will behave like it actually had an admin panel and admin user functionality. All entries can be managed via a single "admin" user account.

A hard coded user id for new entries could probably be easily implemented as a config flag in the system, if you see it would benefit users.

**Comment by pglombardo** [comment]
Hi @mtchetch - The updated JSON API with authentication has been released.  I posted a short summary in this twitter thread: https://twitter.com/pwpush/status/1563889107536941057

**Comment by mtchetch** [comment]
The latest tag is in fact not the latest and specifying the tag 1.17.1 seems to work.

**Comment by pglombardo** [comment]
Yes - that is correct.  `latest` is built weekly when it should be daily.  https://github.com/pglombardo/PasswordPusher/issues/401

**Comment by pglombardo** [comment]
Hi @mtchetch - this should be all fixed now in 1.17.1 and beyond.  How are things?

I'll close this issue if there is nothing remaining.

**Comment by mtchetch** [comment]
> Hi @mtchetch - this should be all fixed now in 1.17.1 and beyond. How are things?
> 
> I'll close this issue if there is nothing remaining.

I think this can be closed. Good work with the API!

**Comment by pglombardo** [comment]
Hi @mtchetch  - It's been a long while on this issue but just an update that the API has some changes coming soon that shouldn't break anything but just in case, see #3068.

Hope all is well!
