### ISSUE TITLE
Docker container - Mysql data not persistant

### ISSUE THREAD

**Issue by mtchetch** [pglombardo/PasswordPusher#368]
https://github.com/pglombardo/PasswordPusher/blob/8bbee221cf4e591bd03300b683957ad7d15c2131/containers/docker/pwpush-mysql/docker-compose.yaml#L14

The folder remains empty when using MysqlDB. The database is actually stored under /var/lib/mysql as per mariadb default configuration.
The data will get wiped if the container is recreated with out the volume.

**Comment by pglombardo** [comment]
Thanks for pointing this out.  I'll put in a fix soon and tag new containers.

**Comment by pglombardo** [comment]
@ clmcavaney I'm going to update the Mysql data path - do you see/have any issue with this?

**Comment by clmcavaney** [comment]
G'day @pglombardo - no that will be fine.  I am using the `DATABASE_URL` environment variable to point to an already existing MySQL server I am running.
Thanks for asking.

**Comment by pglombardo** [comment]
Thanks @clmcavaney 

@mtchetch the fix in #377 has been merged.  I'll tag new containers before the end of the weekend.
