### ISSUE TITLE
Add support for Slack integration

### ISSUE THREAD

**Issue by brianroach** [pglombardo/PasswordPusher#37]
I'm trying to create a /Slash command for slack to securely share passwords. Can someone point me in the right direction, please?
![pw-pusher](https://cloud.githubusercontent.com/assets/9772694/15516174/7b42be1a-21a6-11e6-8891-ca132a14f176.jpg)

**Comment by pglombardo** [comment]
Hey @brianroach great idea!  I'm not familiar with setting up those custom slack commands but can take a closer look tomorrow.

In the meantime, if the form just accepts what HTTP form details are needed, we have those listed in the [Password API](https://github.com/pglombardo/PasswordPusher/wiki/Password-API).

Note that API sends the HTTP form to `/p.json` although just `/p` should work too depending on what type of response you want.

**Comment by pglombardo** [comment]
I took a look at the Slash documentation and it seems we'll have to implement Slack support inside of PasswordPusher.  To do this, we'll have to do the following:

1. Add a new path specifically for incoming slack requests
2. Process the slack request form parameters and then do the usual password magic
3. Respond via plaintext with the resulting password URL and possibly some extra info (expirations, views etc..)

Unless you're willing to code and submit a PR, I can take a shot at doing this eventually.  I can't promise anytime immediately but I'll do my best.  Let me know if you have any preferences or thoughts on this.

Some of the docs:
https://api.slack.com/slash-commands
https://api.slack.com/slack-apps

**Comment by pglombardo** [comment]
Very late update 😜 .  I have a pull-request/branch where is this working: https://github.com/pglombardo/PasswordPusher/pull/75

I'll push to merge it soon.

**Comment by alexandrezia** [comment]
Using slack integration, workign well,
My slack users loved this

**Comment by pglombardo** [comment]
Slack integration added in https://github.com/pglombardo/PasswordPusher/pull/75.  I still need to document & publicise this a bit.

**Comment by pglombardo** [comment]
Added a brief wiki page on how to add PasswordPusher as a custom slash command in Slack: https://github.com/pglombardo/PasswordPusher/wiki/PasswordPusher-&-Slack:-Custom-Slash-Command
