### ISSUE TITLE
Automatic password generation, random password

### ISSUE THREAD

**Issue by n-marques** [pglombardo/PasswordPusher#38]
It would be nice to have the option to create a random pass. Even better if we cold choose the type (just numbers, special chars, etc...)

Great software by the way.

**Comment by pglombardo** [comment]
Thanks @luxitan!  I agree - it's a great suggestion.  I'll see if I can find some time to add this eventually.  I can't promise anytime soon but I'll see what I can do.

**Comment by christag** [comment]
I'm working on a branch of pwpush that uses HSXKPasswd to generate a password on the fly. Right now it's really specialized to a particular standard but I think it would be a good implementation to expand on this functionality in a way that's already written.

https://github.com/bbusschots/hsxkpasswd/releases
https://www.bartbusschots.ie/s/publications/software/xkpasswd/

**Comment by sumnerboy12** [comment]
This is a great little tool, thanks @pglombardo! I agree a password generator on the main landing page would be a great addition. Just adding my +1 for this suggestion. Thanks again!

**Comment by pglombardo** [comment]
This might be a good option for integration:
https://github.com/omgovich/omgopass

**Comment by pglombardo** [comment]
Coming soon.

![Screen Shot 2021-08-28 at 15 22 59](https://user-images.githubusercontent.com/395132/131219488-1572de9f-29c4-4e73-add4-2d8e8d96a504.png)

**Comment by pglombardo** [comment]
This feature is done.  pwpush.com and containers are updating now.  Thanks all for the feedback/input!
