### ISSUE TITLE
Configure SMTP to ignore invalid certificate

### ISSUE THREAD

**Issue by amberflag48** [pglombardo/PasswordPusher#385]
Hello!

I was trying to configure the SMTP part so I have to login in order to generate a password.

I then tried to sign up, but got the error `#500 - We're sorry, but something went wrong`.

After digging in the logs I found this error:
> `OpenSSL::SSL::SSLError (SSL_connect returned=1 errno=0 state=error: certificate verify failed (self signed certificate)):`

Because of the provider that I am using (Protonmail), I cannot change the certificate so I need Password Pusher to be able to ignore the certificate error.

Is there any way to do that?
Thanks!

**Comment by pglombardo** [comment]
Protonmail should always have valid certificates...their whole marketing is about security.  I would open a support ticket with them too.

..but in any case, the option to _not_ verify the SSL peer was available but not exposed with the other SMTP options.  I put #386 together to fix.  Once I finish some testing & documentation and get to release it, I'll update again here.

**Comment by amberflag48** [comment]
> ?

That is not true, they do not offer public SMTP server so you have to install their bridge that'll broadcast SMTP on localhost.

Because it broadcasts SMTP on 127.0.0.1 it uses a self signed certificate.

**Comment by amberflag48** [comment]
> Protonmail should always have valid certificates...their whole marketing is about security.  I would open a support ticket with them too.
> 
> ..but in any case, the option to _not_ verify the SSL peer was available but not exposed with the other SMTP options.  I put #386 together to fix.  Once I finish some testing & documentation and get to release it, I'll update again here.
> 
> How are you running the application?  Via Docker container?

That is not true, they do not offer public SMTP server so you have to install their bridge that'll broadcast SMTP on localhost.

Because it broadcasts SMTP on 127.0.0.1 it uses a self signed certificate.

Yes I am running both Proton bridge and Password Pusher using Docker compose.

**Comment by pglombardo** [comment]
The fix in #386 has been merged.  Release coming soon.
