### ISSUE TITLE
Generate Password: saved "Use Seperators" option ignored when disabled

### ISSUE THREAD

**Issue by jerrykan** [pglombardo/PasswordPusher#387]
I seem to have hit an issue with the Generate Password settings when trying to save the settings with the "Use Seperators" option disabled.

## Steps to reproduce
  - Open the Generate Password settings
  - Set the following settings:
    - Number of Syllables: **3**
    - Minimum Syllable Length: **3**
    - Maximum Syllable Length: **3**
    - Include numbers: **Enabled**
    - Use Titlecase: **Enabled**
    - Use Separators: **Disabled**
  - Click "Test" to confirm settings
  - Click "Save" to save the settings
  - Reload the page and click on "Generate Password"

## Results
When generating a new password after reloading the page it includes separators

## Expected Results
The generated password should not include any separators.

## Other comments
After reloading the page and looking at the "Generate Password" settings the "Use Separators" option is still disabled, but it seems to be ignored. Toggling the "Use Separators" options fixes the problem temporarily... until the next page reload.

**Comment by pglombardo** [comment]
Good find!  Thanks for the report.  It seems the cookie for that setting wasn't saved or isn't being loaded correctly.  I'll see if I can fix this soon.

**Comment by pglombardo** [comment]
Hi @jerrykan - thanks for pointing this out.  This has been fixed now in the latest releases.
