### ISSUE TITLE
Updated Ruby? More specifically - Gem Load Error is: uninitialized constant Syck

### ISSUE THREAD

**Issue by dnichk** [pglombardo/PasswordPusher#39]
Any plans to update the app for a more current version of Ruby? Seems like newer versions of Ruby choke with:

Gem Load Error is: uninitialized constant Syck

This happens when trying to run:
RAILS_ENV=private bundle exec rake db:setup

**Comment by pglombardo** [comment]
Hey @dnichk.  I just installed on a new system and got the same error.  Elsewhere, I'm running on Ruby 2.3 without issue.

Thanks for pointing this out.  I'll dig around and update here soon.

**Comment by dnichk** [comment]
Great. Looking forward to deploying once resolved.

**Comment by dnichk** [comment]
For clarity, I was trying to run it on: ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]

**Comment by pglombardo** [comment]
Hey @dnichk .  My apologies that I've been a bit busy.  I suspect if you remove `rails_admin` from the Gemfile and re-run `bundle install`, this should resolve the issue.  

I pushed up this change a couple days ago but haven't finish testing.

Could you try a `git pull` and restart the stack?

**Comment by pglombardo** [comment]
Thanks for being patient on this issue @dnichk .  I just deployed new app instances to my mac and the other to Heroku without issue.  Could you confirm that you are seeing the same?

**Comment by dnichk** [comment]
@pglombardo - I now have it up and running under Ubuntu 16.04. I do, however, now have to figure out how to setup for production. I have been documenting it as we go. If I can get it figured out, you can post the full tutorial.

**Comment by pglombardo** [comment]
Closing up this issue.  If this is in error, feel free to re-open.  I plan to kick off an automated test suite that will run on Travis with each git push so clean slate ruby versions will be tested more thoroughly/consistently.
