### ISSUE TITLE
Heroku no longer free as README claims

### ISSUE THREAD

**Issue by AdamNofsinger-Leer** [pglombardo/PasswordPusher#393]
FYI, Heroku is going to soon stop offering free Dynos / Postgres .
See https://blog.heroku.com/next-chapter

So might want to update the documentation to reflect that.  I'm still figuring out where I can host it for free/cheap, might try our DigitalOcean.  Thanks for this very useful tool!

**Comment by pglombardo** [comment]
Thanks for the note!  pwpush.com is hosted there although it's all paid components (except for the pipeline/staging site).

I've been wanting to move away from Heroku for a long time now.  This may be the trigger needed.  I may give Digital Ocean another try or just fall back to AWS ECS potentially.

The README has been updated.

**Comment by AdamNofsinger-Leer** [comment]
Neat, will look forward to seeing what you come up with.  I'm trying Digital Ocean myself, although I'm doing it on a Droplet (VM) running Ubuntu / Easypanel / Docker, but maybe it would be a few $$ cheaper each month to run it as an "App" or on AWS

**Comment by pglombardo** [comment]
I like the DO app hosting they have.  I tried it last year and didn't work entirely.  Hopefully it's better now.

A droplet is a good solution and that's how I used to host it.  The zero management of Heroku & DO App hosting though is hard to move away from once I got used to it.
