### ISSUE TITLE
Postgres Ver. 1.16.0 and UP issues

### ISSUE THREAD

**Issue by blaine07** [pglombardo/PasswordPusher#397]
Hey it's this fool again.

I am using PasswordPusher on Unraid still.

I always lock container to a specific build; and until today was on postgres 1.14.3. I upgraded to 1.17.0 and had 502 bad gateway errors. The container does seem to load/work for a second then crashes. That led to me thinking maybe I needed to step up upgrades and go a version at a time.

I am not sure if it's me being dumb, like usual, BUT it appears anything AFTER POSTGRES 1.15.1 does not work. Maybe this issue is specific to Postgres version? 

When I go 1.17.0 for example the part of log I can catch is:

bundler: failed to load command: puma (/opt/PasswordPusher/vendor/bundle/ruby/3.1.0/bin/puma)
/opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require': cannot load such file -- net/pop (LoadError)
        from /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in `require'
        from /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/mail-2.7.1/lib/mail/network/retriever_methods/pop3.rb:36:in `<class:POP3>'
        from /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/mail-2.7.1/lib/mail/network/retriever_methods/pop3.rb:35:in `<module:Mail>'
        from /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/mail-2.7.1/lib/mail/network/retriever_methods/pop3.rb:4:in `<main>'
        from /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        from /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        from /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in `require'
        from /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/mail-2.7.1/lib/mail.rb:54:in `block in eager_autoload!'
        from /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/mail-2.7.1/lib/mail.rb:54:in `each'
        from /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/mail-2.7.1/lib/mail.rb:54:in `eager_autoload!'
        from /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/actionmailer-6.1.6.1/lib/action_mailer.rb:61:in `eager_load!'
        from /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/railties-6.1.6.1/lib/rails/application/finisher.rb:134:in `each'
        from /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/railties-6.1.6.1/lib/rails/application/finisher.rb:134:in `block in <module:Finisher>'
        from /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/railties-6.1.6.1/lib/rails/initializable.rb:32:in `instance_exec'
        from /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/railties-6.1.6.1/lib/rails/initializable.rb:32:in `run'
        from /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/railties-6.1.6.1/lib/rails/initializable.rb:61:in `block in run_initializers'
        from /usr/local/lib/ruby/3.1.0/tsort.rb:228:in `block in tsort_each'
        from /usr/local/lib/ruby/3.1.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        from /usr/local/lib/ruby/3.1.0/tsort.rb:431:in `each_strongly_connected_component_from'
        from /usr/local/lib/ruby/3.1.0/tsort.rb:349:in `block in each_strongly_connected_component'
        from /usr/local/lib/ruby/3.1.0/tsort.rb:347:in `each'
        from /usr/local/lib/ruby/3.1.0/tsort.rb:347:in `call'
        from /usr/local/lib/ruby/3.1.0/tsort.rb:347:in `each_strongly_connected_component'
        from /usr/local/lib/ruby/3.1.0/tsort.rb:226:in `tsort_each'
        from /usr/local/lib/ruby/3.1.0/tsort.rb:205:in `tsort_each'
        from /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/railties-6.1.6.1/lib/rails/initializable.rb:60:in `run_initializers'
        from /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/railties-6.1.6.1/lib/rails/application.rb:391:in `initialize!'
        from /opt/PasswordPusher/config/environment.rb:78:in `<top (required)>'
        from config.ru:3:in `require'
        from config.ru:3:in `block in <main>'
        from /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/rack-2.2.4/lib/rack/builder.rb:116:in `eval'
        from /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/rack-2.2.4/lib/rack/builder.rb:116:in `new_from_string'
        from /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/rack-2.2.4/lib/rack/builder.rb:105:in `load_file'
        from /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/rack-2.2.4/lib/rack/builder.rb:66:in `parse_file'
        from /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/puma-5.6.5/lib/puma/configuration.rb:348:in `load_rackup'
        from /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/puma-5.6.5/lib/puma/configuration.rb:270:in `app'
        from /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/puma-5.6.5/lib/puma/runner.rb:150:in `load_and_bind'
        from /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/puma-5.6.5/lib/puma/cluster.rb:357:in `run'
        from /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/puma-5.6.5/lib/puma/launcher.rb:193:in `run'
        from /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/puma-5.6.5/lib/puma/cli.rb:81:in `run'
        from /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/puma-5.6.5/bin/puma:10:in `<top (required)>'
        from /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/bin/puma:25:in `load'
        from /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/bin/puma:25:in `<top (required)>'
        from /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.3/lib/bundler/cli/exec.rb:58:in `load'
        from /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.3/lib/bundler/cli/exec.rb:58:in `kernel_load'
        from /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.3/lib/bundler/cli/exec.rb:23:in `run'
        from /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.3/lib/bundler/cli.rb:484:in `exec'
        from /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        from /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.3/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
        from /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.3/lib/bundler/cli.rb:31:in `dispatch'
        from /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.3/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
        from /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.3/lib/bundler/cli.rb:25:in `start'
        from /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.3/exe/bundle:48:in `block in <top (required)>'
        from /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.3/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
        from /opt/PasswordPusher/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.3/exe/bundle:36:in `<top (required)>'
        from /usr/local/bundle/bin/bundle:25:in `load'
        from /usr/local/bundle/bin/bundle:25:in `<main>'
[9] Puma starting in cluster mode...
[9] * Puma version: 5.6.5 (ruby 3.1.2-p20) ("Birdie's Version")
[9] *  Min threads: 5
[9] *  Max threads: 5
[9] *  Environment: production
[9] *   Master PID: 9
[9] *      Workers: 2
[9] *     Restarts: (✔) hot (✖) phased
[9] * Preloading application
[9] ! Unable to load application: LoadError: cannot load such file -- net/pop

** Press ANY KEY to close this window ** 

Hopefully this helps?

**Comment by pglombardo** [comment]
Hi @blaine07 good to hear from you.  It seems that this is due to this issue:

https://stackoverflow.com/questions/70500220/rails-7-ruby-3-1-loaderror-cannot-load-such-file-net-smtp
https://github.com/rails/rails/pull/44083

This fix seems easy enough.  Let me do some testing and I put together a new release.

**Comment by blaine07** [comment]
> Hi @blaine07 good to hear from you. It seems that this is due to this issue:
> 
> https://stackoverflow.com/questions/70500220/rails-7-ruby-3-1-loaderror-cannot-load-such-file-net-smtp [rails/rails#44083](https://github.com/rails/rails/pull/44083)
> 
> This fix seems easy enough. Let me do some testing and I put together a new release.

For once im maybe not crazy lol. 

I’ll watch for update. Thank you; all the thanks! :-)

**Comment by pglombardo** [comment]
I just pushed out the fix.  Docker containers v1.17.1 are building now.  They usually take 30-45 minutes.

Could you try this version and let me know if it resolves the errors?

https://github.com/pglombardo/PasswordPusher/releases/tag/v1.17.1
https://github.com/pglombardo/PasswordPusher/actions/runs/2948478152

**Comment by blaine07** [comment]
> I just pushed out the fix. Docker containers v1.17.1 are building now. They usually take 30-45 minutes.
> 
> Could you try this version and let me know if it resolves the errors?
> 
> https://github.com/pglombardo/PasswordPusher/releases/tag/v1.17.1 https://github.com/pglombardo/PasswordPusher/actions/runs/2948478152

Yes mate; absolutely. It’ll be a few hours CST though. :-)

**Comment by blaine07** [comment]
> I just pushed out the fix. Docker containers v1.17.1 are building now. They usually take 30-45 minutes.
> 
> Could you try this version and let me know if it resolves the errors?
> 
> https://github.com/pglombardo/PasswordPusher/releases/tag/v1.17.1 https://github.com/pglombardo/PasswordPusher/actions/runs/2948478152

Sorry, Im a LOT slow today; apologies!

So, it appears, thus far, that everything is working fine/as intended.

All my logs got this time: 

[10] Puma starting in cluster mode...
[10] * Puma version: 5.6.5 (ruby 3.1.2-p20) ("Birdie's Version")
[10] *  Min threads: 5
[10] *  Max threads: 5
[10] *  Environment: production
[10] *   Master PID: 10
[10] *      Workers: 2
[10] *     Restarts: (✔) hot (✖) phased
[10] * Preloading application
[10] * Listening on http://0.0.0.0:5100
[10] Use Ctrl-C to stop
[10] - Worker 0 (PID: 12) booted in 0.01s, phase: 0
[10] - Worker 1 (PID: 15) booted in 0.01s, phase: 0

Which appears...normal?

**Comment by pglombardo** [comment]
That's great.  Thanks for confirming!
