### ISSUE TITLE
Deploying into prod - MySQL error on DB creation

### ISSUE THREAD

**Issue by dnichk** [pglombardo/PasswordPusher#40]
Hi there,

I'm deploying to a production system, and I am running the command:

```
RAILS_ENV=production bundle exec rake db:setup
```
And when I do, I get the following error:
```
-- create_table("passwords", {:force=>true})
rake aborted!
ActiveRecord::StatementInvalid: Mysql::Error: All parts of a PRIMARY KEY must be NOT NULL; if you need NULL in a key, use UNIQUE instead
```
Are there any known issues using mysql?

**Comment by dnichk** [comment]
Maybe I posted too soon. Might be related to [this](https://github.com/rails/rails/pull/13247#issuecomment-32425844} change in mysql.

**Comment by dnichk** [comment]
Alright - for others who might have this issue. Apparently, newer versions of ruby/rails will fix. To bypass you need to have this bit as an initializer in config/initializers/abstract_mysql_adapter.rb:

```
class ActiveRecord::ConnectionAdapters::MysqlAdapter
  NATIVE_DATABASE_TYPES[:primary_key] = "int(11) auto_increment PRIMARY KEY"
end
```

**Comment by dnichk** [comment]
One last thing to note - this file needs to be moved after the database is created - otherwise starting the server will fail. I just backed it up to my home folder.

**Comment by pglombardo** [comment]
This is great info @dnichk thanks!  So just to confirm, no changes are needed for PasswordPusher.  This doesn't happen in latest patches of Rails correct?

**Comment by dnichk** [comment]
@pglombardo - I never tested with a patched version of rails. That was just something I read in the above linked thread. But to get it working I used this abstraction file. This is actually also noted in the Ubuntu deploy guide I'm writing as well.

**Comment by pglombardo** [comment]
Hi @dnichk - closing up this issue.  If there is any issue remaining - feel free to re-open or file another issue.
