### ISSUE TITLE
Prevent braking changes to settings.yml by providing default values

### ISSUE THREAD

**Issue by mtchetch** [pglombardo/PasswordPusher#400]
The new changes to settings.yml that added support for branding and theming options cause the app to return error 500 if the variables are not there.

In my installation settings.yml is moved to a local volume to preserve settings when updating the image so the file did not have the new theming variables and the app failed to load.

**Comment by pglombardo** [comment]
Do you still have a copy of the error?

Those settings should default to `nil` if not set but likely I missed something.

**Comment by mtchetch** [comment]
I do not have a copy of the error, but I do have the old setting-file that can be used to duplicate the issue. I sensured some things about our setup  and replaced them with sensured.com:

`# Global Application Configuration

# See also https://github.com/pglombardo/PasswordPusher/blob/master/Configuration.md
# for a further explanation of the larger settings available here.

# Logins are disabled by default since they require an MTA (email) server
# available to send emails through.
#
# For instructions on how to enable logins, see this page:
# https://github.com/pglombardo/PasswordPusher/discussions/276
#
# Environment variable override:
# PWP__ENABLE_LOGINS='false'
#
enable_logins: true

# By default, Password Pusher can be used by anonymous users to push
# new passwords and generate secret URLs.  If you want to limit functionality
# to logged in  users only, set the following value to true.
#
# This does not affect password secret URLs themselves as anonymous is always
# allowed there.
#
# Environment variable override:
# PWP__ALLOW_ANONYMOUS='true'
#
allow_anonymous: true

# The domain (without protocol) where this instance is hosted
# Used in generating fully qualified URLs.
#
# Environment variable override:
# PWP__HOST_DOMAIN='pwpush.com'
#
host_domain: 'sensured.com'

# The protocol to reach the domain above
# Used in generating fully qualified URLs.
#
# Environment variable override:
# PWP__HOST_PROTOCOL='https'
#
host_protocol: 'https'

# Set the following value to force the base URL of generated links.
#
# Environment variable override:
# PWP__OVERRIDE_BASE_URL='https://pwpush.mydomain.com'
#
# You could even add a port if needed:
# PWP__OVERRIDE_BASE_URL='https://pwpush.mydomain.com:5100'
#
# Set this value without a trailing slash ('/').
#
override_base_url: 'https://sensured.com'


# Configure the application throttling limits.
#
# Throttling enforces a minimum time interval
# between subsequent HTTP requests from a particular client, as
# well as by defining a maximum number of allowed HTTP requests
# per a given time period (per minute, hourly, or daily).
#
# See https://github.com/dryruby/rack-throttle#throttling-strategies
# for a description of function.
#
throttling:
  # ..maximum number of allowed HTTP requests per day
  #
  # Default: 1000
  #
  # Environment Variable Override: PWP__THROTTLING__DAILY='1000'
  daily: 1000

  # ..maximum number of allowed HTTP requests per hour
  #
  # Default: 100
  #
  # Environment Variable Override: PWP__THROTTLING__HOURLY='100'
  hourly: 100

  # ..maximum number of allowed HTTP requests per minute
  #
  # Default: 30
  #
  # Environment Variable Override: PWP__THROTTLING__MINUTE='30'
  minute: 30

  # ..maximum number of allowed HTTP requests per second
  #
  # Default: 2
  #
  # Environment Variable Override: PWP__THROTTLING__SECOND='2'
  second: 2


# When logins are enabled, an SMTP server is required to send emails to users
# for things such as forgot password, unlock account, confirm account etc.
# If `enable_logins` is set to true above, the following _are required_ to be
# filled out with valid values.
mail:
  # Email delivery errors will be shown in the application
  # Environment Variable Override: PWP__MAIL__RAISE_DELIVERY_ERRORS='false'
  raise_delivery_errors: true

  # Allows you to use a remote mail server. Just change it from its default "localhost" setting.
  # Environment Variable Override: PWP__MAIL__SMTP_ADDRESS='smtp.example.com'
  smtp_address: sensured.com

  # If your mail server requires authentication, set the username in this setting.
  # Environment Variable Override: PWP__MAIL__SMTP_USER_NAME='apikey'
  # smtp_user_name: 'apikey'

  # If your mail server requires authentication, set the password in this setting.
  # Environment Variable Override: PWP__MAIL__SMTP_PASSWORD='something@&#$'
  # smtp_password: ''

  # Port of the SMTP server
  # Environment Variable Override: PWP__MAIL__SMTP_PORT='587'
  smtp_port: 25

  # If your mail server requires authentication, you need to specify the
  # authentication type here. This is a string and one of :plain (will send
  # the password in the clear), :login (will send password Base64 encoded)
  # or :cram_md5 (combines a Challenge/Response mechanism to exchange
  # information and a cryptographic Message Digest 5 algorithm to hash
  # important information)
  # Environment Variable Override: PWP__MAIL__SMTP_AUTHENTICATION='plain'
  smtp_authentication: 'none'

  # Use STARTTLS when connecting to your SMTP server and fail if unsupported.
  # Environment Variable Override: PWP__MAIL__SMTP_STARTTLS='true'
  smtp_starttls: false

  # Number of seconds to wait while attempting to open a connection.
  # Environment Variable Override: PWP__MAIL__SMTP_OPEN_TIMEOUT='10'
  smtp_open_timeout: 10

  # Number of seconds to wait until timing-out a read(2) call.
  # Environment Variable Override: PWP__MAIL__SMTP_READ_TIMEOUT='10'
  smtp_read_timeout: 10

  # Configure the e-mail address which will be shown as 'From' in emails
  # See config/initializers/devise.rb where this is used
  # Environment Variable Override: PWP__MAIL__MAILER_SENDER='"Password Pusher" <pglombardo@pwpush.com>'
  mailer_sender: '"Password Pusher" <sites@sensured.com>'

# List of supported languages indexed by language code.  This is used
# to build the in application language menu.
#
# <language code>: '<language name>'
language_codes:
  ca: 'Català'
  cs: 'Čeština'
  da: 'Dansk'
  de: 'Deutsch'
  en: 'English'
  es: 'Español'
  fi: 'Suomi'
  fr: 'Français'
  hu: 'Magyar'
  it: 'Italiano'
  nl: 'Nederlands'
  'no': 'Norsk' # _no_ keyword in Ruby evaluates to false :-(
  pl: 'Polski'
  'pt-BR': 'Português'
  sr: 'Српски'
  sv: 'Svenska'

# The default language for the application.  This must be one of the
# valid/supported language codes from the list above.
#
# Example: default_locale: :es
#
# Environment Variable Override: PWP__DEFAULT_LOCALE='es'
default_locale: :en`

**Comment by pglombardo** [comment]
The fix for this has been merged and is building now in container v1.17.6.  Thanks for reporting this!

**Comment by pglombardo** [comment]
Hi @mtchetch - this should be closed.  Let me know if otherwise.
