### ISSUE TITLE
Feature Request: Limit account registration to specific domain

### ISSUE THREAD

**Issue by cameronbrister** [pglombardo/PasswordPusher#405]
It'd be awesome if we could restrict account registration to a specific domain to ensure that only internal users are able to create an account on our self-hosted instance.

**Comment by TargetCrafter** [comment]
This, together with limiting signups to the local networks would be awesome. Much better than creating a user and then disabling sign-ups again. Any progress on this?

**Comment by pglombardo** [comment]
Thanks for the reminder.  Added the feature in: https://github.com/pglombardo/PasswordPusher/pull/1283

Documentation from the `settings.yml`:

<img width="632" alt="Screenshot 2023-07-26 at 16 33 49" src="https://github.com/pglombardo/PasswordPusher/assets/395132/900d9ce0-7035-40d1-831e-7968cd3fb698">

I'll try to release this soon.

**Comment by TargetCrafter** [comment]
Good to hear. I did notice that users without email verification can create pushes too, so that makes this less useful as someone can just create a user with the domain like "H8WQK36J4VL@example.com" and start creating pushes. Even if that email doesn't exist. Should i create a separate issue for this?

**Comment by pglombardo** [comment]
I'll add the option to require verification before login is allowed.  I'll mostly likely get to this over the weekend.

**Comment by pglombardo** [comment]
This has been added and released in [v1.30.0](https://github.com/pglombardo/PasswordPusher/releases/tag/v1.30.0).  Thanks all for the feature request and input!

Documentation is in [Configuration.md](https://github.com/pglombardo/PasswordPusher/blob/master/Configuration.md#enabling-logins) and in the [config/settings.yml](https://github.com/pglombardo/PasswordPusher/blob/master/config/settings.yml#L66-L91) file
