### ISSUE TITLE
FORCE_SSL = true causes "SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol"

### ISSUE THREAD

**Issue by desertmoose706** [pglombardo/PasswordPusher#406]
I'm trying to resolve an issue where the pwpush redirects to an http:// url when I click "Push It" button. In my scenario, pwpush is deployed as ephemeral to an EKS cluster and fronted with an F5. The F5 handles TLS termination and we're accessing the site as https://pwpush.somedomain.com/. Backend, between the F5 and the pod, I don't necessarily need it to be HTTPS.

That said, if I set the FORCE_SSL environment var and re-deploy, then I get SSL error response from the pod. e.g.:
❯ curl https://10.10.10.199:5100/
curl: (35) error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
At this point, curl to http:// produces no response.

I'm using the PWP__OVERRIDE_BASE_URL env var, but that only fixes the link generated, not the URL used when the form is submitted.

Is this an issue with my specific environment / config? I see the previous issue around this topic was closed and users stating that FORCE_SSL fixed theirs.

Also, is it possible to add another override for the submit URL, e.g. PWP__OVERRIDE_FORM_URL ? or have the form use the PWP__OVERRIDE_BASE_URL var?

**Comment by pglombardo** [comment]
This is a fairly normal setup.  SSL termination point out front, HTTP communication from F5 to pwpush.

The first and best solution is to make sure your F5 is sending the `X-Forwarded-*` headers.  This is documented [here](https://github.com/pglombardo/PasswordPusher/blob/master/Configuration.md#proxies).

If you can't do that, then the fall back is environment variables to just force a blind protocol://url base.

> That said, if I set the FORCE_SSL environment var and re-deploy, then I get SSL error response from the pod. e.g.:
> ❯ curl https://10.10.10.199:5100/
> curl: (35) error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol

Port 5100 isn't an SSL termination point so direct `https://` there won't work ever.

> At this point, curl to http:// produces no response.

`curl http://10.10.10.199:5100/` should work if that is where your container:port is hosted/bound.

I would scrap FORCE_SSL and PWP__OVERRIDE_BASE_URL and try the `X-Forwarded-*` headers first.

Longer term, FORCE_SSL will be deprecated any case.  PWP__OVERRIDE_BASE_URL will be the lone backup if  headers aren't an option.

Could you try the headers and let me know?

**Comment by pglombardo** [comment]
If you need it, found this config rule for an F5.  See last comment in thread: https://community.f5.com/t5/technical-forum/x-forwarded-in-f5/td-p/30474

It's important to have all three `X-Forwarded-*` headers.  `-Port` might be optional but it's best to test.

**Comment by desertmoose706** [comment]
Hi Peter,
Setting the X-Forwarded-Proto in particular is what fixed my specific issue. Thanks for the detailed response.

**Comment by pglombardo** [comment]
Excellent!
