### ISSUE TITLE
Modifying color scheme / layout

### ISSUE THREAD

**Issue by chachtastic** [pglombardo/PasswordPusher#43]
PWPUSH is awesome! Such a life/timesaver!

I'm working on adding a different color scheme / layout to the page, however running into issues when doing so. Can you specify which css file(s) should be modified to accomplish this?

Also, I noticed when updated the css, the old pages get pulled from /tmp/cache and don't reflect the changes. Is this typical behavior or should there be a different way to refresh each time, other than removing these files? 

Much appreciated, thank you!!!!
-Jon

**Comment by chachtastic** [comment]
Disregard! I re-read the notes and instructions a little more and figured it out. Thank you!

**Comment by pglombardo** [comment]
Great to hear on everything!

**Comment by Viajaz** [comment]
@pglombardo I know this is old but I can't find any notes/instructions relevant to CSS restyling

**Comment by pglombardo** [comment]
This is not guaranteed to work like this forever but if you change [this line](https://github.com/pglombardo/PasswordPusher/blob/master/app/frontend/js/bootstrap_js_files.js#L19), it modifies the CSS theme name.  There are 4 themes installed.

I definitely could install some more themes and make them selectable via environment variable.  They aren't perfect though and there may be visual bugs.

![Screenshot 2022-09-30 at 10 29 46](https://user-images.githubusercontent.com/395132/193228646-4d0c9f9d-bf60-4d30-a3d9-9236d51e08dc.png)

The pre-installed CSS themes are [here](https://github.com/pglombardo/PasswordPusher/tree/master/app/frontend/css).   `Litera` is the default.

**Comment by pglombardo** [comment]
Hi all - you might be interested in these [custom theme instructions](https://github.com/pglombardo/PasswordPusher/issues/762#issuecomment-1416718368).

It's a short term work around for eventual selectable themes.

**Comment by pglombardo** [comment]
Just an update that as of v1.26.10 Password Pusher now

* comes with [26 themes](https://github.com/pglombardo/PasswordPusher/blob/master/Themes.md#theme-gallery) bundled in selectable by environment variable
* also supports [custom CSS](https://github.com/pglombardo/PasswordPusher/blob/master/Configuration.md#how-to-add-custom-css)
* supports [entirely custom themes](https://github.com/pglombardo/PasswordPusher/blob/master/Configuration.md#adding-an-entirely-new-theme-from-scratch)

With this framework and foundation, we'll be able to make sure that future changes don't break any existing user customisations.

If there are any questions or issues, please let me know!
