### ISSUE TITLE
Default values of password generator

### ISSUE THREAD

**Issue by DominikZublasing** [pglombardo/PasswordPusher#435]
Hello, I would like to know if there is currently a way to change the default values of the password generator (application wide).

**Comment by pglombardo** [comment]
Not yet - but soon... 

 <img src="https://media1.giphy.com/media/603cLZVdYomSgIBhB0/giphy.gif"/>

**Comment by pglombardo** [comment]
First pass at fixing this - in progress...

**Comment by pglombardo** [comment]
Hi all - this has been added.  The settings are available in [config/settings.yml](https://github.com/pglombardo/PasswordPusher/blob/mast) or via [environment variables](https://github.com/pglombardo/PasswordPusher/blob/master/Configuration.md#password-generator-settings).

Thanks for pointing this out.  Let me know if you have any issues using this.
