### ISSUE TITLE
PWP__DISABLE_SIGNUPS docker env variable not working

### ISSUE THREAD

**Issue by pyramidofgreatness** [pglombardo/PasswordPusher#439]
I created a docker new instance of Pwpush running the latest release, with postgres backend.

Created my users, then set the env variable PWP__DISABLE_SIGNUPS to true.

Restarted the container. But the "Sign Up" link is still present, and I'm able to create a new user.

Any ideas?

**Comment by pglombardo** [comment]
Hi @pyramidofgreatness - I just re-tested this and it's working correctly for me.

![Screenshot 2022-10-21 at 11 11 43](https://user-images.githubusercontent.com/395132/197159836-7893bec7-7a92-40af-bcbe-1d76c22ac0d5.png)

Possibly you have to re-pull the `latest` tag again?

As an alternative, try the same with tag [v1.17.8](https://github.com/pglombardo/PasswordPusher/releases/tag/v1.17.8).  That versioned tag is the latest and has the feature bundled in.

Let me now how things progress.

**Comment by pyramidofgreatness** [comment]
Thanks. Latest tag fixed it. I was running release from the postgres package one liner.
