### ISSUE TITLE
Configuring SSL

### ISSUE THREAD

**Issue by jonathanpuebla** [pglombardo/PasswordPusher#44]
Hi!
I'm having some issues enabling SSL on my production server. Apologies for the noobish question but are there any additional steps besides adding the config.force_ssl = true line to production.rb? It still only responds to the 5000 port number. 
Thanks!

**Comment by pglombardo** [comment]
Hi @jonathanpuebla - that `force_ssl` is really the last step to force the app to prefer/redirect traffic over to port 443.  I'm not sure how far you've gotten but you have to setup Apache or Nginx in front of the app with the SSL certificate for this to work.  There is a bit to this if you haven't done it before but once setup it works really well.

Here is a DO guide that may help:
https://www.digitalocean.com/community/tutorials/how-to-install-rails-and-nginx-with-passenger-on-ubuntu

Again, I'm not sure how far you've gotten.  You may already be past this point and hitting some other issue.  Let me know in either case!

Best,
Peter

**Comment by chachtastic** [comment]
Thanks @pglombardo ! I set up the SSL certs along with Nginx but I'm only still getting a Welcome to nginx splash page on 80, and nothing when I use https. I've also modified my /etc/nginx/nginx.conf file to point to what I believe are the correct entries.

`server {
       listen 80;
       server_name pwp1.myserver.com;
       rails_env production;
       root /home/pwpadm/PWPusher;
       passenger_enabled on;
}
    server {
       listen 443 default;
       ssl on;
       ssl_certificate     /home/pwpadm/PWPusher/ca.crt;
       ssl_certificate_key /home/pwpadm/PWPusher/ca.key;
       proxy_set_header X-Forwarded-Proto $scheme;
       server_name ny-pwp1.ad.hugeinc.com;
       rails_env production;
       root /home/pwpadm/PWPusher;
       passenger_enabled on;
}
`
Any additional thoughts or ideas here?

**Comment by pglombardo** [comment]
I _believe_ you have to point `root` to the public directory for passenger:

    root /home/pwpadm/PWPusher/public;

(on both entries)

**Comment by pglombardo** [comment]
Hey @jonathanpuebla @chachtastic did you guys have any luck on this?

**Comment by chachtastic** [comment]
Thanks for following up! Turns out I was modifying the wrong nginx.conf file (/opt/nginx/conf/nginx.conf), and I should have been modifying /etc/nginx/nginx.conf. Only issue now is I get a 403 forbidden when i attempt to load the page with http, and a generic error message related to Phusion Passenger when I attempt to load https.

**Comment by pglombardo** [comment]
Yeah always a bit of a hassle to set this stuff up initially.  Double check that root entry above that I noted - I'm almost sure that it has to point to the public directory.

**Comment by pglombardo** [comment]
Closing up this issue for now.  If anything remains, feel free to re-open or open another issue.
