### ISSUE TITLE
Auditlog missing information about the push creator

### ISSUE THREAD

**Issue by mtchetch** [pglombardo/PasswordPusher#449]
Probably a minor issue, but since we have a working audit log system, it should contain info on the push creator as well as the people accessing the push.

![image](https://user-images.githubusercontent.com/11362763/198234832-1362fa0c-12c7-438f-9d4b-8b6c87985795.png)

I would rate this as a low priority issue.

**Comment by pglombardo** [comment]
Hey @mtchetch,  here is one of my audit logs:

![Screenshot 2022-10-27 at 11 08 27](https://user-images.githubusercontent.com/395132/198243100-1c591dbb-807c-4d4d-8b13-1a8ef089f391.png)

If you click that `Expire Now` button you should even get:

![Screenshot 2022-10-27 at 11 10 09](https://user-images.githubusercontent.com/395132/198243401-0b3d2761-9b96-4f0c-91bf-a130e2b789d8.png)

You have no audit logs?

**Comment by mtchetch** [comment]
I have audit logs that are the same as yours. My point was that there should be information saved about the person that created the push in the first place. Instead just having a push created line, there should be IP, referrer and agent information on the creator as well as maybe info if the push was created using the API or the web UI.

**Comment by pglombardo** [comment]
Ah ok got it!  Good point - this will be helpful when I add teams too.

**Comment by pglombardo** [comment]
Hi @mtchetch - this has been added.

![Screenshot 2023-01-14 at 17 43 00](https://user-images.githubusercontent.com/395132/212484327-7dad625f-5b10-4239-86cb-58b42776409e.png)

Audit logs will be expanded even further eventually once I get extended logins and teams added...

**Comment by mtchetch** [comment]
> Hi @mtchetch - this has been added.
Excellent job @pglombardo It is good to see that progress is being made even after so many years developing the app.
