### ISSUE TITLE
possible to change password creation policy?

### ISSUE THREAD

**Issue by 4001982248998** [pglombardo/PasswordPusher#466]
Hi,

I am truly sorry if this has been asked before (I haven't found anything), but would it be possible to preconfigure a different password length? I'd like to follow a certain password policy.

Thank you!

**Comment by pglombardo** [comment]
To make it application wide and the default for all users - not yet.  I have this planned and a feature request is in #435.

The hacky work-around for the time being is to update/modify/replace [this file](https://github.com/pglombardo/PasswordPusher/blob/master/app/frontend/js/pw_generator.js#L19-L29)

You can replace the file in the docker container with a bind mount option:
--mount type=bind,source=/path/pw_generator.js,target=/opt/PasswordPusher/app/frontend/js/pw_generator.js

That _should_ work but I haven't tested it myself.

I'll see if I can add `settings.yml` settings and environment variables for these options soon.

**Comment by 4001982248998** [comment]
Hi, thank you for all your efforts. I (think I) created a bind mount like you recommended, but unfortunately I do not see changes in the web service. As I am not very experienced with container images, this might stem from poor skills on my side. All the more I'd applaud proper settings for a password policy.

By changing into the container's context, I verified that the file really was changed in the container, so that should have been working.

**Comment by pglombardo** [comment]
First pass at adding configurability - in progress...

**Comment by pglombardo** [comment]
Hi @4001982248998 I'm late on updating this but this feature has been added.  The settings are available in [config/settings.yml](https://github.com/pglombardo/PasswordPusher/blob/mast) or via [environment variables](https://github.com/pglombardo/PasswordPusher/blob/master/Configuration.md#password-generator-settings).

Thanks for pointing this out.  Let me know if you have any issues using this.

If anything remains, please let me know.
