### ISSUE TITLE
Add automatic background job runs to Docker containers

### ISSUE THREAD

**Issue by pglombardo** [pglombardo/PasswordPusher#468]
The application can preemptively expire and clean up pushes.  This is done daily on pwpush.com in a hacky automated fashion.

The two tasks are (run from the command line):

1. `rake daily_expiration`
2. `rake delete_expired_and_anonymous`

We can add the automated run of these tasks by adding cron to the Docker containers and using the [whenever](https://github.com/javan/whenever) gem to schedule the daily task.

**Comment by ivancarlosti** [comment]
A kindly reminder or workaround to have it ;)

**Comment by pglombardo** [comment]
I've started this 3 times before getting interrupted every time. :-)

I will get to this soon.  In the meantime, you can run the tasks as cron jobs:
<img width="1053" alt="Screenshot 2024-10-03 at 08 45 19" src="https://github.com/user-attachments/assets/71a4b5a8-b2c6-47d3-b6e3-fb88875354ac">

**Comment by pglombardo** [comment]
#2601 is in progress.  This will add a new Docker container dedicated at running background tasks.  Thanks for the nudge!

**Comment by pglombardo** [comment]
The `pwpush-worker` docker container image is out (quietly).  Once it stabilizes, get enough feedback and write documentation I'll make a larger announcement.

https://hub.docker.com/r/pglombardo/pwpush-worker/tags
