### ISSUE TITLE
spellcheck='false' for textarea "password_payload"

### ISSUE THREAD

**Issue by mamind1** [pglombardo/PasswordPusher#475]
It is already applied to some other input fields, but the main input field (where user paste or type their passwords) should also contain the attribute spellcheck='false'

- https://www.otto-js.com/news/article/spell-jacking-enhanced-spellcheck-features-send-pii-even-passwords
- https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/spellcheck

**Comment by pglombardo** [comment]
Good point - I'll see if I can update this soon.  Thanks!

**Comment by pglombardo** [comment]
Hi @mamind1 - I've added the `spellcheck` field to the text area in [release v1.20.0(https://github.com/pglombardo/PasswordPusher/releases/tag/v1.20.0).  New Docker containers are building now.  Thanks for pointing this out!
