### ISSUE TITLE
Environment Variable to Toggle Password Blur/Spoiler

### ISSUE THREAD

**Issue by Viajaz** [pglombardo/PasswordPusher#486]
It would be useful to have an environmental variable (Eg: `PWP__ENABLE_PASSWORD_BLUR`) to toggle the Password blur/spoiler:
https://github.com/pglombardo/PasswordPusher/blob/master/app/frontend/js/passwords.js#L113 ?

This can improve UX by reducing the number of clicks a end-user has to make, especially if one is already using the "1-click retrieval step". One could assume if the end-user has already used "Click Here to View the Password" they have already considered the risk of shoulder surfing that the password blur/spoiler is designed to mitigate.

**Comment by pglombardo** [comment]
Hi @Viajaz - I'll see if I can add this soon.  It shouldn't be much work.

**Comment by Viajaz** [comment]
Any luck with this @pglombardo ?

**Comment by pglombardo** [comment]
Hi @Viajaz - done in #845.  I'll see if I can merge/release it soon.  The environment variable will be `PWP__PW__ENABLE_BLUR` with a default of true.
