### ISSUE TITLE
Is it possible to host google fonts locally?

### ISSUE THREAD

**Issue by sirux88** [pglombardo/PasswordPusher#653]
## Checklist

- [x] I've searched the project's [`issues`](https://github.com/pglombardo/pwpush/issues?q=is%3Aissue).
- [x] I've searched the project's [`discussions`](https://github.com/pglombardo/PasswordPusher/discussions).

## ❓ Question

According to an decision of a german regional court (https://gdprhub.eu/index.php?title=LG_M%C3%BCnchen_-_3_O_17493/20) using google font interferes with EU GDPR.

To get around this problem it should be fine using google font locally.

To do so in it's necessary to download google font and some css content.
Next step would be to include the css content and reference the downloaded content.

https://gwfh.mranftl.com/fonts helps downloading the fonts and prepare the css content

So my question is, is there a chance to use google fonts locally within password pusher?

**Comment by pglombardo** [comment]
That is helpful information @sirux88.  Give me some time to look into this.  I'll post back soon.

**Comment by pglombardo** [comment]
This change is included in [v1.23.9](https://github.com/pglombardo/PasswordPusher/releases/tag/v1.23.9) which is building now.

Thanks for pointing this out @sirux88!

**Comment by sirux88** [comment]
You're welcome @pglombardo.

Thank you for implementing the necessary changes that fast.
Now i can use password pusher without any fear of getting a fee.
