### ISSUE TITLE
Assets ActiveStorage 404

### ISSUE THREAD

**Issue by Viajaz** [pglombardo/PasswordPusher#656]
## Checklist
- [x] I've searched the project's [`issues`](https://github.com/pglombardo/pwpush/issues?q=is%3Aissue).
- [x] I've searched the project's [`discussions`](https://github.com/pglombardo/PasswordPusher/discussions).

## ❓ Question
Browser reports:
`Loading module from “https://pwpush.example.com/assets/activestorage” was blocked because of a disallowed MIME type (“text/html”).`
-because it results in error 404. This breaks the web-app.

I'm using PasswordPusher in Docker with a NGINX reverse proxy, I'm assuming I need to reconfigure it to support this path but I'm not familiar with RoR ActiveStorage and it's requirements.

Tried using the following NGINX location configs:
_With WebSocket Support_
```
location /assets/ {
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Host $host;
    proxy_set_header Connection $connection_upgrade;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_pass http://docker-pwpush;
  }
```
or without
```
location /assets/ {
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_pass http://docker-pwpush;
  }
```

**Comment by pglombardo** [comment]
Hi @Viajaz - I'm not sure at first glance.  Is Nginx setting the ContentType request header anywhere?

Let me give this some thought.  

The documentation for Active Storage [is here](https://edgeguides.rubyonrails.org/active_storage_overview.html) if you want to take a look.  It talks about proxying but that is referring to e.g. S3 files proxied through the application server...  not Nginx style proxying...

Do you have anymore related logs that you could post?  Nginx, browser console and/or pwpush app server?

**Comment by Viajaz** [comment]
The browser makes a HTTP request for `https://pwpush.example.com/assets/activestorage` which fails with 404, that's the crux of the issue.

**Comment by pglombardo** [comment]
Hi @Viajaz - [v1.23.10](https://github.com/pglombardo/PasswordPusher/releases/tag/v1.23.10) which is building now fixes a Javascript issue with active storage.  This may resolve this issue.

**Comment by Viajaz** [comment]
Issue appears fixed, thank you.
