### ISSUE TITLE
A better local install method

### ISSUE THREAD

**Issue by pglombardo** [pglombardo/PasswordPusher#66]
Instead of:
```
git clone git@github.com:pglombardo/PasswordPusher.git
cd PasswordPusher
gem install bundler
bundle install --without development production test --deployment
bundle exec rake assets:precompile
RAILS_ENV=private bundle exec rake db:setup
foreman start internalweb

Then view the site @ http://localhost:5000/.
```

we should provide a ruby executable to do this in one step.  So the resulting instructions would be:

```
git clone git@github.com:pglombardo/PasswordPusher.git
cd PasswordPusher
./bin/run_private

Then view the site @ http://localhost:5000/.
```

That script can/should also:

1. Validate Ruby version
2. Existence of required base gems (e.g. bundler)
etc...

**Comment by alexeygolikov** [comment]
docker

**Comment by pglombardo** [comment]
We have a Dockerfile posted onto a branch.  I need to put it on master: https://github.com/pglombardo/PasswordPusher/blob/pwpush.com/Dockerfile

...And we're on [Docker hub](https://hub.docker.com/r/pglombardo/passwordpusher/).  I need to put this in the README - thanks for pointing this out!

**Comment by pglombardo** [comment]
https://github.com/pglombardo/PasswordPusher/issues/78

**Comment by pglombardo** [comment]
Docker containers are now the preferred installation method.  The local install method is suggested only for local development.

https://hub.docker.com/u/pglombardo
