### ISSUE TITLE
SMTP Open SSL Verify Mode - None

### ISSUE THREAD

**Issue by chadniko** [pglombardo/PasswordPusher#718]
## 🐛 Bug Report

Have an internal mail server setup with self-sign cert to accept relays from LAN. So in PWP I have (I think...) set it up to bypass the cert verify.  I still get an error in the log when accessing the mailserver:
6777931a-048a-49f1-9e19-b736196e2228] OpenSSL::SSL::SSLError (SSL_connect returned=1 errno=0 peeraddr=10.10.1.10:25 state=error: certificate verify failed (self signed certificate)):

Using an environment variable in docker-compose to bypass the cert:
Output of env:
pwpusher@e5eb33283f94:~/log$ env|grep PWP
PWP__MAIL__SMTP_OPENSSL_VERIFY_MODE=none

Docker compose file:
```dockerfile
services:
  pwpush:
    image: docker.io/pglombardo/pwpush-postgres:latest
    #    ports:
    #  - "5100:5100"
    volumes:
      - ./settings.yml:/opt/PasswordPusher/config/settings.yml
    environment:
      PWP__MAIL__SMTP_OPENSSL_VERIFY_MODE: "none"
    depends_on:
      - postgres
    links:
      - postgres:postgres
    restart: unless-stopped
  postgres:
    image: docker.io/postgres:10
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
        #ports:
        #- "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: passwd
      POSTGRES_DB: pwpdb
    restart: unless-stopped
networks:
   default:
     name: npmnet
     external: true
```

I'm thinking it's operator error somewhere as this was fixed in #386 a while ago.
Maybe a fresh set of eyes can help me.
TIA

**Comment by pglombardo** [comment]
Hi @chadniko - everything looks correct.  Could you shell into the pwpush-postgres container (`docker exec -it <containerId> /bin/bash`) and run:

```ruby
bin/rails console
Rails.application.config.action_mailer.smtp_settings
```

You should see `:openssl_verify_mode=>:none` in the output...  could you confirm?

**Comment by chadniko** [comment]
@pglombardo - I've shelled into the pwpush-postgres container  using portainer and there is no /bin/rails executable  and nowhere else within the path...
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/postgresql/10/bin
_=/usr/bin/env

**Comment by chadniko** [comment]
Seems I misunderstood which container...in  the pwpush container  and not the postgres container I see:
:openssl_verify_mode=>:none}

**Comment by pglombardo** [comment]
Hrm that's odd...

This error came from the pwpush-postgres container?

```
6777931a-048a-49f1-9e19-b736196e2228] OpenSSL::SSL::SSLError (SSL_connect returned=1 errno=0 peeraddr=10.10.1.10:25 state=error: certificate verify failed (self signed certificate)):
```

Did this ever work for you or was this a recent break?

**Comment by chadniko** [comment]
Yes the error is in the production.log.  I'm a new user and I have been unable to get the mail to work. The local smtp is setup to not require authentication for a lan client on port 25...I have also tried with mail auth on port 587 and still get the same error even with the  verify mode set to none.   Here is the output from rails console for smtp settings:
{:address=>"10.10.1.10",                                
 :port=>25,                                                           
 :user_name=>"",
 :password=>"",
 :authentication=>"plain",
 :enable_starttls_auto=>nil,
 :open_timeout=>10,
 :read_timeout=>10,
 :openssl_verify_mode=>:none}
Could also try to relay thru my ISP email to see if that works.

**Comment by pglombardo** [comment]
I'm not sure what the issue is.  I haven't had any other reports of this.

Could you open that console in the pwpush container again, confirm the settings:

```ruby
bin/rails console
Rails.application.config.action_mailer.smtp_settings
```

Then run this code snippet to manually send an email.  Replace those email addresses with something valid:

```ruby
Mail.deliver do
  to 'your@email.com'
  from 'your@email.com'
  subject 'testing mail'
  body 'testing mail'
end
```

Could you let me know what the output is.  And did you get the email?

**Comment by chadniko** [comment]
No email sent and here's the output:
/usr/local/lib/ruby/3.2.0/socket.rb:1217:in `__connect_nonblock': Cannot assign requested address - connect(2) for [::1]:25 (Errno::EADDRNOTAVAIL)
After googling I think I may have a config problem somewhere and probably related to my setup.  With the ruby console commands you gave me I can investigate this further and report back as it may help someone with a similar setup. Docker running  on an Ubuntu LXC under Proxmox and PWP reverse proxied thru Nginx Proxy Manager on the same LXC.
No need to further waste your time ---- Thanks for your help and support!!!!!

**Comment by chadniko** [comment]
I think that #754,  #755 and #718 all have the same underlying issue.
Tried  the command:
ruby -e 'require "socket"' -e "TCPSocket.open('10.10.1.10', 25)"
and it just returns back to the command prompt for me....

**Comment by chadniko** [comment]
So like @tesudacochino I went for a different setup this time using an Ubuntu 20.04 VM (under Proxmox) docker host and also has my lan mailserver ---a mailcow docker instance....I'm getting the same results as with my Ubuntu 20.04 LXC docker host.

**Comment by chadniko** [comment]
FYI, tried various docker images all the way back to 1.17.1 and this issue exists in all of them that I tried.

**Comment by pglombardo** [comment]
I agree with your analysis.  I just haven't found the root cause to trigger this issue yet.  Then at the same time, there is a large community of users that use email and haven't reported any issues (e.g. not global) and pwpush.com email is still working (and has been working since day 1/pre `1.17.1`).

Then 3 identical email issues come in at once.  :-)

So reducing the problem area like we've been going is the right approach.  I'll take another shot at investigating this later today likely.

**Comment by chadniko** [comment]
I finally was able to send emails with PWP using an external mailjet server with a good cert---so the verify mode was commented out and not active.....Once I reenable with : PWP__MAIL__SMTP_OPENSSL_VERIFY_MODE: none 
PWP throws a #500 error  and the log file shows:
, [2023-01-30T01:08:32.224696 #348] FATAL -- : [77c870b7-b3e2-46b0-9e7a-404d9f6c56ef]   
[77c870b7-b3e2-46b0-9e7a-404d9f6c56ef] TypeError (no implicit conversion of Symbol into Integer):
[77c870b7-b3e2-46b0-9e7a-404d9f6c56ef]   
[77c870b7-b3e2-46b0-9e7a-404d9f6c56ef] net-smtp (0.3.3) lib/net/smtp.rb:681:in `initialize'
[77c870b7-b3e2-46b0-9e7a-404d9f6c56ef] net-smtp (0.3.3) lib/net/smtp.rb:681:in `new'
[77c870b7-b3e2-46b0-9e7a-404d9f6c56ef] net-smtp (0.3.3) lib/net/smtp.rb:681:in `ssl_socket'
[77c870b7-b3e2-46b0-9e7a-404d9f6c56ef] net-smtp (0.3.3) lib/net/smtp.rb:686:in `tlsconnect'
[77c870b7-b3e2-46b0-9e7a-404d9f6c56ef] net-smtp (0.3.3) lib/net/smtp.rb:666:in `do_start'
[77c870b7-b3e2-46b0-9e7a-404d9f6c56ef] net-smtp (0.3.3) lib/net/smtp.rb:611:in `start'
Seems like the option is not getting passed correctly and when I google:
ruby "smtp" TypeError (no implicit conversion of Symbol into Integer)

I see some results about rails string handling....Not a rails guy but seems like this may be a clue....Hope this is helpful.

**Comment by pglombardo** [comment]
That's likely the culprit then.  Thanks for investigating @chadniko.  I'll get back to this code soon and put in a fix.

**Comment by pglombardo** [comment]
Hi @chadniko - I just released [1.25.6](https://github.com/pglombardo/PasswordPusher/releases/tag/v1.25.6) that includes a [mail system update](https://github.com/pglombardo/PasswordPusher/pull/789) that claims:

> Bug Fixes:
> Regression: sendmail accepts string :arguments ([@​sebbASF](https://github.com/sebbASF))
> Regression: accept enable_starttls_auto: false [@​ahorek](https://github.com/ahorek)

A regression in that library would explain this change of behavior despite no changes in Password Pusher.  Let's see if this has any affect for you.  1.25.6 is building now.

I'm hoping this also resolves the other two issues you linked as well.

**Comment by chadniko** [comment]
@pglombardo - I pulled the above version (-also the latest) and it still has the above issue when setting:
PWP__MAIL__SMTP_OPENSSL_VERIFY_MODE: none
but works when I comment this out in docker-compose file:     
 #      PWP__MAIL__SMTP_OPENSSL_VERIFY_MODE: none

did not check any of the other related issues yet.

**Comment by chadniko** [comment]
@pglombardo -----  @kuehnel-net's workaround also works for my configuration.  Turning off this option seems to get rid of the mail issues.....

**Comment by pglombardo** [comment]
Excellent - I'll use these issues going forward if anyone else reports similar.  As for the root cause - I still don't know.  Something changed in the dependent mail library.  Thanks for staying on top of this!

**Comment by pglombardo** [comment]
If nothing remains here, I'll close out this issue.
