### ISSUE TITLE
Git Clone access denied.

### ISSUE THREAD

**Issue by CBB3810** [pglombardo/PasswordPusher#769]
## Checklist

- [ x] I've searched the project's [`issues`](https://github.com/pglombardo/pwpush/issues?q=is%3Aissue).
- [x ] I've searched the project's [`discussions`](https://github.com/pglombardo/PasswordPusher/discussions).

## ❓ Question

Hello Mr. Lombardo. Thank you for writing this software. I tried to run a git clone in an attempt to install this to Ubuntu 22.04 installing version 3.2.0 under "rvm".
When I attempt a git clone, it said permission denied. I looked around but didn't recognize any way to get access in the Issues/Discussions. Please advise.
Thanks!

Is it possible to [...]?

## 📎 Additional context
![image](https://user-images.githubusercontent.com/123845047/215365617-db3b2b24-3a4d-4c49-849b-6357d0ec03f0.png)

**Comment by CBB3810** [comment]
Update: I just installed the docker software on Ubuntu 22.04 and pulled your docker image. Wayyy easier. Thanks.

**Comment by pglombardo** [comment]
Hi @CBB3810 - that's great to hear.  The Docker images are easier to run/manage.

I'm not sure what that github issue was though.  If it's a blocker for you in the future, file another issue and we'll investigate.

**Comment by pglombardo** [comment]
I know it a lot to take in any new tech stack...  I do it often too :-)

A few random tips/cheat sheet:

1. Password Pusher supports [basic branding](https://github.com/pglombardo/PasswordPusher/blob/master/Configuration.md#rebranding) through environment variables.  This will be extended in the future to support custom themes but no ETA yet.  Examples of branding in this [twitter thread](https://twitter.com/pwpush/status/1492083610261901312).
2. If you want to customise further, I suggest working from the source code and then making your own docker container when you are done customising.
3. Password Pusher is already quite configurable so make sure to read that [Configuration document](https://github.com/pglombardo/PasswordPusher/blob/master/Configuration.md)
4. Docker build [cheatsheet here](https://github.com/pglombardo/PasswordPusher/blob/master/containers/docker/RELEASE.md)
5. More docker container info here: https://github.com/pglombardo/PasswordPusher/tree/master/containers/docker
6. If you want to modify CSS, the files are here: https://github.com/pglombardo/PasswordPusher/tree/master/app/assets/stylesheets
7. Make sure to run `rake assets:precompile` to recompile your modified assets.  This is part of the docker build process that you can see in the [Dockerfile](https://github.com/pglombardo/PasswordPusher/blob/master/containers/docker/pwpush-ephemeral/Dockerfile#L36)

**Comment by pglombardo** [comment]
Hi @CBB3810 - did you have any luck cloning from Github?  Looking at the error again, it looks like you have to add your public key to your Github account.  Otherwise, clone via HTTP:

`gh repo clone https://github.com/pglombardo/PasswordPusher.git`

or

`git clone https://github.com/pglombardo/PasswordPusher.git`

Let me know.  Hope all is well.

**Comment by CBB3810** [comment]
Thanks! I am just seeing this. I'll follow up and check it out. Thank you!

    On Monday, February 13, 2023 at 05:08:50 PM EST, Peter Giacomo Lombardo ***@***.***> wrote:  
 
 


Hi @CBB3810 - did you have any luck cloning from Github? Looking at the error again, it looks like you have to add your public key to your Github account. Otherwise, clone via HTTP:

gh repo clone https://github.com/pglombardo/PasswordPusher.git

or

git clone https://github.com/pglombardo/PasswordPusher.git

Let me know. Hope all is well.
