### ISSUE TITLE
File Push via API

### ISSUE THREAD

**Issue by Simon-Design** [pglombardo/PasswordPusher#809]
## Checklist

- [x ] I've searched the project's [`issues`](https://github.com/pglombardo/pwpush/issues?q=is%3Aissue).
- [ x] I've searched the project's [`discussions`](https://github.com/pglombardo/PasswordPusher/discussions).

## ❓ Question

How can I Push a file via the official API?
I have a Bash script that kinda works but it pushes the path of the temp file instead of the file itself. 
Here is the script im using:
 
```
#!/bin/bash

# set the API endpoint URL
api_url="https://own.url.com/f.json"

# set the email and token for authentication
email="xxxxxx"
token="xxxxxxxxxxx"

# get the contents of the system clipboard
clipboard_contents=$(xclip -selection clipboard -o)

# create a temporary file with the clipboard contents
temp_file=$(mktemp)
echo "$clipboard_contents" > "$temp_file"

# make a POST request to the API endpoint to push the file
response=$(curl -X POST \
  -H "X-User-Email: $email" \
  -H "X-User-Token: $token" \
  --data "file_push[payload]=@$temp_file&file_push[expire_after_days]=2&file_push[expire_after_views]=10" \
  "$api_url")

# remove the temporary file
rm "$temp_file"

# extract the url_token from the response
url_token=$(echo "$response" | grep -o '"url_token":"[a-zA-Z0-9]*"' | cut -d ':' -f 2 | tr -d '"')

# check if the API request was successful
if [ -n "$url_token" ]; then
  # save the url_token in the clipboard
  echo "own.url.com/f/$url_token" | xclip -selection clipboard
  echo "File push successful! URL token saved in clipboard: own.url.com/f/$url_token"
else
  echo "File push failed!"
  echo "$response"
fi
```

is there anything im doing wrong or did i found a bug?

**Comment by pglombardo** [comment]
Hi @Simon-Design - use the `-F` parameter instead:

`curl -X POST -H "X-User-Email: <email>" -H "X-User-Token: MyAPIToken" -F "file_push[files][]=@/path/to/file/file.extension" https://pwpush.com/f.json`

or to upload multiple files at once (max 10) just repeat the parameter:

`curl -X POST -H "X-User-Email: <email>" -H "X-User-Token: MyAPIToken" -F "file_push[files][]=@/path/to/file/file1.extension" -F "file_push[files][]=@/path/to/file/file2.extension" https://pwpush.com/f.json

Note: There is a UI display bug that exists currently if you try to view JSON created pushes.  Fix going out shortly.  I'll post back there once it's out.

**Comment by pglombardo** [comment]
Hi @Simon-Design - did you get a chance to try this out?  I've tested it locally and it works here.

**Comment by pglombardo** [comment]
Hi @Simon-Design - If this is resolved for you I'll close out this issue soon.  If anything remains, let me know.  I'd be happy to help.

**Comment by Simon-Design** [comment]
Thanks a lot! I think this was just user error. Thank you for this great project!
