### ISSUE TITLE
API documentation problems, syntax error and http/https

### ISSUE THREAD

**Issue by sparr** [pglombardo/PasswordPusher#83]
https://github.com/pglombardo/PasswordPusher/wiki/Password-API

The curl example says `curl -d -X POST --data "pas...` but `-d` and `--data` are redundant and since they require a parameter then `-d -X POST` is interpreted as `-d "-X"` followed by a hostname of `POST`.

Also, the examples use `http://`; when I try to post to `http://pwpush.com/p.json` I always get a blank response. It appears that the real API requires HTTPS? `https://pwpush.com/p.json` returns expected responses.

**Comment by pglombardo** [comment]
Hi @sparr - Just an update that the API has some cleanup coming.  I'm adding support for `Authorization` headers as well.  It shouldn't break anything but just a heads up.  See #3068 

Hope all is well!
