### ISSUE TITLE
Environment variable "PWP__URL__EXPIRE_AFTER_VIEWS_MAX" doesn't work

### ISSUE THREAD

**Issue by Nelllow** [pglombardo/PasswordPusher#864]
## 🐛 Bug Report

Hello ! 

First, thanks for this app. It's really usefull.

Here is our problem : 

Changing the environment variable "PWP__URL__EXPIRE_AFTER_VIEWS_MAX" in a docker-compose file doesn't work

### Code sample

![image](https://user-images.githubusercontent.com/77050866/220865668-d9a188ba-0bb5-4cf1-b8a4-3af1535709d6.png)

### Environment

Where are you running/using Password Pusher?

- [ ] pwpush.com
- [X] Docker
  - [ ] pwpush-ephemeral
  - [X] pwpush-mysql
  - [ ] pwpush-postgres
  - [ ] custom image
- [ ] Heroku
- [ ] Digital Ocean
- [ ] Microsoft Azure
- [ ] Google Cloud
- [ ] AWS
- [ ] Source Code
- [ ] Other (please specify)

If applicable, what version of Password Pusher?

The release version.

## 📈 Expected behavior

we want the users not to be able to change the maxiumum of view before expiration, 1 view max

**Comment by pglombardo** [comment]
Confirmed.  The view is missing the `max` setting in the [form](https://github.com/pglombardo/PasswordPusher/blob/5e87449439c9f282a45423a55c5b3f41bdd15f36/app/views/urls/new.html.erb#L63-L70) - thanks for pointing this out @Nelllow!

I'll see if I can put in a fix soon.

**Comment by Nelllow** [comment]
Thanks you ! Can you let me know in this thread when the fix is ready ?

**Comment by pglombardo** [comment]
Will do for sure @Nelllow.  Should be sometime next week.

**Comment by pglombardo** [comment]
Hi @Nelllow - the fix is in https://github.com/pglombardo/PasswordPusher/pull/933.  Going out soon.
