### ISSUE TITLE
problem running the application in a subfolder

### ISSUE THREAD

**Issue by tibo59** [pglombardo/PasswordPusher#905]
## 🐛 Bug Report

Hello Peter,
we use the PWP__RELATIVE_ROOT feature, "Runs the application in a subfolder"
For example, PWP__RELATIVE_ROOT: "pwpush"
It's useful because it allows us to use passwordpusher on a web portal (reverse proxy) with other web applications, with a url like:
https://portal.examp.le/pwpush
I see that not all items are hosted behind /pwpush for example (there may be others):
`<link` `rel="apple-touch-icon"` sizes="57x57" `href="/assets/apple-icon-57x57-c2d34ae21a25a9309ce6ee488be162e44cf160ee77fab45cec8a90aaa5b18ab6.png">`

This is a problem for us because we have to redirect the paths to /assets at the web portal level, among all the other web applications that could be in conflict with this path /assets

## 🔬 How To Reproduce

see html source code/links

### Code sample

<link rel="apple-touch-icon" sizes="57x57" href="/assets/apple-icon-57x57-c2d34ae21a25a9309ce6ee488be162e44cf160ee77fab45cec8a90aaa5b18ab6.png">

docker compose

environment:
      PWP__DEFAULT_LOCALE: fr
      PWP__RELATIVE_ROOT: "pwpush"

### Environment

- [ ] pwpush.com
- [X ] Docker
  - [ ] pwpush-ephemeral
  - [ ] pwpush-mysql
  - [X ] pwpush-postgres
  - [ ] custom image
- [ ] Heroku
- [ ] Digital Ocean
- [ ] Microsoft Azure
- [ ] Google Cloud
- [ ] AWS
- [ ] Source Code
- [ ] Other (please specify)

If applicable, what version of Password Pusher?
Latest.

## 📈 Expected behavior

All items are hosted behind /pwpush (for example)

**Comment by pglombardo** [comment]
True - good find.  I'll see if I can fix this soon.

**Comment by FixFlare** [comment]
I just wanted to throw my hat in the ring on this issue.

I got approval from my company to deploy this to share temporary passwords around the company only to find it wouldn't work behind our reverse proxy because of the asset URLs

Would love to see this fixed.

**Comment by pglombardo** [comment]
I'm sorry to hear that @FixFlare - my apologies for the issue.  This is a bug in the base framework.  Is it possible you could instead use a virtual host and a dedicated subdomain?

The other alternative (besides getting this issue fixed) would be to do URL rewrites for everything `/assets` and `/rails/active_storage/blob` which isn't ideal but would work.

**Comment by FixFlare** [comment]
> I'm sorry to hear that @FixFlare - my apologies for the issue.  This is a bug in the base framework.  Is it possible you could instead use a virtual host and a dedicated subdomain?
> 
> The other alternative (besides getting this issue fixed) would be to do URL rewrites for everything `/assets` and `/rails/active_storage/blob` which isn't ideal but would work.

Sorry for the late reply.  That's what I ended up doing actually, seems to work.

Is the workaround provided at that issue you linked not applicable here?

Thanks

**Comment by pglombardo** [comment]
Since support for running in a subfolder has been dropped and the time passed I'll close out this issue.  @tibo59 / @FixFlare - please let me know if any issues remain regarding this issue.


For anyone else coming to this issue: support for running in a sub-folder has been removed in #1959.  It's possible but problematic and hard to support.  And with new upcoming features, the problems will even be more soon.

Apologies for anyone running in this matter.  Given the amount of work to be done in this project, my limited time and the few people running in a subfolder - it had to be cut to simplify things.

I'll close out this issue but if anything remains feel free to comment or open a new issue.
