### ISSUE TITLE
Unable to change theme

### ISSUE THREAD

**Issue by mzch** [pglombardo/PasswordPusher#929]
## Checklist

- [x] I've searched the project's [`issues`](https://github.com/pglombardo/pwpush/issues?q=is%3Aissue).
- [x] I've searched the project's [`discussions`](https://github.com/pglombardo/PasswordPusher/discussions).

## ❓ Question

I use Passenger as an app server and I put an environment variable in `apache` config file as below:
```apache
  SetEnv PWP__THEME 'morph'
```
But the theme is not changed.

How can I set a theme instead of `default`?

## 📎 Additional context

I patched `app/assets/stylesheets/application.scss.erb` as below:
```diff
--- application.scss.erb.orig   2023-03-16 18:51:46.202212440 +0900
+++ application.scss.erb        2023-03-16 18:44:25.586207212 +0900
@@ -31,7 +31,7 @@
 
 @import "bootstrap";
 
-@import "themes/<%= ENV.fetch('PWP__THEME', 'default') %>";
+@import "themes/<%= ENV.fetch('PWP__THEME', 'morph') %>";
 
 a em.bi.bi-trash:hover {
     cursor:pointer;
```
And then execed `RAILS_ENV=productioin bundle exec rake assets:precompile`, so I can get `morph` theme. But this way is not elegant.

**Comment by pglombardo** [comment]
How are you running the application?  Source, docker container?

**Comment by pglombardo** [comment]
I found an issue with the Docker containers:  You also have to set `PWP_PRECOMPILE=true` to recompile the assets on container boot.  😞   I'll update the documentation to reflect this.

**Comment by pglombardo** [comment]
It's been a long while since I've used Passenger.  I just checked the docs and it says to use `passenger_env_var`:
https://www.phusionpassenger.com/library/config/nginx/reference/#passenger_env_var

So a potential configuration would be:

```passenger
passenger_env_var PWP__THEME morph;
passenger_env_var PWP_PRECOMPILE true;
```

Could you try this out and let me know?

**Comment by mzch** [comment]
Hi @pglombardo , sorry being late. I fixed this issue as follows:

1.  login as PasswordPusher user.
2. `export PW__THEME morph`
3. `RAILS_ENV=production bundle exec rake assets:precompile`
4. reload apache

I know the theme can't be changed dynamically.

Thanks!

**Comment by pglombardo** [comment]
That's excellent to hear.  Thanks for the update!
