### ISSUE TITLE
Update Themes.md: Custom Bootstrap Themes

### ISSUE THREAD

**Issue by Viajaz** [pglombardo/PasswordPusher#930]
It should be mentioned in [Themes.md](https://github.com/pglombardo/PasswordPusher/blob/master/Themes.md) that a full and custom Bootstrap theme can be added as a CSS file (Eg: `/opt/PasswordPusher/app/assets/stylesheets/themes/mycustomtheme.css`) and then specified in using the appropriate environment variable (Eg: `PWP__THEME=mycustomtheme`)

**Comment by pglombardo** [comment]
That's a good point!  I didn't think of that 😂

**Comment by Viajaz** [comment]
Hopefully this means theming will be more stable now, I keep doing custom theming only for new and improved theming to break it 😄

**Comment by pglombardo** [comment]
That understandable and apologies for that.   Now that there is official support with an clear implementation pattern, I'll do everything I can to maintain existing customisations in the future although I don't expect to touch this feature again for a long time once it's stable.

**Comment by pglombardo** [comment]
Added documentation on how to add an entirely new theme:
https://github.com/pglombardo/PasswordPusher/blob/master/Configuration.md#adding-an-entirely-new-theme-from-scratch

Thanks @Viajaz - until the next issue/feature or request 😉
