### ISSUE TITLE
custom.css gets loaded before application.scss

### ISSUE THREAD

**Issue by jplitza** [pglombardo/PasswordPusher#931]
## 🔬 How To Reproduce

1. Put something in the app/assets/stylesheets/custom.css that is supposed to override a builtin style

### Code sample

Don't make the heading yellow in dark mode:
```css
@media (prefers-color-scheme: dark) {
    .display-1 {
        color: inherit;
    }
}
```

### Environment

Where are you running/using Password Pusher?

- [ ] pwpush.com
- [ ] Docker
  - [ ] pwpush-ephemeral
  - [ ] pwpush-mysql
  - [ ] pwpush-postgres
  - [ ] custom image
- [ ] Heroku
- [ ] Digital Ocean
- [ ] Microsoft Azure
- [ ] Google Cloud
- [ ] AWS
- [x] Source Code
- [ ] Other (please specify)

If applicable, what version of Password Pusher?

v1.26.10

## 📈 Expected behavior

Since `@import "./custom.css";` is at the end of `application.scss.erb`, the custom style should override the builtin style.

## 📎 Additional context

Instead, the precompiled `application-*.css` starts with
```css
@import url(/assets/custom-d8438bce0c5c43a8f3972f783fdb6f1a322cb01a4c6eb972d9a13a06b980d6e7.css);
```
and then everything else (builtin theme) follows

We previously patched the `application.scss` manually to include an `@import "custom";` at the end, which required the custom stylesheet to be named `custom.scss` but worked correctly. I don't know if this is caused by the `./` prefix or the `.css` extension.

**Comment by pglombardo** [comment]
Hi @jplitza - did you run `bin/rails asset:precompile` to recompile the CSS?

**Comment by pglombardo** [comment]
Apologies - I found the bug.  Calling `@import 'custom.css'` vs `@import 'custom'` has some odd behaviour.  Fix incoming.
