### ISSUE TITLE
Disable access on main page for certain IP/Subnet and use personal certificate.

### ISSUE THREAD

**Issue by technofab** [pglombardo/PasswordPusher#944]
Meanwhile the issue #939 I hope to find a solution, I pull 2 questions.

I will use the "source" edition.. and my boss ask a way to block the main page where we can insert password to share, only to some ip/subnet; and full access for the page link of shared password. There is a way to work with this behaviour?

We also want use SSL certificate emitted with our internal CA. Is that possible?

**Comment by technofab** [comment]
Ciao e grazie, 
Yes, I'm going to that solution. When found an affordable configuration With NGINX or Apache HTTPD i post here the example for someone needs too.

**Comment by pglombardo** [comment]
Closing this out as we now have the [public gateway](https://docs.pwpush.com/docs/public-gateway/).
