### ISSUE TITLE
Can`t use Azure Storage for File Push

### ISSUE THREAD

**Issue by burak40** [pglombardo/PasswordPusher#983]
## 🐛 Bug Report

If I try to enable File Enable via Azure Storage then the application crashes. I'm getting this error 2023-04-03T13:46:24.376268059Z [8] ! Unable to load application: KeyError: Missing configuration for the as Active Storage service. Configurations available for the test, local, amazon, google en microsoft services.

These settings has been configured
PWP__ENABLE_FILE_PUSHES:true
PWP__FILES__STORAGE:as
PWP__FILES__ENABLE_BLUR:true

PWP__FILES__AS__STORAGE_ACCOUNT_NAME:storageaccount
PWP__FILES__AS__STORAGE_ACCESS_KEY:secretkey
PWP__FILES__AS__CONTAINER:containername (already created by me)

I tried with different secret key 1 and key 2 in Azure, still not working. I typed "as" in capital letters, still not working. 

### Environment

Where are you running/using Password Pusher?

- [x] pwpush.com
- [x] Docker
  - [ ] pwpush-ephemeral
  - [ ] pwpush-mysql
  - [x] pwpush-postgres
  - [ ] custom image
- [ ] Heroku
- [ ] Digital Ocean
- [x] Microsoft Azure
- [ ] Google Cloud
- [ ] AWS
- [ ] Source Code
- [ ] Other (please specify)

**Comment by pglombardo** [comment]
Hi @burak40,

Could you try setting `PWP__FILES__STORAGE:microsoft`?

That setting specifies which entry to use in [storage.yml](https://github.com/pglombardo/PasswordPusher/blob/master/config/storage.yml#L23-L27).

This difference between "as" and "microsoft" is a bit confusing and could probably be improved.

**Comment by burak40** [comment]
Hi @pglombardo ,

Thanks for your help it's working now.
