### ISSUE TITLE
Unable to start application anymore

### ISSUE THREAD

**Issue by burak40** [pglombardo/PasswordPusher#987]
## 🐛 Bug Report

I added custom domains in Azure and it worked very well. After doing this I changed only one parameter PWP__HOST_DOMAIN to the new domain. Application restarted, but now it's not starting, even if I revert the changes (custom domain, and the parameter) 

This is the error message:

2023-04-04T09:57:34.139535071Z exec containers/docker/pwpush-postgres/entrypoint.sh: exec format error
2023-04-04T10:00:20.490208107Z exec containers/docker/pwpush-postgres/entrypoint.sh: exec format error
2023-04-04T10:03:19.374608119Z exec containers/docker/pwpush-postgres/entrypoint.sh: exec format error
2023-04-04T10:06:09.269924091Z exec containers/docker/pwpush-postgres/entrypoint.sh: exec format error
2023-04-04T10:16:09.097960315Z exec containers/docker/pwpush-postgres/entrypoint.sh: exec format error

I tried also to set parameter PWP__PRECOMPILE false, but still not working

Where are you running/using Password Pusher?

- [x] pwpush.com
- [ ] Docker
  - [ ] pwpush-ephemeral
  - [ ] pwpush-mysql
  - [x] pwpush-postgres
  - [ ] custom image
- [ ] Heroku
- [ ] Digital Ocean
- [x] Microsoft Azure
- [ ] Google Cloud
- [ ] AWS
- [ ] Source Code
- [ ] Other (please specify)

If applicable, what version of Password Pusher?

### Screenshots

<img width="470" alt="image" src="https://user-images.githubusercontent.com/23256937/229764556-09edbe7f-2a3c-4c49-b3fa-bc173289d5da.png">

**Comment by pglombardo** [comment]
What tag?  Try using `release` or downgrading to an older tag.

> pwpush-postgres/entrypoint.sh: exec format error

This odd/never seen.  I'm running `release` on pwpush.com.  See if you can swap tags and what affect it has.

**Comment by pglombardo** [comment]
Hi @burak40 - found the issue - working on a fix.

**Comment by pglombardo** [comment]
Docker has an issue with tagging multi-arch builds (it doesn't support it).  The wrong arch was pushed to the `release` tag.  It should be fixed now.  Could you confirm?

**Comment by burak40** [comment]
Hi @pglombardo , yes its working now ! Thanks again
