### ISSUE TITLE
Failing to start up container, exec format error

### ISSUE THREAD

**Issue by rgallo** [pglombardo/PasswordPusher#988]
## 🐛 Bug Report

After updating this morning on the release branch, I'm getting this error and my container is shutting down:

`standard_init_linux.go:230: exec user process caused: exec format error`

I have Watchtower set to update this container automatically, the last time before today it was updated was February 18th.

## 🔬 How To Reproduce

1. Start docker container

### Environment

Where are you running/using Password Pusher?

- [ ] pwpush.com
- [x] Docker
  - [x] pwpush-ephemeral
  - [ ] pwpush-mysql
  - [ ] pwpush-postgres
  - [ ] custom image
- [ ] Heroku
- [ ] Digital Ocean
- [ ] Microsoft Azure
- [ ] Google Cloud
- [ ] AWS
- [ ] Source Code
- [ ] Other (please specify)

If applicable, what version of Password Pusher?

pglombardo/pwpush-ephemeral:release

**Comment by pglombardo** [comment]
Hi @rgallo - which container tag and arch are you using?  arm or amd?

**Comment by pglombardo** [comment]
I got it - fix incoming.

**Comment by pglombardo** [comment]
Docker has an issue with tagging multi-arch builds (it doesn't support it).  The wrong arch was pushed to the `release` tag.  It should be fixed now.  Could you confirm?

**Comment by rgallo** [comment]
Looks good now, thanks!
